### ISSUE TITLE
no microphone for incoming calls

### ISSUE THREAD

**Issue by bcnero** [andyholmes/gnome-shell-extension-gsconnect#1013]
Hello!

When I set up KDE Connect (android 10 - kernel 4.9.118-19869079) on my Samsung note9, the microphone is mute for incoming calls. (Partner cannot hear me) When I click on speakers, my microphone works too. My microphone works immediately for outgoing calls. In terms of rights, I have already withdrawn all rights to the microphone and telephone areas from KDE Connect, unfortunately without success ...

any ideas? Thanks

**Comment by andyholmes** [comment]
It doesn't sound like anything GSConnect could cause. I would recommend opening a bug report against kdeconnect-android in the KDE bug tracker at https://bugs.kde.org

**Comment by ferdnyc** [comment]
Hm, yeah I wonder. I agree it doesn't seem like this can _possibly_ be GSConnect's issue, I'd be kind of surprised if it's KDE Connect's either.

When you set up KDE Connect, @bcnero, by any chance did you _also_ pair the phone and your PC over Bluetooth? The symptoms sound a lot like what you'd get if the phone was automatically routing call audio to a Bluetooth audio device — a capability many PCs will advertise on their Bluetooth interfaces, and Android has a habit of automatically enabling Bluetooth audio if it's available when it pairs with another device.

The fact that you say you have to hit the **Speaker** icon, rather than the **Microphone** (mute) icon, is what makes me really think this could be an audio routing issue. Although... if you can hear the _caller_ (presumably through the phone's earpiece speaker), then it's weird that the microphone would be disabled, _or_ that hitting the speakerphone button would enable it, instead of switching the call to speakerphone.

Anyway, it's been 20 days, hopefully you solved this by now.
