### ISSUE TITLE
Dark Panel Icon / HiDPI issue in user menu?

### ISSUE THREAD

**Issue by benfeatherstone** [andyholmes/gnome-shell-extension-gsconnect#102]
I am not sure what is causing these issues. I am assuming it is because I have a 3200 x 1800 screen, but the phone icon and the battery indicator are not display correctly as they are on the third picture.
![screenshot from 2018-05-14 10-56-29](https://user-images.githubusercontent.com/7890249/40010912-d2277cc8-576b-11e8-9903-fe7bcf1b91c3.jpg)

I have tried using different icons packs, but it keeps using the light icon on each one.
![screenshot from 2018-05-14 10-56-46](https://user-images.githubusercontent.com/7890249/40010914-d28c2d1c-576b-11e8-8fd4-ef8301ca7450.jpg)

The light icon in the panel looks decent when it is selected, but I am not sure how it will work if it is the dark icon. 
![screenshot from 2018-05-14 10-57-16](https://user-images.githubusercontent.com/7890249/40010915-d2a16f56-576b-11e8-9079-e2f1f8dcee60.jpg)

Clearly, these aren't major issues. All the functionality seems to work just fine. Just wanted to help where I could. I love this project.

**Comment by andyholmes** [comment]
> I am assuming it is because I have a 3200 x 1800 screen, but the phone icon and the battery indicator are not display correctly as they are on the third picture.

This was due to a CSS change in Gnome Shell 3.28 that was fixed in v11, which is still in review on the extensions website. v11 is available on the releases page for download.

> The light icon in the panel looks decent when it is selected, but I am not sure how it will work if it is the dark icon.

Generally, symbolic icons like these are dealt with properly by the UI by being titled `foo-symbolic`, which lets the desktop know it can change the color to match the background color. Unfortunately the names of the icons are along the lines `smartphoneconnected` so the Shell doesn't know they're symbolic. These are already 'standardised' names between GSConnect and KDE Connect and implemented in several icon themes, so it will have to be dealt with at that level.

**Comment by benfeatherstone** [comment]
Thanks for the quick response. I will keep an eye out for the new version and file issues with the icon maintainers.
