### ISSUE TITLE
clipboard sync not working on GNOME 3.38

### ISSUE THREAD

**Issue by preIdiotWeb** [andyholmes/gnome-shell-extension-gsconnect#1023]
Clipboard sync was working perfectly but when I upgraded from Ubuntu 20.04 to Ubuntu 20.10 it does not works.

**Comment by ykhurshid** [comment]
I'm having this issue as well, how/if did you manage to resolve this?

**Comment by eode** [comment]
For anyone else who finds this:

The issue is not with GSConnect, but with Android 10 and the KDE Connect app.  Android 10 has denied access to applications reading the clipboard unless they are explicitly pasted into by user activity.

Solution is to expand the KDE Connect permanent notification, and select "Send Clipboard".

If you want this to change, you need to take it up with the KDE Connect Android App.  There are known workarounds, but they require implementation in the android app itself to work.

**Comment by tareko** [comment]
Thank you for this. I can't find where in the KDE Connect bugzilla I should track this issue. I've [searched as best I can](https://bugs.kde.org/buglist.cgi?quicksearch=kdeconnect%20android%20clipboard). Is there an open bug for this?

tarek : )
