### ISSUE TITLE
Missing features when connecting between two GSConnect instances.

### ISSUE THREAD

**Issue by ReyLeonardAmorato** [andyholmes/gnome-shell-extension-gsconnect#108]
**Browse Files**
Plugin missing from options.
![screenshot from 2018-05-15 15-05-32](https://user-images.githubusercontent.com/38913802/40042260-4fba7162-5853-11e8-841e-091a0a5ca7ee.png)
![screenshot from 2018-05-15 14-44-27](https://user-images.githubusercontent.com/38913802/40042265-55174090-5853-11e8-8495-ad1c5f4eda65.png)
![screenshot from 2018-05-15 15-01-15](https://user-images.githubusercontent.com/38913802/40042266-555534fe-5853-11e8-82d4-82c5532eda2a.png)

**Media Player Control**
Plugin missing from options.

**Remote Input**
Plugin missing from options.

**Screen Lock**
Plugin is enabled but no way to implement.

**Comment by andyholmes** [comment]
> Browse Files

Probably this is unlikely to be supported between desktops. As far as I know this would require root access to set up, spawning an sftp server for the current user and then passing the user's password, all of which would be pretty insecure.

> Media Player Control

Forwarding MRPIS client control between desktops is not currently supported and would require exporting a mock DBus service. It's planned to eventually implement, but it's not a priority right now and probably won't be worked on until I merge the rewrite into master.

> Remote Input

Also currently not supported, but might be one day. Passing mouse events between desktops might never be implemented, since it requires grabbing the mouse from the desktop and kind of awkward to do without a screencast. Passing keyboard events is planned since the Android app supports it, but both of these are really better done on the desktop with RDP or VNC.

> Screen Lock

Screen lock is basically a dead plugin that was never even really fully supported on KDE Connect, as far as I know. It will probably be removed the next time I remember.

**Comment by ReyLeonardAmorato** [comment]
> As far as I know this would require root access to set up, spawning an sftp server for the current user 

If the user already has an ssh server running, that would solve the root issue right?

>  passing the user's password, all of which would be pretty insecure.

Is it not possible to use existing public ssh keys the user has or generate new ones for this purpose?
Even if that's not possible, the password won't be transferred in plaintext as the connection is encrypted from end-to-end, no?

Correct me if I'm wrong but I think it as the same logic as using the browse plugin for an android phone.

**Comment by andyholmes** [comment]
Yep, both KDE Connect and GSConnect implement sftp the same way.
