### ISSUE TITLE
Does it have Cinnamon compatibility?

### ISSUE THREAD

**Issue by dikonov** [andyholmes/gnome-shell-extension-gsconnect#118]
I am excited about this project by Gnome-shell but I would like to use it with a Cinnamon (gnome3 fork) desktop and a Sailfish OS phone (a native client is under development at https://github.com/R1tschY/harbour-sailfishconnect). 
Please, consider, making it compatible with Cinnamon as well.

**Comment by andyholmes** [comment]
I have no idea if Cinnamon is API compatible with stock Gnome Shell or what would be required to make it compatible. Have you tried installing it?

**Comment by SamBurgos** [comment]
Well, at least on Archlinux which I tried, I haven't been able to add it to Cinnamon, I installed it and pull many Gnome and Gnome Shell dependencies; however; it doesn't work, I am not really sure if it needs a rework/rewrite or to at least adapt/change the parts that call Gnome Shell specifically to the Cinnamon ones

There might be some libraries that can be used by both Cinnamon and GS but otherwise you might need to do some changes

**Comment by andyholmes** [comment]
Well, if Cinnamon has broken compatibility with Gnome Shell extensions GSConnect would probably have to be forked. Unfortunately I don't use Cinnamon or know much about it and I don't have the time to maintain two separate versions, sorry :/

**Comment by andyholmes** [comment]
Closing since I can't do much about this without breaking compatibility with Gnome Shell.
