### ISSUE TITLE
Google Wifi, cannot see my device on the network

### ISSUE THREAD

**Issue by brittyazel** [andyholmes/gnome-shell-extension-gsconnect#128]
Using GSConnect on a Google-WIfi mesh network, and my phone is unable to find my computer and visa versa. Using KDE Connect allows my phone and computer to sync, but with GSConnect they cannot.

Further, if I refresh the device list in the Android App I get a real quick "OnePlus" flash in the kde connect extension, but it only last about half a second before it disappears again.

**Comment by brittyazel** [comment]
Woah, ok so the version on the extensions page is not the latest. Version 11 seemed to have fixed it. 
When will the version in the extensions page be updated by any chance?

**Comment by andyholmes** [comment]
The review process is volunteer based and sometimes lengthy since it's mostly for security/stability purposes. There's usually a delay around release dates (when developers are busy) and exam/mid-term time (when students are busy), but it's hard to say. With larger extensions like GSConnect it sometimes takes someone who can review actually using it for awhile to decide it's good to go.
