### ISSUE TITLE
Add Do Not Disturb/Silent mode for devices

### ISSUE THREAD

**Issue by PlugaruT** [andyholmes/gnome-shell-extension-gsconnect#13]
Sometimes, there is a need to stop disconnect the phone from the laptop. I guess it will be a usefull addition.

**Comment by andyholmes** [comment]
What's the use case for disconnecting a device, rather than just unpairing?

This is possible, but there are a couple problems with disconnecting a device. The protocol is really designed to connect devices whenever possible, and usually reconnect if they disconnect. The connection process looks like this:

* Device broadcasts identity to entire network  -> Server responds with TCP connection
* Device accepts connection -> Server sends identity
* TLS certificates are exchanged to authenticate

In this case it might be possible to ignore the broadcasted identity and not connect, but it means keeping a list of devices to not connect to around. So it would be more "disconnect and don't ever reconnect until I say so", which is pretty much like unpairing.

***OR***

* Server broadcasts identity to entire network -> Device responds with TCP connection
* Server accepts connection -> Device sends identity
* TLS certificates are exchanged to authenticate

In this case, the identity of the device isn't known until a connection is already established, so it would have to connect, receive identity and disconnect.

The server actually sends it's identity pretty often, and Android devices do too, so both of these would happen pretty frequently.

**Comment by PlugaruT** [comment]
I was just thinking, because there are times when I don't want to unpair, but only to temporarily disconnect the service to stop receiving notifications. When I'm in a meeting or having a presentation on my laptop. You don't want to receive notifications from phone and also you still want to remain connected on same network. It's just an idea 🙂 thanks anyway for your work.

**Comment by andyholmes** [comment]
That's okay, I'm not against the idea, I've just never had a reason to disconnect myself. Maybe something like a "silence/silence for X hours" option similar to Android would be a better option?

**Comment by PlugaruT** [comment]
Yeah, it's exactly what I want. To just silent notifications for a time.

**Comment by andyholmes** [comment]
Sorry, for the long delay on this. This is mostly implemented in my local branch, but won't be merged until v10 unfortunately. I'll mark it as targetted for v10.

**Comment by stark-dev** [comment]
Hi! First of all, thanks again for your great work!

I was thinking about the implementation of the "Do not disturb" feature. It came to me while I was having an Hangouts call with Telephony plugin enabled. I received a phone call and the PC volume went down.
Of course, the simplest solution would be to disable the plugin while having an Hangouts call =)

There is a "Do not disturb" option in almost any Android smartphone I guess, which disables notifications. Could it be exploited/integrated in GSConnect?
At this stage, even with the DND option active, Android forwards notifications to GSConnect. Would it be possible to control this option through GSConnect (i.e., adding a DND button that enables the same mode on phone and at the same time avoids notification forwarding from phone to GSConnect)?

Maybe this feature needs some changes in the Android application, so it's just an idea I was thinking of, I don't know if it is feasible and if there is something already implemented.

Thanks again!

Mauro

**Comment by andyholmes** [comment]
> There is a "Do not disturb" option in almost any Android smartphone I guess, which disables notifications. Could it be exploited/integrated in GSConnect?

It's possible, but it would have to be forwarded from the Android app, which it's currently not. In the GSConnect rewrite there is a *Do Not Disturb* switch the *Mobile Settings* menu that pops up a dialog like this:

![dnd](https://user-images.githubusercontent.com/1265208/40515928-ac6cd834-5f63-11e8-9ff4-0bbd84cd6557.png)

When it's on, phone notifications are still received and put in the message tray but don't pop-up or make a sound. For now that's the best I can do. I would recommend you file a bug upstream with KDE Connect if you want better integration of the phone's DND feature.

On the other hand, the system volume adjustments are made based on Telephony events, which are different from Notifications, so that wouldn't change anything in that regard.

**Comment by stark-dev** [comment]
Ok, so with the new DND feature I would not see the pop up call notification, but GSConnect will still lower volume/pause media (according to Telephony config).
I personally think it would be nice to have a DND that follows Android settings, but as you confirmed it should be first implemented in the app. I will try to file a bug upstream ;)

Anyway, your DND is perfectly fine, I'm now using a system wide DND extension from [pop-os](https://github.com/pop-os/gnome-shell-extension-do-not-disturb), but I heard some rumours about a similar feature coming with GNOME 3.30.

It's funny that we ask for integrating notifications with desktop and than we ask for a way to stop them :stuck_out_tongue_closed_eyes: 

Thanks again for your work,

Mauro

**Comment by andyholmes** [comment]
Implemented in rewrite now.
