### ISSUE TITLE
v7 cannot pair a new device and other issues 

### ISSUE THREAD

**Issue by Baldrs** [andyholmes/gnome-shell-extension-gsconnect#15]
OS: Arch Linux latest updates
Gnome: 3.26

Extension is unable to pair with my phone. It is unable to detect any devices. I was able to pair with my PC using patched v5, but it didn't show my Galaxy S7 in the devices list, nor it did show an icon when the respective option was checked. 
Also when I attempted to redo pairing with v7, it didn't work. When phone was paired, I was able to use some of the features from the side of the phone, however nothing worked from extension side as the pair didn't show up.

**Comment by andyholmes** [comment]
If you enable "Debug Mode" in the About Page of preferences do you get any useful output?

> OS: Arch Linux latest updates
> Gnome: 3.26

If you are using the package from Arch, this is known not to work since the extension doesn't work from a system directory, see #12 

> I was able to pair with my PC using patched v5, but it didn't show my Galaxy S7 in the devices list, nor it did show an icon when the respective option was checked.

What is "patched v5"?

> Also when I attempted to redo pairing with v7, it didn't work. When phone was paired, I was able to use some of the features from the side of the phone, however nothing worked from extension side as the pair didn't show up.

When a device becomes unpaired on only one side (eg, Phone thinks it's paired, Computer thinks it's not) the behaviour is not always well defined since KDE Connect Android 1.6.x doesn't re-confirm paired state when prompted. I've filed a [bug report](https://bugs.kde.org/show_bug.cgi?id=386763) for this issue on the KDE Connect bugzilla, but it hasn't been confirmed. Maybe it's been fixed in 1.7-beta already.

**Comment by Baldrs** [comment]
When I turn on a debug mode, it shows 4 terminals, all of them showing this output:
```
JS WARNING: [/home/baldrs/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 243]: reference to undefined property "deviceId"
JS LOG: error closing UDP listener: Gio.IOErrorEnum: Error closing socket: Bad file descriptor
JS LOG: UdpListener: using port 1717
JS LOG: TcpListener: using port 1717
JS LOG: 0 devices loaded from cache
JS WARNING: [/home/baldrs/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 243]: reference to undefined property "deviceId"
JS LOG: UdpListener: using port 1717
JS LOG: TcpListener: using port 1717
JS LOG: 0 devices loaded from cache
JS WARNING: [/home/baldrs/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 243]: reference to undefined property "deviceId"
```

No I've installed extension manually as per wiki.

By "Patched v5" I mean the last file from Fedora 26 issue: 
![image](https://user-images.githubusercontent.com/814651/33986156-6a036a84-e0c5-11e7-8d1d-39ed0640d576.png)

**Comment by Baldrs** [comment]
Also, in second tab, "Extension", it says: 
```
[gsconnect@andyholmes.github.io]: extension.SystemIndicator._serviceVanished()
```

**Comment by andyholmes** [comment]
> JS LOG: UdpListener: using port 1717
> JS LOG: TcpListener: using port 1717

If the daemon is using port 1717 that means another program is using port 1716, the normal port for KDE Connect protocol. If you are also running KDE Connect or another service it will confuse the Android app since it only expects packets on one port. In that case you'll have to manually enter your computer's IP in the Android app.

> JS WARNING: [/home/baldrs/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 243]: reference to undefined property "deviceId"

This could mean GSConnect is receiving a broken identity packet or something went wrong generating the local identity packet, but in either case there should be more errors. Pretty much nothing has changed with the daemon since the patched v5 you referenced, other than checking a setting for the WebExtension.

> JS WARNING: [/home/baldrs/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 243]: reference to undefined property "deviceId"
> JS LOG: error closing UDP listener: Gio.IOErrorEnum: Error closing socket: Bad file descriptor

If these are really the first two lines of the debug log, it makes me think there was a problem updating the extension since it implies that turning on Debug stopped the daemon, which shouldn't happen anymore.

 Could you try:

    rm -rf /home/baldrs/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io

And then re-install?

**Comment by Baldrs** [comment]
So running netstat to check ports as you've suggested revealed kdeconnect running, seems that it somehow remained after I've purged KDE from my system(I guess it was explicitly installed), so I've killed it, uninstalled, then I've killed daemon running on port 1717 and reinstalled extension. It solved my issue, because actually app was connecting to kdeconnect daemon without any interface, rather than your extension. Thanks!

**Comment by lnicola** [comment]
I also ran into this, but I don't know whether the reason was `kdeconnectd` or if the extension was loaded multiple times (!). E.g., when I enabled the debug logs, three windows showed up instead of a single one.

Anyway, if you have this issue, also try logging out and back in.
