### ISSUE TITLE
A way to disable GSConnect?

### ISSUE THREAD

**Issue by null-von-sushi** [andyholmes/gnome-shell-extension-gsconnect#152]
I am not sure _how_, but it seems GSConnect is running even if I am running KDE. I don't even use GDM. And nope, I don't have the actuak KDE connect installed.

How is GSConnect automatically launched? I assume it was a gnome shell extension, and therefore, without running gnome, extensions should not run either? Are there any service files or .desktop files ? Thanks!

**Comment by andyholmes** [comment]
Just like KDE Connect, GSConnect uses a server process for communicating with devices. It can be activated over DBus by either the Shell extension, Nautilus extension or Chrome/Firefox extension. Currently it installs a DBus service file under `~/.local/share/dbus-1/`.

Since there's no special hook for extensions that are manually disabled or uninstalled, the service file is never removed but will fail to start silently if the extension is uninstalled.

**Comment by null-von-sushi** [comment]
I figured it out. Somehow the Firefox addon was launching an instance of `gjs` and this extension. Disabling the FF addon also stopped the extension from starting.

**Comment by null-von-sushi** [comment]
Oops, thanks for the reply. For some reason I didn't see it before.
