### ISSUE TITLE
GSConnect rewrite hard-depends on systemd

### ISSUE THREAD

**Issue by SebastianMcMillan** [andyholmes/gnome-shell-extension-gsconnect#154]
I run a modified version of GNOME that makes it fully functional without systemd and when I tried compiled and installed said branch, I cannot enable the extension because it cannot find child process or directory systemctl, a core component of systemd.

I am interested if it would be possible to make it not require systemd and if it does require it, why it does it, as I don't want systemd on my system, but I would love to have this extension.

Here is the error when I attempt to load the preferences:
```
GLib.SpawnError: Failed to execute child process “systemctl” (No such file or directory)

Stack trace:
  gsconnect.installService@/home/smcmillan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:255:5
  init@/home/smcmillan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:21:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```
Here is the project page of the patched GNOME Project:
[https://github.com/dantrell/gentoo-project-gnome-without-systemd](url)

~~EDIT: This also applies to the main branch as well.~~

EDIT2: It does not apply to main branch, it was just left over. But I would like to use the rewrite branch for the experimental bluetooth support.

**Comment by andyholmes** [comment]
In my current local repo, systemd scripts have been removed I just have a lot of changes that haven't been pushed to wip-rewrite. The systemd service was only a temporary band-aid for `dbus-broker` support that was solved (mostly) another way. As far as I know GSConnect should run as long as Gnome Shell runs and doesn't *rely* on systemd inherently, but since I use it myself I can't really say for sure. Here's build without the systemd service from my local branch:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2172395/gsconnect.andyholmes.github.io.zip)

Fair warning, some things are broken, some things are flaky, some things will be removed, some switches just don't do anything, etc.

**Comment by SebastianMcMillan** [comment]
That's good news to hear! I'll test this build out.

I do expect stuff to be flaky and whatnot, but thanks for the update!

**Comment by andyholmes** [comment]
Closing this as it should be fixed in wip-rewrite now.
