### ISSUE TITLE
Browse Files setting is broken by default

### ISSUE THREAD

**Issue by aral** [andyholmes/gnome-shell-extension-gsconnect#162]
It looks like the Browse Files setting is broken by default as it requires a dependency that must be installed separately (also see #90).

Could we either:

  * Install the dependency as part of GSConnect, or
  * Detect if the dependency is installed and, if not, give people a link to where they can install it (and disable the ability to enable the extension until it can be enabled).

Currently, my experience was the following:

1. I turned on the Browse Files option
2. I saw an exclamation icon and the option stayed off so I knew that something had gone wrong but had no clue what.
3. I went to turn on Debug mode to see what happened and saw the error messages in the console.
4. On a whim, decided to hover over the exclamation mark icon and then saw the error message in a tooltip.

**Comment by aral** [comment]
Documented instructions for enabling the Browse Files feature and floated a suggestion for adding a Gnome design principle for avoiding this pattern in the future at: https://ar.al/2018/08/03/how-to-enable-the-browse-files-setting-in-gsconnect/

**Comment by andyholmes** [comment]
Thanks for taking an interest in this and describing your expected experience well. The current behaviour of showing a warning icon with a tooltip was a pattern inherited from Gnome Tweaks. It's admittedly not very user friendly, even if a user were familiar with that application.

How GSConnect is installed is somewhat relevant here. If the extension is installed from your distributions package system, then it falls to the packager to mark it as a (possibly optional) dependency. On the other hand, if the extension is installed from [extensions.gnome.org](https://extensions.gnome.org) it can't be bundled with `sshfs` since it is an architecture (eg. 64-bit) and system (eg, Linux, BSD) dependant binary.

Strictly speaking, `sshfs` is not a hard dependency of GSConnect since the only functionality relying on it is remote browsing and that is only supported by Android devices. Most extensions aren't as elaborate as GSConnect, so there's no existing facilities for marking dependencies or prompting users to install packages. I can look into using PackageKit to install dependencies, but it might not be possible to support all distributions.

**Comment by andyholmes** [comment]
PackageKit support is now included in master, this is about as close as I can get to shipping external software:

![screenshot from 2018-09-25 07-07-14](https://user-images.githubusercontent.com/1265208/46020414-32cfba00-c093-11e8-90ec-5dd88ae7590c.png)
