### ISSUE TITLE
Country Code issue

### ISSUE THREAD

**Issue by luksol** [andyholmes/gnome-shell-extension-gsconnect#19]
A bit of an odd issue. If I receive an SMS message, number is being recognized, I can display it in a popup window (SMS App) and respond. However, when I then check my phone, those messages are not sent, even though they appear in a correct conversation. If I pick a contact from the list in SMS App and send message this way, it is being sent correctly. The only difference is that when message arrives and I respond to it, it has a phone number prefixed with country code (+44 for UK). When I send it after picking a contact from the list, it only ha a 0 prefix. So I guess my phone app is picky when it comes to sending SMS to a number with country code prefix. If I add the country prefix with 00 instead of + (so 0044 instead of +44) it all works well. Is it possible to add feature that will convert + to 00? it would mean that I could have my conversation in a single window in SMS App.

**Comment by andyholmes** [comment]
> A bit of an odd issue. If I receive an SMS message, number is being recognized, I can display it in a popup window (SMS App) and respond. However, when I then check my phone, those messages are not sent, even though they appear in a correct conversation.

This part there's not much I can do about, since the Android app doesn't respond with any success/failure when an SMS is sent (yet; there's a TODO note in the source).

> The only difference is that when message arrives and I respond to it, it has a phone number prefixed with country code (+44 for UK). When I send it after picking a contact from the list, it only ha a 0 prefix. So I guess my phone app is picky when it comes to sending SMS to a number with country code prefix.

Until just now GSConnect sent SMSs to the number stripped of all non-digits, not the full text number, but the latest commit changes it to send the number as is; hopefully that will fix this.

> If I add the country prefix with 00 instead of + (so 0044 instead of +44) it all works well. Is it possible to add feature that will convert + to 00? it would mean that I could have my conversation in a single window in SMS App.

Android should be able to use any number it can receive from and the phone number matching is extremely convoluted already, so I'd like to avoid this if possible...If you could give this Zip a try and see if it fixes your problem it would be preferrable:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1564005/gsconnect.andyholmes.github.io.zip)

If not, report back and I'll look into it more

**Comment by luksol** [comment]
Partially Worked! Thank you! What works is that when I reply to +44 
messages, they are now being correctly sent, no errors. If I have 
already sent a message to a 0 number though, the reply from +44 opens in 
new window, is not displayed in old 0 one. But this is a minor thing, I 
can live with that. Thank you again!

Luke

**Comment by andyholmes** [comment]
I think the right fix for all these phone number problems is to somehow get libphonenumber working in GJS. I'm going to close this and open #30 to track that.
