### ISSUE TITLE
GSConnect Indicator Menu Missing

### ISSUE THREAD

**Issue by rdabra3** [andyholmes/gnome-shell-extension-gsconnect#190]
Following is a snapshot my system (Manjaro 17.1.12 Gnome 3.28), I installed GSConnect and I am using it now. The thing is that the phone is connected but it doesn't show that my phone is connected in the GSConnect Settings. And also the GSConnect Indicator Menu is missing.
![screenshot_2018-09-16-13-55-04](https://user-images.githubusercontent.com/25562421/45594430-33dc5980-b9b8-11e8-846b-70b249a4564b.png)
![screenshot from 2018-09-16 13-54-34](https://user-images.githubusercontent.com/25562421/45594431-3d65c180-b9b8-11e8-9d81-e425fc3656f2.png)
![screenshot from 2018-09-16 13-55-16](https://user-images.githubusercontent.com/25562421/45594432-3d65c180-b9b8-11e8-93d9-b712b7730484.png)

**Comment by rdabra3** [comment]
Note: I am able to use all the features through the mobile app from android to manjaro but the vice-versa is not causing the problem.

**Comment by andyholmes** [comment]
Since the public name of GSConnect is "**rdabra3**" while the name in the Android app is "**rdabra3@JARVIS**" which is typical of KDE Connect, you have probably paired your device with the KDE Connect server (`kdeconnectd`) and not GSConnect.

GSConnect doesn't work well at all with `kdeconnectd` running and it's very common for the server to keep running even after it's uninstalled (until you logout/login next). You can check this in a terminal with `pidof`:

```sh
$ pidof kdeconnectd
18839
$ kill -9 18839
```
You should then stop the GSConnect server and let the shell extension start it again for you:

```sh
$ kill $(ps aux | grep '[d]aemon.js' | awk '{print $2}')
```

This is confusing for a lot of users, especially since it appears that GSConnect is working. It's something I plan on detecting automatically in the next version. If that doesn't solve the problem, let me know.

**Comment by rdabra3** [comment]
Thanks, 
I am now seeing the GSConnect Indicator Menu but the Browse Files function is not working.
![screenshot from 2018-09-16 16-18-21](https://user-images.githubusercontent.com/25562421/45595593-2af58300-b9cc-11e8-8c88-d71182a6c2a3.png)

**Comment by andyholmes** [comment]
Well, that's one issue :)

There's possibly two options here. If `sshfs` is not installed, that's an easy fix and you should be able to just disable/enable the plugin. There's also a known issue with the recent version of OpenSSH/OpenSSL, possibly also if you have an Oreo phone.

If it's one of the second two cases, there's a branch of the Android app that should work, but it's not yet released. Let me know and I'll see if I can convince Albert to push a new release or I might be able to build you one for now, but it will break your updates in Google Play.

**Comment by rdabra3** [comment]
Thanks For The Reply,
I am actually Lollypop 5.0 on my phone, I just installed sshfs on my system and it's working now. Thanks once again.
![screenshot from 2018-09-16 17-07-32](https://user-images.githubusercontent.com/25562421/45596042-2ed8d380-b9d3-11e8-9ee1-689eee4f1ac7.png)
