### ISSUE TITLE
[v13-alpha2] tray icon duplicated many times after lock screen

### ISSUE THREAD

**Issue by AdamKane41** [andyholmes/gnome-shell-extension-gsconnect#216]
Same installation from a week ago built with Latest Master from git. Ran without brakage since.

But now out of the blue came back from 10 min shower when I unlocked the lock screen I was greated with this;
![cty](https://user-images.githubusercontent.com/30092603/46307897-36c57580-c586-11e8-9ea8-e1fd933ca5b6.png)

**Comment by andyholmes** [comment]
Ah, this was reported by another tester as well. I believe this is related to the upstream issue in Gnome Shell:

[#177 Gnome-shell disables and enables extension in sub-optimal manner (quadratically).](https://gitlab.gnome.org/GNOME/gnome-shell/issues/177)

I'd guess that this is caused by the asynchronous init of the DBusObjectManager in `extension.js`, but I'm not sure how it could be addressed properly yet.

**Comment by andyholmes** [comment]
It seems like my patch might've fixed this one, but I'm going to leave this open for awhile since it's a rare bug. Let me know if it happens again.

**Comment by etu** [comment]
@andyholmes It seems stable to me now :+1:, been testing a while. Suspending, unlocking and so on.

**Comment by andyholmes** [comment]
Alright, I'll mark this closed for now. I'll be releasing RC1 pretty soon here.
