### ISSUE TITLE
branch wip-rewrite not working at all (for me)

### ISSUE THREAD

**Issue by mirko** [andyholmes/gnome-shell-extension-gsconnect#218]
I know it's work-in-progress, but apparently this branch appears to work to some degree at least for some people - while it doesn't work for me at all.

I git-pull every couple of weeks, build it, install it, enable it in gnome-tweaks and.. nothing is happening. Also clicking the settings-icon for the extension just nothing is happening.

From what I read, it appears to work for some people at least - that's why I allow myself to open this ticket, even though explicitly declared as wip.

I'm fairly familiar with linux/programming and happy to help out / provide more information / debug output if requested.

Current version: 1d98a752c1207b699bfc8fa1f7efc4294f8a8709
OS: Debian testing/buster
Gnome: ii  gnome-shell    3.30.0-1     amd64

**Comment by andyholmes** [comment]
> From what I read, it appears to work for some people at least - that's why I allow myself to open this ticket, even though explicitly declared as wip.

That's okay, this is a good time for testers to jump in, especially 3.30 users since I'm not there yet. Because of the commit 1d98a75 (about Aug. 22) I'm thinking you might be stuck on an old branch now.

A few weeks ago wip-rewrite was merged into master and then deleted, so I'm thinking your local clone still has the branch `wip-rewrite` which isn't been getting any new commits now. Could you try checking out the master branch and building from that?

**Comment by mirko** [comment]
Ahhh, I missed the merge to master!
So I already used the new version for a while, without knowing (always switched back to master when I noticed the wip-rewrite branch doesn't work for me).
Thanks!
