### ISSUE TITLE
[DEVEL] Mousepad on Wayland

### ISSUE THREAD

**Issue by wvengen** [andyholmes/gnome-shell-extension-gsconnect#249]
It would be nice if mouse input could be made to work on Wayland too. There may be options, let's gather them here, so that if someone wants to implement it, there are some starting points.

**Comment by wvengen** [comment]
https://stackoverflow.com/questions/31051173 suggests opening `/dev/uinput` for writing

**Comment by wvengen** [comment]
Do feel free to close when this is out-of-scope (since it is Waylands design to prevent part of this).

**Comment by rugk** [comment]
It's in the FAQ.

**Comment by rugk** [comment]
But I agree that it would be good to have an issue here to track this…

Because AFAIK work is done on this, too, as e.g. remote access via [pipewire](https://pipewire.org/) is in beta and can be tested

**Comment by nocoZ** [comment]
just installed ubuntu 18.10 and vanilla Gnome. "Remote input" only works in Gnome on Xorg

**Comment by andyholmes** [comment]
Correct, currently AT-SPI still doesn't have support for simulating mouse events on Wayland (See: [Wayland + Accessibility](https://wiki.gnome.org/Accessibility/Wayland)).

**Comment by auscompgeek** [comment]
It looks like someone has successfully used the remote desktop API to send mouse events: https://bugzilla.gnome.org/show_bug.cgi?id=709999#c5

**Comment by andyholmes** [comment]
Interesting and promising. At the moment, this doesn't seem likely to be usable by GSConnect, since mutter must be compiled with support for remote desktop and it relies on gnome-remote-desktop/pipewire (not core yet I think?).

Hopefully there's some movement on before gnome-shell 3.34, so we might see support included in atspi2. I'll keep an eye on this though, thanks for the link :)

**Comment by auscompgeek** [comment]
Pipewire support in Mutter 3.32 seems to be enabled by default, judging by how Arch Linux packages it at least.

**Comment by andyholmes** [comment]
It's hard to tell for sure without spinning up some VMs, but Ubuntu seems to [explicitly build mutter without remote desktop support](https://git.launchpad.net/~ubuntu-desktop/ubuntu/+source/mutter/tree/debian/rules?h=ubuntu/disco#n34), although it's probably on in Fedora.

If it's used by atspi2 we can be sure it will be available, but otherwise we will rely on pipewire, gnome-remote-desktop and gnome-shell >= 3.32. [gnome-remote-desktop](https://gitlab.gnome.org/jadahl/gnome-remote-desktop) seem to still be living in a private repository, which is why I don't think it's considered core yet.

A proof-of-concept would be nice here. Implementing a low-latency client for the DBus interface (or two) in GJS might have some performance issues. AT-SPI is also effectively a DBus wrapper, but we use the C library so it's not too bad.

**Comment by jnsh** [comment]
Does the built in mouse accessibility support for gnome-shell/mutter 3.34 that just landed help with this?

https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/474
https://gitlab.gnome.org/GNOME/mutter/merge_requests/512

**Comment by andyholmes** [comment]
> Does the built in mouse accessibility support for gnome-shell/mutter 3.34 that just landed help with this?

What we really need is for AT-SPI to be supported on Wayland. There seems to be some movement in [atspi2-core](https://gitlab.gnome.org/GNOME/at-spi2-core/commits/master) lately, but we'll have to wait until those changes propagate to see if AT-SPI will work on Wayland.

**Comment by andyholmes** [comment]
BAM! (needs testing)

**Comment by ferdnyc** [comment]
I see a codename for v27 shaping up: "GSConnemeril Edition".

**Comment by auscompgeek** [comment]
Has anyone else actually been able to get this working? It doesn't seem to work for me on Arch Linux (despite seeing "screen is being shared" in the system menu).

**Comment by auscompgeek** [comment]
Just had a look through the dogtaild stuff. Looks like you also need `gsettings set org.gnome.desktop.interface toolkit-accessibility true` for this to work. (No restart necessary.)
