### ISSUE TITLE
Extension periodically freezes desktop

### ISSUE THREAD

**Issue by ivandotv** [andyholmes/gnome-shell-extension-gsconnect#269]
OS:fedora 28
gnome shell: 3.28.3
Extension: from website

Every hour or so desktop freezes and I get a bunch of these notifications:
![screenshot from 2018-10-26 22-16-47](https://user-images.githubusercontent.com/390700/47590722-7b69e400-d96d-11e8-83db-36e9518b34ec.png)

**Comment by andyholmes** [comment]
This is an upstream issue with the extension subsystem, [!177 Gnome-shell disables and enables extension in sub-optimal manner (quadratically).](https://gitlab.gnome.org/GNOME/gnome-shell/issues/177)

Basically in some cases Gnome Shell will try and repetitively load extensions, which doesn't do well with GSConnect. This "error" is GSConnect aborting the previous load, each time a new load is started. I'll try and quiet down these notifications a bit, since `Operation was cancelled` should only happen in these cases (I think).
