### ISSUE TITLE
Register as handler for "sms:" URI's

### ISSUE THREAD

**Issue by nielsdg** [andyholmes/gnome-shell-extension-gsconnect#27]
It would be very cool if GSConnect could register as handler for sms URI's.
This would mean that an application could implement the following code:

```js
Gtk.show_uri_on_window(null, "sms:123456789", Gtk.get_current_event_time())
```
... which would then show either a portal on which app to open, or just open a GSConnect SMS window immediately.

I'm not sure how to actually do the registering (I think it's probably going to be something with `GLib.AppInfo`'s methods) and I don't even know if it's possible. But asking doesn't hurt of course :)

**Comment by andyholmes** [comment]
This sounds like a neat idea.

I think this is possible with both `AppInfo.set_as_default_for_type("x-scheme-handler/sms")` or with a combination of `xdg-mime` and a `.desktop`. The AppInfo route would be preferrable, but sometimes these methods don't export outside the process they're run in (like `Gio.Vfs.register_scheme()`). I already use a .desktop file to use GNotifications and DBusActivatable anyways so I'll give that a shot first.

**Comment by andyholmes** [comment]
I think I've got this mostly figured out. I added the `MimeType` field to the `.desktop` and call `Gio.AppInfo.add_supports_type()` when the extension is enabled.

I've tested it with `xdg-open`, `Gtk.LinkButton` and `GLib.show_uri_on_window()`, but I'm not sure about sandboxed apps like flatpak since I don't have any experience with those.

I've implemented the [RFC for sms URIs](https://tools.ietf.org/html/rfc5724) with multiple numbers and a body variable like:

```
sms:555-5555,555-5556?body=foo%20bar
```

The RFC also allows for additional variables, although I haven't implemented any. It could be possible to support a `device` variable, or to define a default device for SMS. Right now if there's more than one device supporting the telephony plugin a popup is shown, though it feels a bit clunky:

![screenshot from 2017-12-30 16-07-15](https://user-images.githubusercontent.com/1265208/34458136-9044c036-ed7b-11e7-9b0c-b5cc9874aef2.png)

If you wanted to test it out, I'd be happy to hear your feedback:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1594875/gsconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
This is pretty much done and committed. I assume this will be used with things like libfolks/gdata/gnome-contacts so the number matching is more lenient than the `tel:` spec allows. Numbers can be passed without pre-processing and let's me match incoming `sms:<folks-number>` to GSConnect's cache of `<folks-number>`'s. I currently don't cache `tel:` numbers from folks or gdata, but if you have any clue to how common it is for those fields to be populated, I could start doing that.

For reference the number field regex is essentially `[+]?[0-9A-F*#().-]+` and also allows single spaces.

**Comment by nielsdg** [comment]
Hey Andy, just wanted to say thank you for implementing this so quickly!

I've added [an issue](https://gitlab.gnome.org/GNOME/gnome-contacts/issues/83) for adding support for multiple actions and have a WIP-branch for this somewhere. I'm hopeful that it will be landing in Contacts 3.28 :)

**Comment by andyholmes** [comment]
No problem, it's a good idea. I hope to integrate a lot more with the desktop and do more cool things like this. Let me know if you have any more ideas.
