### ISSUE TITLE
disconnect on screen blanking

### ISSUE THREAD

**Issue by bstecklum** [andyholmes/gnome-shell-extension-gsconnect#272]
gnome 3.28.0
ubuntu 18.04
installed from github

I guess this was a bug already which is back now. As soon as the smartphone screen shuts off, gsconnect disconnects.
While this is another issue I want to mention it nevertheless. Installing gsconnects in the recommended way (deleting extension folder, extractting the new one) deletes previous contacts.

**Comment by ferdnyc** [comment]
> As soon as the smartphone screen shuts off, gsconnect disconnects.

What phone, and what OS? (Android version / vendor release / etc.)

I'm not seeing the same thing, even with v13, so could the issue be on the phone end instead? 

Android keeps adding more power-saving features to reduce background processing, and some vendors add their own on top of the built-in OS features (like Samsung's "Samsung+" app) — perhaps something is terminating the KDE Connect app's background service when the screen shuts off?

**Comment by bstecklum** [comment]
Well, not really solved. After I pressed the power button to blank the screen,
the same faulty behavior as before happens, even _after_ reboot. Forcing the
screen to be on (with Keep screen on) does help either. As soon as the blanking
time-out is over the device disconnects.

**Comment by andyholmes** [comment]
I know that this is definitely an issue on Oreo+, because background services now require a persistent notification (although that's fixed in the next Android release), but I don't often experience this on 7.1.1 (I keep a device on "last" release and one on current).

What would really be telling is to plug the device into a charger and see if it has the same behaviour. If keeping it plugged in fixes this, then it's definitely Android and I would glance around Settings quickly.

If there's nothing that addresses this, or no special feature in your ROM, maybe open a bug upstream with KDE Connect requesting the persistent notification as a option for < 8.0 devices. I think currently it's toggled automatically based on a API version check.

**Comment by ferdnyc** [comment]
Also check **Settings > Connections > Wi-Fi > Advanced > Keep Wi-Fi on during sleep** (that's the Android 7.0 preference location on my Galaxy S6, anyway), if the phone is turning off the network interface the connection's going to be dropped. I have mine set to "While charging", the other options are "Always" and "Never".

(Re: "Show persistent notification", it's displayed as an option in **KDE Connect > Settings** on my Android 7.0 phone — I'm running app version 1.10, from the Google Play beta program.)

**Comment by bstecklum** [comment]
Good catch, it does not disconnect while charging. The router lists the device
as connected while the screen is blanked.

**Comment by ferdnyc** [comment]
> Good catch, it does not disconnect while charging. The router lists the device as connected while the screen is blanked.

In that case, Enabling "Show persistent notification" (in the KDE Connect app's Settings) might allow the background service to stay alive even when not charging.

**Comment by ferdnyc** [comment]
> In that case, Enabling "Show persistent notification" (in the KDE Connect app's Settings) might allow the background service to stay alive even when not charging.

...If there is such a switch in the Settings menu, or a Settings menu at all. Google Play's "What's New" info seems to indicate it was added recently, and may only be in the beta versions of KDE Connect right now.

**Comment by andyholmes** [comment]
Yeah, the next release is going to be huge and they're pushing commits like crazy, but the Beta release is pretty up to date. There is a build server setup, but to install those APKs you might have to uninstall your current first, because I think they're unsigned:

https://binary-factory.kde.org/view/Android/job/kdeconnect_android/

**Comment by bstecklum** [comment]
I installed the beta and checked "Show persistent notification". Seems to work
fine now :-)

**Comment by andyholmes** [comment]
Give it some testing for bit, and if you're confident it's all good, feel free to close the issue.

**Comment by kmahyyg** [comment]
It is not working here. I've already enabled `persistent notification`. I just moved from KDE to Gnome and I found that with the above solutions, GSconnect stil let phone disconnect from computer on screen blanking. However, this phone is offering network hotspot for PC, so the problem may be on GSConnect instead of my phone. Because that my phone is working perfectly while I was using kdeconnect on PC.

Phone model: Huawei G9 Plus
System: Android 7.1
Already gives all permission to the application.

**Comment by kmahyyg** [comment]
According to my observation, the connection closed **30s** after phone screen get blanked. I'm trying to use `wireshark` to trying to get the packet sending order.

**Comment by kmahyyg** [comment]
This problem may be solved by sending `TCP Keep-Alive` packet from both side, after screen blanking I could see that the phone client still trying to send `KeepAlive` per 10 seconds, however, after first three packets have been ACKed by the computer client, the fourth packet **HAS NOT BEEN ACKED BY ANY PROGRAM**. Finally, the fourth `TCP KeepAlive` packet is going through TCP Retransmission process and finally get a `RST`. So tne connection closed.

The same problem existed while using `kdeconnect` and `indicator-kdeconnect-git` in PC.

My OS: Arch Linux.

I think this issue should be reopened.

**Comment by andyholmes** [comment]
Hi, this is very likely a result of Android being put into doze mode and not responding to keepalive packets. The protocol describes a total keepalive of 3x10s for 30s without a response before closing. In GSConnect this is done here:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/18d6b92a3bc061c784a5bbd6ed5965444ce36a15/src/service/protocol/lan.js#L352-L354

In KDE Connect Desktop this is done [here](https://github.com/KDE/kdeconnect-kde/blob/2687ee54833d6788fd56c7818d70d6b24d3bd71a/core/backends/lan/lanlinkprovider.cpp#L456-L480). In KDE Connect Android it appears the keepalive code was changed in [this](https://github.com/KDE/kdeconnect-android/commit/71dc71357821fa06cb3987f758a9223d6c287788#diff-0e593c9b134286c9566bf302a54281cb) commit.

Please file an upstream issue at https://invent.kde.org/kde/kdeconnect-android/issues

**Comment by kmahyyg** [comment]
> Hi, this is very likely a result of Android being put into doze mode and not responding to keepalive packets. The protocol describes a total keepalive of 3x10s for 30s without a response before closing. In GSConnect this is done here:
> 
> [gnome-shell-extension-gsconnect/src/service/protocol/lan.js](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/18d6b92a3bc061c784a5bbd6ed5965444ce36a15/src/service/protocol/lan.js#L352-L354)
> 
> Lines 352 to 354 in [18d6b92](/andyholmes/gnome-shell-extension-gsconnect/commit/18d6b92a3bc061c784a5bbd6ed5965444ce36a15)
> 
>  connection.socket.set_option(6, 4, 10); // TCP_KEEPIDLE 
>  connection.socket.set_option(6, 5, 5);  // TCP_KEEPINTVL 
>  connection.socket.set_option(6, 6, 3);  // TCP_KEEPCNT 
> In KDE Connect Desktop this is done [here](https://github.com/KDE/kdeconnect-kde/blob/2687ee54833d6788fd56c7818d70d6b24d3bd71a/core/backends/lan/lanlinkprovider.cpp#L456-L480). In KDE Connect Android it appears the keepalive code was changed in [this](https://github.com/KDE/kdeconnect-android/commit/71dc71357821fa06cb3987f758a9223d6c287788#diff-0e593c9b134286c9566bf302a54281cb) commit.
> 
> Please file an upstream issue at https://invent.kde.org/kde/kdeconnect-android/issues

So sorry, I mistakenly took the Android IP address as the PC IP Address.

**Comment by kmahyyg** [comment]
https://bugs.kde.org/show_bug.cgi?id=404163  Please give me a vote here. Thanks.

**Comment by andyholmes** [comment]
Hi, I don't think there's any voting on bugzilla. KDE Connect has migrated to GitLab at https://invent.kde.org/kde/kdeconnect-android, so in future you should open bugs there instead of https://bugs.kde.org.

**Comment by ferdnyc** [comment]
@andyholmes 

I checked w/ KDE Connect about that, since their wiki page bugzilla link hadn't been updated, and Albert [reports](https://invent.kde.org/kde/kdeconnect-kde/issues/1#note_915) that the KDE Cabal<sup>1</sup> have decreed that bugzilla will remain the canonical location for user bug reports, with GitLab issues being used "to track high level project goals/roadmap milestones (like we did with Phabricator tasks)". (He didn't sound 100% thrilled with the idea, but The Cabal Has Spoken.)

**Notes**:
1. (I assume they have a cabal, [all the cool kids do](https://en.wikipedia.org/wiki/Wikipedia:Words_of_wisdom#On_Wikipedia_and_the_Cabal).)

**Comment by andyholmes** [comment]
Ah that sucks, GitLab issues are so much nicer than archaic bugzilla trackers. I guess it's always nice to take a trip back to the late 90's though - **Zarro ~~Boogs Found~~ Usability!**

**Comment by ferdnyc** [comment]
I mean... I suppose it could be worse. They could be using Trac, a bugtracker / project manager so poorly-designed it was already 10 years out of date on the day it launched!
