### ISSUE TITLE
Unhelpful error when Sound Effects support is missing

### ISSUE THREAD

**Issue by smkamranqadri** [andyholmes/gnome-shell-extension-gsconnect#276]
I am using pop os.

@/home/mkamran/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/sound.js:17:15
_loadComponents@/home/mkamran/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:672:21
vfunc_startup@/home/mkamran/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:736:9
_init@/home/mkamran/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:97:9
@/home/mkamran/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:864:2

**Comment by andyholmes** [comment]
Thanks for reporting. This error means GSConnect can't find libcanberra/GSound which are used to play sound effects. Right now this is only when you use "Find My Phone"/"Locate" to find the device running GSConnect.

Since you're on an Ubuntu derivative, you should be able to use the preferences to install this (or you can install `gir1.2-gsound-1.0` package using your package manager):

![screenshot from 2018-10-26 11-57-22](https://user-images.githubusercontent.com/1265208/47609947-d21efe80-d9fd-11e8-8e6e-20bef2dae388.png)

I think this error should should be a little more helpful, so I'll try and fix that for the next release.
