### ISSUE TITLE
Overlapping of Notifications 

### ISSUE THREAD

**Issue by Abtektas** [andyholmes/gnome-shell-extension-gsconnect#281]
Every message, media or another changes that making notifications and similar notifications are not gone disappear when a familiar new notification come or grouping each other. 
![screenshot from 2018-10-28 22-46-57](https://user-images.githubusercontent.com/15087318/47621081-6e7ef900-db03-11e8-8f2b-f410ac4abf1a.png)

**Comment by andyholmes** [comment]
Right, so there's two types of notifications here. The one at the top is actually GNOME Shell's persistent notification for MPRIS players.

The rest of the notifications are unique notifications, so GSConnect is treating them as it's being told. The best way to deal with this would be to disable notifications on Android for Spotify and let the MPRIS notification keep updated with the correct track.

**Comment by Abtektas** [comment]
But was that happening in v12 ? I couldnt remember like that overlapping

**Comment by andyholmes** [comment]
v12 received notifications in the same way, nothing has changed in the protocol. In fact the only thing that changed in this regard is that the usual limit of 3 notifications GNOME Shell imposes was lifted, since it applies to what GNOME Shell considers an application (which is GSConnect as far as it knows).

This is what an average notification provides us:

```js
{
  // Unix timestamp from when the packet was sent, so changes
  // everytime it's sent (device connects/requests notifications)
  "id": 1540759939984,
  "type": "kdeconnect.notification",
  "body": {
    // Hash of the icon
    "payloadHash": "ab58bf84f10e26ab15e215faa1d13980",
    // This is the actual notification id
    //    v----------------------------------------------v
    "id": "0|com.matusmak.fakenotifications|41|null|10111",
    "appName": "Fake Notifications",
    "isClearable": true,
    "ticker": "Test Title: Test Body",
    "title": "Test Title",
    "text": "Test Body",
    // This is the timestamp when the notification was "posted",
    // which will change when Android restarts
    "time": "1540759939967"
  },
  "payloadSize": 4348,
  "payloadTransferInfo": {
    "port": 1740
  }
}
```

Unfortunately the `notification->body->id` is the only true judge of whether a notification is unique or not (at least that we are provided). Here's another one that shows that the remote device is considering this a new notification and not an update:

```js
{
  "id": 1540760321431,
  "type": "kdeconnect.notification",
  "body": {
    "payloadHash": "ab58bf84f10e26ab15e215faa1d13980",
    // ------------------------------------v--v
    "id": "0|com.matusmak.fakenotifications|42|null|10111",
    "appName": "Fake Notifications",
    "isClearable": true,
    "ticker": "Test Title: Test Body",
    "title": "Test Title",
    "text": "Test Body",
    "time": "1540760321377"
  },
  "payloadSize": 4348,
  "payloadTransferInfo": {
    "port": 1740
  }
}
```

I don't use Spotify myself, but in principle an application should notify Android when a notification is closed/withdrawn, which we will receive as:

```js
{
  "id": 1540761055724,
  "type": "kdeconnect.notification",
  "body": {
    // ------------------------------------v--v
    "id": "0|com.matusmak.fakenotifications|42|null|10111",
    // notification has been closed on remote device
    "isCancel": true
  }
}
```

Or alternatively we can close it if the app (eg. Spotify) says we can:

```js
{
  "id": 1540761056669,
  "type": "kdeconnect.notification.request",
  "body": {
    // ----------------------------------------v--v
    "cancel": "0|com.matusmak.fakenotifications|42|null|10111"
  }
}
```

So we're kind of stuck because we must use the ID that Android tells us or we won't be able to close or know if it has been closed (if somehow we managed to come up with some tricky way of telling if the notification was unique.

**Comment by Abtektas** [comment]
Now I see, actually grouping the each app's notification might be a good solution but ID is making a problem here. But v13 has really more user-friendly interface and actions. Anyway, It's not a big problem. I just wondered it, thank you for the detailed reply.

**Comment by andyholmes** [comment]
No problem, it's sometimes unclear how exactly these things work under the hood, but if I write it out once I can just point people here now.
