### ISSUE TITLE
"Do Not Disturb" fails at times.  

### ISSUE THREAD

**Issue by dln949** [andyholmes/gnome-shell-extension-gsconnect#284]
Desktop computer: Ubuntu (Bionic) 18.04.1, GNOME Shell 3.28.3, GSCONNECT v13.

Android devices: kde connect 1.8.4.

I have set the gsconnect "Do Not Disturb" toggle to off until I manually reset it to on.  However, I still get messages from the android devices appearing on my computer's desktop.  

I have attached a screenshot to show that the desktop computer is still getting notifications from the android devices.  (All the notifications shown are from the android devices.)  
![screenshot from 2018-10-28 19-44-17](https://user-images.githubusercontent.com/8601150/47624393-27d0d500-daea-11e8-9876-0ef473a64601.png)

**Comment by andyholmes** [comment]
I'm sure you noticed the last group is not from Android (related to #260 that's been fixed in master), but coming the the Shell extension. Those are not silenced since they don't belong to GSConnect, but actually gnome-shell.

Basically how the Do Not Disturb feature works is by preventing the Shell from popping up notifications visibly or making a sound, however they will still be received and appear in the message tray (silently). Are these notifications are popping up/making sound when received, or are they just appearing in the tray?

If they are popping up/making sound, can you confirm that when you set Do Not Disturb to "Until I Turn This Off" the setting is properly set?

    $ dconf read /org/gnome/shell/extensions/gsconnect/donotdisturb
    2147483647

And just to make sure this isn't a weird timezone problem, this should be something reasonable:

    $ gjs -c "print(imports.gi.GLib.DateTime.new_now_local().to_unix())"
    1540779730

**Comment by dln949** [comment]
Thank you for the explanation.  I did not understand the distinction you describe.  

No, the "android" messages are NOT popping up, nor are they making sounds.  So, I now realize that all is working as intended.  

Thanks.
