### ISSUE TITLE
Using Nautilus’ sharing API

### ISSUE THREAD

**Issue by fbruetting** [andyholmes/gnome-shell-extension-gsconnect#29]
I asked how this would be implemented in Nautilus: [Link](https://gitlab.gnome.org/GNOME/nautilus/issues/183#note_21203)

Carlos wrote, that there already is an API in flatpaked Nautilus. Could you use that already? :D

**Comment by andyholmes** [comment]
Sound interesting, but it doesn't seem like this is a public API (yet) and would only work on flatpak versions of Nautilus. If the developers end up exposing a DBus portal it should be simple to support, but we'll have to wait on that.

**Comment by andyholmes** [comment]
As per Carlos Soriano's [comment](https://gitlab.gnome.org/GNOME/nautilus/issues/183#note_21249) this functionality will only be feasible to use from a flatpak'd Nautilus (which isn't even ready to go yet), so I'm going to mark this closed since making that a requirement for Nautilus integration would be pretty obtuse.
