### ISSUE TITLE
Improvements to SMS application and notifications

### ISSUE THREAD

**Issue by PunkGeekJip** [andyholmes/gnome-shell-extension-gsconnect#31]
New to reporting issues/request hope it helps:

1. No sound effects on notifications, made sure install all dependencies mentioned on the wiki.
2. Would like to see time stamps on sms messages
3. Would also like to have an option to save sms history, and ability to see them if you opened an SMS window with the specific person.
4. I saw you can't receive or send images because of KDE connect, but is it possible to show a message on the sms chat about receiving an Image.
5. Along with the Image notification, is it possible to receive the text that was sent along with the image?
6. Sometimes when I receive notifications from gsconnect, even when I close the notification it will reappear again as if it was a new notification. 
7. An option to open an sms window automatically when a text is received
8. On SMS chat window, a way to pull a list of emoticons from Characters (on fedora, not sure what other OSes use)

**Comment by andyholmes** [comment]
Obviously the telephony/SMS plugin is the coolest part about KDE Connect, but it's surprisingly the most limited by the KDE Connect protocol. Most of the SMS application and telephony features are actually giant hacks that rely on a lot best case scenarios to work at all.

Much of what you request are things I'd like too, but are either not possible or super difficult to deal with, but I'll try and give you a good run-down of what's possible, what's not, and what's unlikely to be implemented and why.

A lot more would be possible and simpler if multi-recipient conversations weren't supported. I don't use them myself, and Android hasn't supported them (via SMS) for some time, and they're kind of sham anyways since they're really just "bulk send" messages rather that true shared conversations. Unfortunately I don't have an easy way to poll users about whether anyone else actually uses that feature or I'd just do away with them.

---
> No sound effects on notifications, made sure install all dependencies mentioned on the wiki.

Sound effects for notifications are still controlled by Gnome desktop settings, see:
* Settings->Sound->Sound Effects (tab)->Alert Volume (etc)
* Settings->Notifications->GSConnect->Sound Alerts

> Would like to see time stamps on sms messages

If you mean in the SMS window, that's possible. The desktop notification timestamps are set by Gnome Shell/Gtk when the notification is posted.

> Would also like to have an option to save sms history, and ability to see them if you opened an SMS window with the specific person.

This is only partially possible and only sort of, sometimes:

* there's no guarantee GSConnect has received all messages, even successive messages, from a conversation/person
* since multi-person conversations are possible (and it's possible to add people to a conversation at any time) it would be quite difficult to determine when the previous messages should be included, or if they should be removed after a new person is added, possibly to be replaced by message history from a conversation shared by all recipients.
* messages are usually sourced from SMS "events", but sometimes have to be sourced from notifications (of unread messages) which have different timestamps and that could results in bizarre conversation histories

I understand the desire for a recent history in new conversations, but there are so many corner-cases and situations where it wouldn't work, I probably won't implement it. As far as conversation logging in general, that's probably better to do on your phone which should keep a history of all exchanged messages.

> I saw you can't receive or send images because of KDE connect, but is it possible to show a message on the sms chat about receiving an Image.
> Along with the Image notification, is it possible to receive the text that was sent along with the image?

No, KDE Connect doesn't notify about MMS messages whatsoever, not when/if they're received or any content that comes with them.

> Sometimes when I receive notifications from gsconnect, even when I close the notification it will reappear again as if it was a new notification.

If you click the (X) in the corner of notification it will only be dismissed, and will reappear next time the device connects and the unread notifications are requested. To clear/mark-as-read the notification you have to click on the body of the notification. Unfortunately GNotifications give no notice of when a notification is closed, only when it's activated (clicking on the body).

> An option to open an sms window automatically when a text is received

This probably won't be implemented because:
* there's no way to force a window to the top, and they sometimes popup behind other windows without notice
* opening a message in a window also marks it read on the phone which could result in missed messages
* GSConnect obscures the fact that sometimes SMS messages are sourced from notifications, not actual message events, which would make this only work some of the time

> On SMS chat window, a way to pull a list of emoticons from Characters (on fedora, not sure what other OSes use)

This is should already be possible via the context menu:
![emoji](https://user-images.githubusercontent.com/1265208/34549741-e3344c0c-f0bf-11e7-9993-c4be6d230cc5.png)

**Comment by PunkGeekJip** [comment]
I wonder why my fedora install came with notification sounds muted, thanks for pointing that out. I feel dumb for the Emoji insert, glad that was resolved. Hope to see the timestamp on the SMS window in the future! Thank you for explaining the other issues

**Comment by andyholmes** [comment]
No problem. I wish it were simple enough to explain to bother writing a "How GSConnect works", but it would be pages of "can't do that because can't do this because this doesn't work because the protocol doesn't...". Actually there's a ton of bugs and things that only sometimes work that I know about, but no one else has noticed yet :)

Things will get better though; a few new developers showed up on the KDE Connect project and there's been a ton of work getting done lately. I think the core team are big KDE devs so don't have a lot of time themselves, so with some new developers things might really get moving.

**Comment by M-W99** [comment]
Perhaps this isn't the proper use of an Issue page, but I saw this and just wanted to chime in a few things.

@PunkGeekJip I believe most of (if not all) the features you're looking for related to SMS/Telephony can be achieved with [PulseSMS](https://messenger.klinkerapps.com/overview/). I stumbled across it on the Play Store one day and have been using it ever since. It's pretty great.

One thing I would like to see is the ability to use Telephony just for phone calls. Since I use Pulse for SMS, I have to disable the Telephony feature or else I'd be getting duplicate notifications. That's unfortunate though because the ability to see a desktop notification when a call comes in and all that good stuff like lowering the music volume is something I'd like to take advantage of. I can make a new Issue/Request on this if that would be better for organization.

I tried switching to KDE Neon from Ubuntu w/ Unity a few days ago solely for KDE Connect, but the overall buginess, poor multi monitor support, etc. left me looking at other desktops soon after and Ubuntu 17.10 /w Gnome is probably going to be my next install (currently trying it from a USB drive). I was very glad to find MConnect, but didn't really care for all the KDE dependencies and it had a few bugs, then I found GSConnect and so far in my brief trial it's been amazing.

Thanks for providing this great piece of software!

**Comment by andyholmes** [comment]
> One thing I would like to see is the ability to use Telephony just for phone calls. Since I use Pulse for SMS, I have to disable the Telephony feature or else I'd be getting duplicate notifications.

This will probably be possible in v10, although might be a little while since there are several re-writes happening for that release.

**Comment by andyholmes** [comment]
I'm going to close this for now since the rewrite has been merged into master and much will change with the upcoming Android SMS plugin. I'll keep the points here in mind though as that's implemented!
