### ISSUE TITLE
Improve/Add verification of fingerprint

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#311]
Currently KDE Connect is more or less "Trust on first use" (TOFU). And when breaking the connection and repairing it's TOFU again…

This is not ideal from a security-perspective.

However, you can easily improve that situation:
* in the KDE Connect app, you can already view your fingerprint. This is not possible in GSConnect as far as I see. 
* However, as manual conversion is hardly useful as nearly no one will do this, introducing a QR code with the fingerprint that you can just scan in your app would be very helpful. This obviously requires some upstream/app work, but it would increase the security of the whole system very much.
   You can just scan a QR code to start a session then.

Alternatively switching to WebRTC and using a signalling protocol like https://saltyrtc.org/ (cc @lgrahl) can also be used in such a secure way with a QR code, but that would require a lot more work. (though it could enable connections from anywhere, not only in the [W]LAN)

**Comment by andyholmes** [comment]
> Currently KDE Connect is more or less "Trust on first use" (TOFU). And when breaking the connection and repairing it's TOFU again…

This is partially right. What happens is a TCP connection is opened, then TLS handshake is performed. If we know the device (by it's ID) we compare certificates and if it's valid we're "connected", otherwise we close the connection (also there's a notification so you know about fraudulent attempts). If we don't know the device, we TOFU the certificate, store it and at this point the device is "connected".

The reason certificates are trust-on-first-use in this way, is to ensure that the pairing process happens over an encrypted connection, otherwise it may be vulnerable to deviceId spoofing or maybe even MITM attacks. From here you do the manual comparison and pair requests, etc.

The SHA1 fingerprints *are* presented to the user in the notification for *incoming* pair requests, but there is no way to view them for outgoing requests (and KDE Connect never shows them). This was mentioned in #205 as a consequence of the UI changes, but not fixed before v15. In the short-term, we should probably add a popup to the device settings menu like Android so at least it's in the "same place" and we're at least not worse that KDE Connect 😉.

> However, as manual conversion is hardly useful as nearly no one will do this, introducing a QR code with the fingerprint that you can just scan in your app would be very helpful. This obviously requires some upstream/app work, but it would increase the security of the whole system very much.
> You can just scan a QR code to start a session then.

This is a really good idea and you're right, I seriously doubt anyone *actually* checks the SHA1 fingerprint because they're really long, you only get 30s before the request times out, and you don't even know it's there unless you already know it's there 🤔. A QR code would be a really easy thing for people to do, so they probably would do it. You're also right it would have to happen upstream, too.

The only problem is with desktop-to-desktop pairing, but if the QR code was just the SHA1 fingerprint, we could always fallback to the "old style". Another option I've thought of in the past is to use shortened fingerprints, like how Git does for commits. For example, `abc1234` + `efg5678` taken from each fingerprint, and then used as a short two-way pair code like Bluetooth.

**Comment by rugk** [comment]
Yeah, with "breaking the connection" I meant if you click "Unpair" in GSConnect and repair. Does not it then do TOFU again, i.e. accept a new certificate (at least the SHA-1 is shown again in the notification then.).

**Comment by lgrahl** [comment]
> For example, abc1234 + efg5678 taken from each fingerprint, and then used as a short two-way pair code like Bluetooth.

You could also derive a sequence of Emojis.

> Alternatively switching to WebRTC

Interestingly, I started writing a [KDE Connect implementation](https://vcs.zwuenf.org/lgrahl/python-kdeconnect/src/branch/master) (in Python, so it can be used on other OSes as well... dunno if that has changed in the meantime) for the purpose of extending it with WebRTC data channels three years ago but never finished it. I might give it another go at some point now that we have [aiortc](https://github.com/jlaine/aiortc).

Sorry for off-topic. Keep up your work! :smiley_cat:

**Comment by rugk** [comment]
> For example, abc1234 + efg5678 taken from each fingerprint, and then used as a short two-way pair code like Bluetooth.

Well… that's "brittle" and it can easily go wrong/be insecure. Also git is a bad example, because the (short) git commits do not guarantee security in any way. 
So the QR code is very likely the easiest and most secure.

**Comment by andyholmes** [comment]
Oh I see what you mean, this is the code here for "setting" paired sate:

```js
    _setPaired(bool) {
        this._resetPairRequest(); // <-- this just resets the 30s timer

        // For TCP connections we store or reset the TLS Certificate
        if (this.connection_type === 'tcp') {
            if (bool) {
                this.settings.set_string(
                    'certificate-pem',
                    this._channel.certificate.certificate_pem
                );
            } else {
                this.settings.reset('certificate-pem');
            }
        }

        this.settings.set_boolean('paired', bool);
        this.notify('paired');
    }
```
Basically the "connection" is always trusted, in the sense that we know the certificate the connection is using is...the certificate it's using. But this certificate isn't "per connection", it only changes if the device does it on purpose (Android app data is cleared or Desktop settings reset/erased).

Once we have "paired" (agreed that the device is who it says it is), *then* we save the certificate and any device using that deviceId _must_ use that same certificate. GSConnect actually takes it a step further than KDE Connect, because our `deviceId === certificate uuid`, so we can never be confused with another device, unless it has already stolen our certificate.

**Comment by andyholmes** [comment]
> Interestingly, I started writing a KDE Connect implementation (in Python, so it can be used on other OSes as well... dunno if that has changed in the meantime)

I remember reading your code a very long time ago :D

**Comment by andyholmes** [comment]
Since the Encryption Info dialog is now in v16, the rest of the issues here will have to be fixed upstream. Closing since we've done all we can on our side.

**Comment by pabloab** [comment]
The WebRTC bit would add the awesome feature of pairing over internet (without the need of a VPN), am I right? That issue [doesn't seems to be mentioned upstream](https://invent.kde.org/search?search=webrtc&nav_source=navbar&project_id=71&group_id=1551&search_code=true&repository_ref=master).
