### ISSUE TITLE
Request - Clearing phone notifications from desktop

### ISSUE THREAD

**Issue by M-W99** [andyholmes/gnome-shell-extension-gsconnect#33]
Clearing notifications on my phone from KDE Connect is something that I found quite useful, but doesn't seem to be a thing in GSConnect. I saw on the Notifications Plugin wiki page that it isn't possible.
Is there any chance of it being possible in the future? This is a feature that I'd love to see.

**Comment by andyholmes** [comment]
Currently it's possible to clear a notification (mark read) on your phone from your computer by clicking the body of the notification, just not by clicking the close (X) button on the notification. In future that might be fixed.

What's not possible is closing a notification on your computer from your phone. This is because of the way the notification DBus interface works. This also might be fixed in future.

**Comment by M-W99** [comment]
Oh, my bad, I just misunderstood what was on the wiki. That sounds great, I had been trying to do it by clicking the X haha.
