### ISSUE TITLE
Keyboard Input Feedback is Out of Order (Desktop-to-Android)

### ISSUE THREAD

**Issue by select** [andyholmes/gnome-shell-extension-gsconnect#333]
I tried out the keyboard input from desktop to android and it works but the text in the input box is not in the same order as on the phone (on the phone it's correct), since the connection lags sometimes a bit it's confusing if you are using the desktop input box as reference since the symbols there are in "random" order.

Also sometimes the input in the texbox is cleared while there is still text in the texbox on android.

In addition I would like to ask if it's also possible to keep the screen on on android while typing (guess I rather have to ask in KDEConnect issue tracker) It's a problem since the screen turns off while I type and the keyboard input is not send to the login screen. Which is my last question: is there a possibility to make the keyboard work for the login screen? I would love to switch on the phone with my desktop when I get a notification.

Great improvements so far! GSConnect is my favorite toy recently.

**Comment by andyholmes** [comment]
> since the connection lags sometimes a bit it's confusing if you are using the desktop input box as reference since the symbols there are in "random" order.

Yeah, this part is not quite perfect yet, one reason I've kept it as a keyboard shortcut instead of putting it in the device menu (for now). Android's sleep mode makes a lot of situations like this difficult, because sometimes I think it actually just loses packets or the connection times out while sending/receiving.

Basically, around the time this feature was added in KDE Connect, they also added an "echo" packet. This is neat because (when it works) we can send the key stroke and wait for the "echo" as confirmation before we add it to the input box (so we don't report keystrokes as successful when they aren't).

The "random" order shouldn't happen though, because the packet transfer is a regular old queue so even if there is lag they _should_ come in order. This *particular* bug could be [filed upstream](https://bugs.kde.org/buglist.cgi?quicksearch=kdeconnect&list_id=1505828); maybe there's a race condition when the phone is in sleep mode and it's queuing packets out of order. If you do that, be sure to link back here so both projects can track it.

> Also sometimes the input in the texbox is cleared while there is still text in the texbox on android.

This one is a problem. The app sends a "keyboard state" packet letting us know when it can accept input (that's our yellow bar/"Keyboard is not ready").

Usually `state=true` means you selected an input box on Android (same time your keyboard would slide-up) and `state=false` means you've "left" the entry and it's text is gone. But we also get the same state change when connection breaks, plugin is unloaded, or anything else. Basically `state=true` only means one thing, but it's hard to know what `state=false` actually means.

What would you think of the user-experience of just keeping *all* the text all the time (except backspacing which should work properly), and adding a manual clear button? I like the idea of this being all automatic, but maybe that's just not possible.

> In addition I would like to ask if it's also possible to keep the screen on on android while typing (guess I rather have to ask in KDEConnect issue tracker)

I think yeah, that would have to be an Android app thing, but I bet an easy way to sell this feature is as a setting for the keyboard plugin. So like "Option to inhibit screen timeout when keyboard is active". I think that would probably be easy to do, and their _outgoing_ keyboard/mousepad plugin does this already.

> Which is my last question: is there a possibility to make the keyboard work for the login screen?

Not sure, but I have two thoughts.

1. Recently nicofee has started to revive the `lock` plugin which is used to unlock your desktop from your phone. Maybe that could be two-way?
2. I think there is an option in the Android app to accept keyboard strokes even when a text entry is not active. I really don't know how Android translates mouse/keyboard events in their UI, but maybe you could try turning that on and sending a "spacebar" or "up arrow" keystroke or something?

> Great improvements so far! GSConnect is my favorite toy recently.

Thanks! Sometimes I wish I got more time to just play with it myself :stuck_out_tongue_closed_eyes:

**Comment by select** [comment]
Thanks for the very detailed answer. I'm working my way through your explanations and suggestions. Here is the first issue I created.
https://bugs.kde.org/show_bug.cgi?id=401203

**Comment by select** [comment]
> What would you think of the user-experience of just keeping all the text all the time (except backspacing which should work properly), and adding a manual clear button? I like the idea of this being all automatic, but maybe that's just not possible.

With the UX right now I might like the option of keeping all text though it's a bit hard to tell without trying it out. However this only really matters when the text is not mixed up, so I guess this can wait till the mix up issue is resolved, since the UX might be quite different then.

**Comment by rugk** [comment]
I did not even know this feature (desktop to Android input) is already implemented. How can I test it?

**Comment by ferdnyc** [comment]
@rugk 

1. Enable the plugin on both ends
2. Go into Mobile Settings > Device > Keyboard Shortcuts, click Keyboard, and set a shortcut to bring up the keyboard.
3. Use that (global) shortcut to pop up the input panel, and type away!

(...We should probably put that in the Wiki somewhere.)

**Comment by rugk** [comment]
Indeed, that is _very_ hidden.

Also, add a clickable entry somewhere. (also for touch devices e.g.)

Maybe create a new issue for that?

----

Also in my testing, I could not see the entry "keyboard":
![image](https://user-images.githubusercontent.com/11966684/64907417-8ac35e80-d6f2-11e9-95aa-65c1ebdb6990.png)

**Comment by ferdnyc** [comment]
> Also in my testing, I could not see the entry "keyboard":

Ahh, yeah, it's the... I guess the Mousepad plugin. Which I guess should really be renamed "Input", @andyholmes? Or "Mouse & Keyboard", to match the entry it creates under Sharing. (I can submit a PR if you concur...)

**Comment by ferdnyc** [comment]
(On the Android side the corresponding plugin is labeled "Receive remote keypresses", in English.)

**Comment by andyholmes** [comment]
@rugk Probably if you're not seeing the "Keyboard" shortcut, it's because you're running Wayland where we still disable the Mousepad plugin. To be honest, the reason the keyboard is not easier to find even on X11 is because none of the issues I listed in my first response have been fixed and might not be fixable from our side.

In GSConnect every plugin's label is it's packet namespace, like`kdeconnect.mousepad.request` => "Mousepad" with the source file being named `mousepad.js`. Generally the current names are pretty descriptive, but part of the reason "Advanced" is not called "Plugins", is because plugins should usually just be configured in their panel where there are more descriptive labels with context. Actually disabling a plugin has very little benefit and there's no safety-net for users who don't understand the end result.

In any case, the names aren't really a point of contention for me, that's just why it is the way it is now. So feel free to submit a PR for any names you think could be improved to make it easier for users.

**Comment by rugk** [comment]
Okay, good, yes I'm using Wayland. Don't know why that should not work technically, given I would be fine with an extra window and an input box there, where I write text (which then sends it to the phone).
But as I don't know the solution, this is just guessing, so I'll stop here.

**Comment by ferdnyc** [comment]
@rugk @andyholmes 

Yeah, sorry, I didn't even realize your screenshot was of the keyboard shortcuts panel, not the (not-the-)Plugins panel. Alas, Crowdin has already _very_ conclusively established that I am completely useless in German. (And quite possibly in English.)

**Comment by andyholmes** [comment]
> Don't know why that should not work technically...

You're right actually, it might work. If I recall, when I added the code that disables `mousepad` on Wayland, I tested the keyboard dialog and the "grabs" weren't working correctly, which is something we have to do catch key combinations that GNOME Shell or the window might use, like `Ctrl+Alt+F1`.

That was awhile back though, and you can tell by the amount of code comments I use how bad my memory is.

**Comment by rugk** [comment]
Well... even if (global) keyboard controls don't work (AFAIK you need a special permission to catch these global ones in Wayland), my use case would 90%ly satisfied with just writing text, i.e. a usual keyboard.
After all, there are not many hot keys/shortcuts (I know) on Android anyway.

**Comment by andyholmes** [comment]
I can't reproduce the original issue of out-of-order text, so I'm going to close this old issue. Feel free to re-open it if you can find a way to reproduce it.
