### ISSUE TITLE
Menu options don’t work

### ISSUE THREAD

**Issue by fbruetting** [andyholmes/gnome-shell-extension-gsconnect#336]
For version information, see #334.

When I click on the hamburger menu after selecting a device and there select “Connect LAN” or “Connect”, I can see absolutely nothing to happen. I don’t think that this behaviour is meaningful, or?

**Comment by andyholmes** [comment]
That's correct, this About dialog error was fixed in PR #317 and is included in the [latest release v16](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/latest). This version has been submitted for [review on extensions.gnome.org](https://extensions.gnome.org/review/8612). If you want to install v16 now, you can [review the changes yourself](https://github.com/andyholmes/gnome-shell-extension-gsconnect/compare/v15...v16) and follow the instructions for [Installing from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip).

In the KDE Connect protocol, outgoing TCP/TLS connections are never opened unsolicited. A device requests a connection by sending a UDP identity packet to the remote device and it responds by opening the connection using the information in the identity packet. The *Connect LAN* menu option functions by sending one of these identity packets to the remote device and it is then up to the remote device to respond, which may be delayed or timeout if the remote device is in sleep mode.

**Comment by fbruetting** [comment]
If then I think that there should be some feedback to the user about what happens. Like a spinner with a five-second timeout, leading to a message that there was no response, in case there was none. Currently I don’t know if something happens, nothing happens, if it still waits/tries or if there was an error.

**Comment by andyholmes** [comment]
Unfortunately this applies almost all message-types in the KDE Connect protocol. In this case, it might be better just to remove these menu items, since this is not a UI element offered in KDE Connect so there is no precedent for it anyways.

Users can wait for the devices to auto-connect, use the *Refresh* button or use the *Connect to...* dialog if there is a need.
