### ISSUE TITLE
Tap to click does not seem to work

### ISSUE THREAD

**Issue by nvisser** [andyholmes/gnome-shell-extension-gsconnect#35]
**Phone:** LG G4 running Android 7.0
**Extension version:** 9
**Gnome version:** 3.26.2
Double tap to double click seems to work, multiple fingers does not seem to work either. This did work properly in KDE, so my best guess is that it's an issue with the extension.

**Comment by mkey-cdx** [comment]
I can confirm this behaviour with the following setup:
**Phone:** OnePlus 3 running Android 8.0
**Extension version:** 9
**Gnome version:** 3.26.2
Tap to click works using KDE-connect instead of gsconnect on desktop device.
Using gsconnect, I have to double tap on the phone to have the same effect. This makes multitouch or scrolling ineffective.

**Comment by goggle** [comment]
I have the same issue with the following setup:
**Phone:** HTC One X running Android 4.2.2
**Extension version:** 9
**Gnome version:** 3.26.2
As far as I remember, it used to work under kdeconnect directly.

**Comment by andyholmes** [comment]
Hi, I believe this is now fixed in master. I'm planning minor bugfix release of v9 and I'd appreciate if you could test this for me before release:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1777363/gsconnect.andyholmes.github.io.zip)

**Comment by mkey-cdx** [comment]
This is OK in my case. Single tap is now mapped to single click.
Multi-touch and scrolling work fine too. Good job.

**Comment by andyholmes** [comment]
Excellent, thanks for checking :)
