### ISSUE TITLE
[DISCUSSION] Improve UX of "Locate"/Find My Phone" feature

### ISSUE THREAD

**Issue by andyholmes** [andyholmes/gnome-shell-extension-gsconnect#356]
This is a issue to track a discussion started on #205 about the UI for the *Locate* (Find My Phone) UI in the device menu.

> **@Snuggle says:**
>
> As a design-related issue, I was in class a couple days ago and was showing off the awesome that is GSConnect to some of my friends. I tapped on `Locate`, assuming it would come up with a GPS map or a prompt or something*.
> 
> **_Insert my phone blaring an alarm tone at the sound of a billion decibels._**
> 
> Please, for safety reasons, add a confirmation prompt when someone clicks `Locate` on their phone.
> Also, adding a choice of being able to locate using the Google's Find-My-Phone GPS map would also be pretty handy. A link to: [https://www.google.com/android/find](https://www.google.com/android/find)
> 
> -------------
> 
> *(Note: Google uses "Locate" for GPS and calls the ringing function "Ring". This is one of the reasons I didn't expect my phone to suddenly go off in a classroom. Oops.)
> ![image](https://user-images.githubusercontent.com/26250962/48963313-be78a080-ef87-11e8-8b67-78e8262bed36.png)
> ![image](https://user-images.githubusercontent.com/26250962/48963360-89208280-ef88-11e8-8f6c-05947c42b7ef.png)

**Comment by andyholmes** [comment]
Here's two icons that should work, I think the thinner one is better, but it's a bit hard to see maybe:

![screenshot from 2018-11-24 15-20-02](https://user-images.githubusercontent.com/1265208/48973869-82cced80-effe-11e8-943e-090538c2322a.png) ![screenshot from 2018-11-24 15-20-10](https://user-images.githubusercontent.com/1265208/48973870-82cced80-effe-11e8-8af0-a60b89d6f59f.png)

![screenshot from 2018-11-24 15-14-16](https://user-images.githubusercontent.com/1265208/48973872-83658400-effe-11e8-8a35-923393883992.png) ![screenshot from 2018-11-24 15-14-42](https://user-images.githubusercontent.com/1265208/48973871-83658400-effe-11e8-8e64-72db164cdba6.png)

I'll make a branch soon that can be merged after v17 is released, with the icon and *"Locate*" changed to *"Ring"*. I think that's what KDE Connect calls it anyways.

**Comment by Snuggle** [comment]
In my opinion, the icons above look too similar to what one would expect for a phone call, especially because it's directly right of the text-messages/SMS icon.

The "sound-waves" in the icons above are coming out of the earpieces, which wouldn't be very effective for phone location anyway. It would look more obvious if the sound was coming abstractly from the device as a whole, not from any place in particular.

For example, the icon that Google uses has "sound-waves" coming from out of the phone as a whole, emanating from the device itself, as if the entire device is transmitting a signal, an auditory beacon. Not _just out of the earpieces as a phone call._ Unfortunately I don't even think the text would resolve this, as "Ring" could be ambiguous with the icons above.

**Rough sketch of an modified icon that's not as confusing
(Question mark optional, note sound coming from behind the device):**
![screenshot_20181125-050945 2](https://user-images.githubusercontent.com/26250962/48975873-c95c2f80-f072-11e8-8be4-f8a5c1efd7fb.png)

------------

The text might be best as `Locate (Ring)` to make it as clear as possible, and/or I **really believe there should be a confirmation prompt** saying something along the lines of `This will help you locate your device by making it ring at maximum volume. Are you sure?`.

I've already misclicked it once or twice now. It's better to be safe than sorry, as this feature could bring devastation to meeting rooms, classrooms and the like.

**Comment by andyholmes** [comment]
> In my opinion, the icons above look too similar to what one would expect for a phone call, especially because it's directly right of the text-messages/SMS icon.
> 
> The "sound-waves" in the icons above are coming out of the earpieces, which wouldn't be very effective for phone location anyway. It would look more obvious if the sound was coming abstractly from the device as a whole, not from any place in particular.

That's true. It might be hard to find an icon that represent *"Ring"*, but doesn't look like a phone ringing though. Google has the benefit that their icon is (relatively) a lot larger than 16px, though.

For reference, this is what the inverse (16px; GNOME standard) looks like next to Google's (18px) ![bitmap](https://user-images.githubusercontent.com/1265208/48976302-df99c980-f039-11e8-85fd-238400a76704.png) ![baseline_phonelink_ring_black_18dp](https://user-images.githubusercontent.com/1265208/48976353-c5acb680-f03a-11e8-9aeb-5899d51695fc.png)

It's pretty hard to make out, although it might be possible to modify the default Numix icon we use for smartphones and cut a bit out, more like this: <img src="https://visualpharm.com/assets/756/Phonelink%20Ring-595b40b85ba036ed117dc356.svg?sanitize=true" height="16"> (legally required link-back for that icon: https://visualpharm.com/free-icons/phonelink%20ring-595b40b85ba036ed117dc356)

The original icon above I made is based off the Adwaita phone icon, which is something I'd like to keep close to. Materia's design guidelines are fairly different than GNOME, especially for symbolic icons. KDE Connect uses a megaphone icon, but I don't know that's very obvious.

> The text might be best as `Locate (Ring)` to make it as clear as possible

I'd like to keep this as one or the other, since this is an action it should be quite short. *"Ring"* is also what KDE Connect uses in their UI's (desktop, Android, Sailfish, etc) which maintains consistency across platforms.

> I really believe there should be a confirmation prompt

This I'm still not convinced of. It's a strong principle of GNOME not to usurp user interaction, especially with dialogs. If it's too easy to accidentally hit, it might be better just to move it away from more common buttons or remove it from the menu entirely and let it be bound to a shortcut like the other device actions.

**Comment by Snuggle** [comment]
Not at my laptop anymore, so this'll be a terse reply.

I like the Numix icon idea, though, it looks a lot closer to what Google has, and they tend to be pretty good about design. A megaphone might work, too. 🙂

I don't know about a keyboard shortcut, though. If anything that sounds like worst potential for mishaps. Perhaps... A double-click of the icon to ring the phone? First click makes the icon shake a little to get the user to know it hasn't applied yet and second confirmation click could change text to `Ringing...`. I have noticed that GNOME uses a double-click button for laptop suspend.

**Comment by ferdnyc** [comment]
> A megaphone might work, too.

I was going to suggest, in all honesty, a bullhorn. It's a fair representation of the functionality.

In fact, since we're doing symbolic, here are two options from [Flaticon](https://flaticon.com/), both of which are licensable under their [Flaticon Basic License](https://file000.flaticon.com/downloads/license/license.pdf) which basically only requires that the text "designed by {Author's Name} from Flaticon" be placed "in the credits or acknowledgements section" (so, the About window).

ARGH, I keep forgetting GitHub doesn't support .SVG. Well, here are the `24px` .PNG versions, but they also offer SVG:

![megaphone 3](https://user-images.githubusercontent.com/538020/48980872-83b45c80-f09c-11e8-98b1-30d05784eddb.png)  ![megaphone 2](https://user-images.githubusercontent.com/538020/48980873-8616b680-f09c-11e8-8ec3-75db263b2057.png)

(They can also be downloaded in white. In fact, I did that first. ...They were invisible against the comment background. Nice shooting, GitHub.)

Anyway, I have copies of both SVGs in white, with the authors' names (which aren't in the file metadata, annoyingly), if we want to go that route.

**Comment by ferdnyc** [comment]
> I don't know about a keyboard shortcut, though. If anything that sounds like worst potential for mishaps. Perhaps... A double-click of the icon to ring the phone? First click makes the icon shake a little to get the user to know it hasn't applied yet and second confirmation click could change text to `Ringing...`. I have noticed that GNOME uses a double-click button for laptop suspend.

Double-clicks in popup menus are always weird — I'm not sure how easy it is to prevent the panel auto-dismissing once an icon's been clicked, and it doesn't really solve the user menu case.

My suggestion would be that the Find My Phone plugin gain a settings pane of its own, like Sharing, Commands, Notifications, and Telephony. The panel/menu Locate options would only function to bring up that pane in Settings, and the _actual_ locate function could be triggered from **there** by pressing a big, red "destructive-action"-styled button.

And I agree a keyboard shortcut is just a bad idea, period. (Though, I guess if the shortcut just brought up that same settings pane I described, that would be fine.) But how often are users expected to be performing this action, and how quickly do they really need to be able to access it? I would've assumed the answers are "very rarely" and "not at all", respectively.

**Comment by Snuggle** [comment]
If it became a settings pane alone, it would be super cool to add GPS location. I don't know if Google has an API to do so or if this would be possible, otherwise if not, a lazy link to: https://www.google.com/android/find should suffice for functionality purposes.

(I also use locate on GSConnect more than I'd like to admit, I lose my phone within my own room too often.)

**Comment by andyholmes** [comment]
I think a whole settings pane for one function makes much sense. I'd also like to get some more opinions and ideas before making any big changes (especially to a UI that basically hasn't changed in [over a year and two projects](https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/Preferences#device-indicators)).

Later after I get a chance to release v17, I can make the translatable change (*"Locate"* -> *"Ring"*) and I'd like to ask Tobias about the icon, because they have some really cool [ideas](https://gitlab.gnome.org/Teams/Design/app-mockups/raw/master/messages/messages.png) and [mockups](https://gitlab.gnome.org/Teams/Design/app-mockups/raw/master/contacts/contacts.png) for stuff like this already. I also don't really want to trample the icon namespace like I did with `sms-symbolic` and `sms-send` :stuck_out_tongue_closed_eyes: 

> it would be super cool to add GPS location. I don't know if Google has an API to do so...

This would have to implemented in upstream KDE Connect since we don't add device features or extend the protocol without upstream's approval. Keep in mind that KDE Connect runs on Plasma Mobile, Sailfish and Android phones without Google Services (eg. [microG](https://microg.org/)) where Google's device link is not available or appropriate.

Best way to make GPS happen is to get involved upstream; there is a task related to GPS (https://phabricator.kde.org/T4661) and the developers are currently taking part in GCi (Google Code-In). There are a lot of new contributors with no prior experience getting helped through implementing new features right now.

**Comment by andyholmes** [comment]
So I've already pushed the change from *"Locate"* to *"Ring"*, and made the dialog a little more like an OSD (for now at least):

![screenshot from 2018-11-28 14-32-55](https://user-images.githubusercontent.com/1265208/49186827-8623ea00-f31a-11e8-9a48-03c2fa57eab1.png)

Good news is I talked to some designers in #gnome-design and they've offered to design symbolic icons for the phonelink icons (at least the phonelink_ring icon). I'll keep you updated on that; as soon as they decide on a naming scheme we can adjust the icon names we use and use a temporary icon from another icon-set if the designer's aren't finished yet.

I'm not sure what to do about the menu though. Adding long-press buttons would require rewriting the menu code, since those are dynamically generated from GMenu over DBus. That would also make them not work in the settings window, without writing a replacement API for Gtk as well.

There is basic infrastructure for a menu editor it place (ie, adding/removing items), but I've never enabled it or built a UI for it because it would require a fair amount of work to make sure nothing could go wrong.

**Comment by andyholmes** [comment]
Upstream icons are now available, since https://gitlab.gnome.org/Teams/Design/icon-development-kit/issues/4 has been closed by [fe143966](https://gitlab.gnome.org/Teams/Design/icon-development-kit/commit/fe143966dfc8aed14be78384f7809c2876ca27c4).

Once these are merged in the GResource I'll close this issue and we'll deal with the rest in #573 which probably should've been marked as a duplicate (but it's linked now anyways).
