### ISSUE TITLE
The "Panel" display mode doesn't work since the latest update.

### ISSUE THREAD

**Issue by laichiaheng** [andyholmes/gnome-shell-extension-gsconnect#362]
**Describe the bug**
The Panel display mode doesn't work

**To Reproduce**
1. Go to 'Mobile Devices'
2. Click on 'Mobile Settings'
3. Click on 'Display Mode'
4. No indicator

**Expected behavior**
I can see the indicator.

**Screenshots**
![2018-11-27 20-21-34](https://user-images.githubusercontent.com/9532105/49081550-2e39a480-f282-11e8-9119-ffbb0bc9a7cb.png)

**Debug output**
If you have been able to reproduce the problem with debugging enabled (see [instructions in the wiki](wiki/Debugging)), paste any log messages related to this issue between the two ``` lines below.

```
404 This is not the web page you are looking for.
Some code accessed the property 'StatusNotifierWatcher' on the module 'interfaces'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'traverseBusNames' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1052]: unreachable code after return statement
Unable to connect to ibus: 無法連接： 連線被拒絕
Some code accessed the property 'introspectBusObject' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'dbusNodeImplementsInterfaces' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
GNOME Shell started at Tue Nov 27 2018 20:17:14 GMT+0800 (CST)
JS ERROR: Gio.IOErrorEnum: 無法連接主機
_asyncReadyCallback@/home/laichiaheng/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/extension.js:544:27
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22

Some code accessed the property 'WindowPreviewMenu' on the module 'windowPreview'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
```

**System Details (please complete the following information):**
 - GSConnect version: [17]
   - Installed from: [extensions.gnome.org]
 - GNOME/Shell version: [3.30]
 - Distro/Release: [Ubuntu 18.10]

**GSConnect environment (if applicable):**
 - Paired Device(s): [Galaxy A8]
 - KDE Connect app version: [I don't know ]
 - Plugin(s): [I don't know]

**Additional context**
Nothing.

**Comment by sheepdestroyer** [comment]
idem on fedora 29

**Comment by andyholmes** [comment]
Hi, thanks for the report. In your image here you device is not connected to the desktop:

![49081550-2e39a480-f282-11e8-9119-ffbb0bc9a7cb](https://user-images.githubusercontent.com/1265208/49103700-e9395200-f230-11e8-86b1-746a79a9ed28.png)

Could you try hitting the *"Refresh"* button a few times or restarting the service? You may also need to restart gnome-shell after the upgrade. There seem to have been some problems since gnome-shell 3.30 with upgrades.

**Comment by sheepdestroyer** [comment]
Alt + F2 then "r" to reload gnome shell did not suffice.

I restarted the computer and now the indicator is back (I did not try to just logout and back, could have been enough)

**Comment by andyholmes** [comment]
Cool. For reference, the file `daemon.js` (the service) watches "itself" for any changes and quits, then the shell extension restarts it. This is supposed to handle upgrades and uninstalls.

I think what is happening since gnome-shell 3.30 is that the extension is restarting the service before the file `daemon.js` is actually updated. If you have problems like this in the future, it's usually good enough to restart the service from the settings window:

![screenshot from 2018-11-27 18-06-25](https://user-images.githubusercontent.com/1265208/49123899-33412880-f26f-11e8-8a83-8fd3c03dee62.png)

**Comment by laichiaheng** [comment]
It works after I reconnect my phone.
