### ISSUE TITLE
Supress notifications and/or notification dot

### ISSUE THREAD

**Issue by v-marinkov** [andyholmes/gnome-shell-extension-gsconnect#370]
Whenever I am working and would like to remove any notifications (**including** the notification dot in the top panel from [this extension](https://extensions.gnome.org/extension/1480/do-not-disturb/)) I simply close all applications which send notifications.

However, there is no convenient way to fully disable GSconnect. Even if I set "Do not disturb" within GSconnect, I still get the notification dot in GNOME's top panel. This creates a very distracting habit of constantly checking for the notification dot.

I would like a way to stop all notifications from my phone without unpairing or stopping the service. A super silent or "zen" mode if you will.

Thanks!

**Comment by andyholmes** [comment]
Hi, the best way to disable notifications is to simply not send them from your phone. You can also disable the notifications plugin in the *Advanced* page of the [Device settings](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Devices#plugins).

GSConnect doesn't have it's own settings for notifications, so if you'd like further control you can change the settings in GNOME Control Center:

![screenshot from 2018-12-01 12-56-26](https://user-images.githubusercontent.com/1265208/49332805-a517bb80-f568-11e8-9ae2-def2fecdaa8d.png)

**Comment by andyholmes** [comment]
Unfortunately, it's out of the scope of this extension to duplicate GNOME notification settings. Your best bet for a convenient switch in GNOME Shell right now is to use one of the "Do No Disturb" extensions already available.

The "Do Not Disturb" switch itself will probably be removed from GSConnect once [#239 Do Not Disturb For Notifications](https://gitlab.gnome.org/GNOME/gnome-shell/issues/239) is fixed upstream in `gnome-shell`. The current setting is already too broad, since it will it even block fraudulent authentication attempts from being displayed.
