### ISSUE TITLE
Repliable Notifications Steal Input Focus

### ISSUE THREAD

**Issue by Benguin** [andyholmes/gnome-shell-extension-gsconnect#376]
**Describe the bug**
If I'm writing something on my PC, and my phone gets a text, the textbox in the notification is automatically selected and the text I was writing starts being written into that instead. If I was nearing the end of a sentence, and happened to press return, a text would be sent accidentally.

This is quite a bad bug as I could have been writing a password, or sending a personal message to someone, and could inadvertently end up sharing something with the wrong person / leaking details.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open any text editor and begin writing something.
2. While writing is happening, have a text sent to a linked phone.
3. As the notification appears, note that the text you were writing is now being written to the notification
4. Press return.

**Expected behaviour**
The notification is not autoselected & texts can't be sent accidentally.

**System Details (please complete the following information):**
 - GSConnect version: 13
 - Installed from: Arch User Repository
 - GNOME/Shell version: Version 3.30.2
 - Distro/Release: Arch

**GSConnect environment (if applicable):**
 - LG G6
 - KDE Connect app version: 1.10.1

**Additional context**
I use Messenger for my SMS, rather than the default messaging app, not sure if that factors into it or not.

**Comment by andyholmes** [comment]
This is an upstream bug in gnome-shell [#338 Notification popups steal focus sometimes](https://gitlab.gnome.org/GNOME/gnome-shell/issues/338). GSConnect doesn't modify the behaviour of notifications, it merely sends them using the `org.gtk.Notifications` DBus interface.

The most immediate workaround is to disable notifications in the Android app for applications that send repliable notifications.

This is related to and possibly a duplicate of #296

**Comment by andyholmes** [comment]
It didn't occur to me at first, or maybe I'd forgotten, but since this modelled after Android's "Quick Reply" do you think an intermediate button would help?

The notifications could still steal focus, as per the upstream bug, but it would mean you'd have to press *Enter* twice before the message actually sent.

**Comment by ferdnyc** [comment]
> The notifications could still steal focus, as per the upstream bug, but it would mean you'd have to press _Enter_ twice before the message actually sent.

Hmm. I wonder if you would. Is there some way to prevent <kbd>Space</kbd> from also activating the button? That's usually a standard keybinding for keyboard navigation in Gnome apps, unfortunately (in this instance).

**Comment by andyholmes** [comment]
> Hmm. I wonder if you would. Is there some way to prevent <kbd>Space</kbd> from also activating the button? That's usually a standard keybinding for keyboard navigation in Gnome apps, unfortunately (in this instance).

I think that shouldn't be too hard actually. I was already imagining a super-snazzy button-to-entry reveal to wow the blogosphere ;)

Unfortunately my laptop bit the dust a few days back so I'm out of commission for a little while :disappointed:. I've got one on the way, but apparently Canada Post delivers in neither rain, sleet nor snow. Either that or they're on one of their strikes-that-are-not-strikes, because they aren't allowed to strike up here.

**Comment by ferdnyc** [comment]
(I'm laughing at the adoring (if unwashed) blogomasses, not your dead laptop. For the record.)
