### ISSUE TITLE
[Enhancement] Change main panel icon

### ISSUE THREAD

**Issue by varlesh** [andyholmes/gnome-shell-extension-gsconnect#42]
it's only enhancement, if you like:
![2018-02-04 01-52-57](https://user-images.githubusercontent.com/8083855/35771963-dd387c68-094e-11e8-85a3-98ca29eda852.png)
SVG:
```
<!-- Created with Inkscape (http://www.inkscape.org/) -->
<svg width="16" height="16" version="1.1" viewBox="0 0 4.2333332 4.2333333" xmlns="http://www.w3.org/2000/svg">
 <g transform="translate(0,-292.76665)">
  <path transform="matrix(.26458333 0 0 .26458333 0 292.76665)" style="fill:#ececec" d="m8 1c-3.8659932 1e-7 -6.9999999 3.1340068-7 7 1e-7 3.865993 3.1340068 7 7 7 3.865993 0 7-3.134007 7-7v-1h-0.080078-2.025391-3.1660154a1.9999999 1.9999999 0 0 0-1.7285156-1 1.9999999 1.9999999 0 0 0-2 2 1.9999999 1.9999999 0 0 0 2 2 1.9999999 1.9999999 0 0 0 1.7324219-1.0039062l3.1679691-0.0058594c-0.471248 2.3323546-2.520902 4.0094936-4.900391 4.0097656-2.7614238 0-5.0000001-2.238576-5-5-1e-7 -2.7614238 2.2385762-5.0000001 5-5 1.0785093 0.00211 2.127427 0.3528904 2.990234 1h2.751954c-1.308282-1.8788763-3.452696-2.9992232-5.742188-3zm0 3c-2.209139-1e-7 -4.0000001 1.790861-4 4-1e-7 2.209139 1.790861 4 4 4v-1c-1.6568542 0-3-1.3431458-3-3s1.3431458-3 3-3v-1z"/>
 </g>
</svg>
```

**Comment by andyholmes** [comment]
Thanks that's really nice. I'm pretty involved with a rewrite, but I'll have a look back at changing the icon when I'm done.

**Comment by andyholmes** [comment]
I'm still kind of on the fence about this, although it's not really a priority. I think the symbolic panel icon will probably stay the same since it's meant to convey some indication of what it is/does, but I do think it would be nice to have a distinctive application icon. Currently it's just a full-color mockup of the symbolic icon from material.io.

As far as changing/choosing the icon, that will just fall to icon themers providing `org.gnome.Shell.Extensions.GSConnect` and `org.gnome.Shell.Extensions.GSConnect-symbolic` since GSConnect only ships fallback icons to be used when an icon is not present in the theme.

**Comment by andyholmes** [comment]
Going to close this now and just let themers implement custom icons.
