### ISSUE TITLE
'Display mode' label in the hamburger-menu

### ISSUE THREAD

**Issue by amivaleo** [andyholmes/gnome-shell-extension-gsconnect#420]
Hi!

I've just noticed a 'weird' GUI disposition for the 'Display Mode' label in the hamburger-menu.
In the picture below you can see how the 'Sort' label is shown in the nautilus 3.30-4.
[EN] -> [IT]
Sort -> Ordina
Display Mode -> Modalità di visualizzazione
![senzanome](https://user-images.githubusercontent.com/24316547/50558765-23df5000-0cf1-11e9-9ef5-9aba96b8f4d5.png)
In nautilus "Sort" is like an inactive list-item with a separator above.

I better appreciate your approach (although some additional padding would have been nice :P), but maybe it's less 'gnomish' than nautilus's...? :(
I'd prefer to suggest Soriano to change his hamburger-menu indeed, but then I know I wouldn't stop there, since I'd change and merge both popover-menus...

I tried to change yours, but I can't open the menus.ui file using Glade due to some different gtk+ version.

So... Up to you, guys. I wanted to call your attention on this. :)

**Comment by ferdnyc** [comment]
Heh, that's interesting. the problem is partly the *length* of the Italian translation — in the English rendering, "Display Mode" is actually a label on a separator, and the separator lines are (more) clearly visible on either side. But because "Modalità di visualizzazione" is such a long string, it crowds out all of the separator completely and kind of kills the effect:

![screenshot from 2018-12-31 06-00-54](https://user-images.githubusercontent.com/538020/50559179-40b05f00-0cc2-11e9-86d0-6fdd3b43aaf7.png)

I definitely don't love Nautilus' take on menu-section labeling. Personally I'm only kind of so-so on the GSConnect version, too... especially because it's _centered_. Yuck. (And the long-string problem where the separator disappears is another whole issue of its own.)

**Comment by ferdnyc** [comment]
(It's also worth noting that the English version **could** very easily have ended up with the same disappearing-separator problem — the only thing that saves it is how much longer "Generate Support Log" is than any of the other menu strings, because it ends up defining the menu width.)

**Comment by ferdnyc** [comment]
Honestly, I don't feel that changing Nautilus' menu to have a centered-on-a-separator-line "Sort" label would be an improvement there, either. There's plenty of room for improvement (on the Nautilus side), IMHO, but that wouldn't be my first choice for _how_ to improve that menu layout.

...Honestly, labels in menus have remained a poorly-solved problem for most of the past three decades. Not holding my breath that anyone is going to finally come up with a good solution anytime soon.

**Comment by amivaleo** [comment]
"my first choice"
Who said it would be the first thing I'd do? :D
I'd completely redesign both menus to one single compact menu. Just to give an idea, something like:
![popup](https://user-images.githubusercontent.com/24316547/50559753-7a04c100-0cfa-11e9-9cc0-f1536d621656.png)
But... yeah, " Not holding my breath that anyone is going to finally come up with a good solution anytime soon". I think the same.

**Comment by andyholmes** [comment]
> I tried to change yours, but I can't open the menus.ui file using Glade due to some different gtk+ version.

This isn't actually a Glade file, it's a [GMenu XML model](https://developer.gnome.org/GMenu/). All of the items in menu, padding, separators, etc are actually all drawn by Gtk automatically. Unfortunately there's not much I can do about how the separator is rendered, since that's probably defined by your theme in CSS.

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/750885e23e9f8c569962f2afd9e279f84e2652f7/data/menus.ui#L3-L42

You *could* submit a pull request for a changed menu, but it would require building the popover from scratch and probably hooking up all the GActions manually. It would allow you to define the padding and separator rendering though.

**Comment by amivaleo** [comment]
I use Adwaita. :3
Anyway, I think this issue can be closed. It's not a proper issue indeed. I wanted you to notice that.
This is something that has to be chosen from the 'bosses' in order to standardize the UI design.

Andy but... You don't like holidays, don't you? :D
It's ~10:40 pm here. Less than 2 hours before the year ends...
Go and have fun! :D

**Comment by andyholmes** [comment]
:laughing: this is fun!
