### ISSUE TITLE
may be use freenode ?

### ISSUE THREAD

**Issue by solsticedhiver** [andyholmes/gnome-shell-extension-gsconnect#435]
So this is more athing about a personnal preference matter, but irc.gimpnet.org does not allow me to connect because I use a VPN. nothing fancy, it's just PrivateInternetAccess.

I would have like to use IRc and freenode allow VPN (at least PIA). also freenode is kind of best known for open source project.

so if if you don't bother to change... thanks

**Comment by andyholmes** [comment]
I use irc.gimpnet.org because it's where most discussion for GNOME projects happens. You should be able to use matrix, or PIA should work with gimpnet, it probably just needs configuration. One of the GNOME developers mcatanzaro uses PIA with gimpnet, so I know it's possible.

Not much discussion happens on this channel anyways, so I wouldn't worry about it. If you have bug, it should probably be opened here so it can be tracked.
