### ISSUE TITLE
Add photo button in menu

### ISSUE THREAD

**Issue by remcohaszing** [andyholmes/gnome-shell-extension-gsconnect#494]
**Is your feature request related to a problem? Please describe.**

The new photo plugin is awesome, great job! However, it can’t be accessed unless a shortcut is configured.

**Describe the solution you'd like**

I think there should be a button for it in the panel, alongside the other buttons.

**System Details (please complete the following information):**
 - GSConnect version: 21
   - Installed from: extensions.gnome.org

**Additional context**

The button would go in this menu:

![image](https://user-images.githubusercontent.com/779047/54698026-e390b080-4b2e-11e9-86c9-7e843e3c3248.png)

**Comment by MatthewGitter** [comment]
GSConnect would be even better if it automatically exposed a GUI to execute each and any plugin, rather than explicit code per plugin for a GSConnect UI. It seems the keyboard shortcut config already does this, or else if not then a single code path for explicit code supporting the keyboard shortcut could also support a less-buried plugin execution UI.

**Comment by andyholmes** [comment]
Patches are welcome, but you might find it's a bit more complicated than just adding all the actions to the menu. Some are conditional, like mount/unmount and mute call, other are rarely used like pair/unpair and reconnect.

I have a branch somewhere for a menu editor, but it needs a fair amount of work before it's usable and accounts for all the corner cases.
