### ISSUE TITLE
Android Device paired but no functionality

### ISSUE THREAD

**Issue by akshatmahla** [andyholmes/gnome-shell-extension-gsconnect#499]
Pairing devices was successful but no functionality nor the device is listed in drop down menu.
I am running it on Arch Linux, Gnome 3.32

![Screenshot from 2019-03-23 01-03-03](https://user-images.githubusercontent.com/26081087/54849156-71c08e80-4d09-11e9-8424-28982cdab1d6.png)

**Comment by andyholmes** [comment]
Can you please list your KDE Connect Android and GSConnect versions.

**Comment by akshatmahla** [comment]
> Can you please list your KDE Connect Android and GSConnect versions.

Android - 1.12-nosms
GSConnect - 21

**Comment by andyholmes** [comment]
> Android - 1.12-nosms

I believe this version of the Android app had several problems caused by Proguard stripping necessary classes during the build process. v1.12.5 is now on [Google Play](https://play.google.com/store/apps/details?id=org.kde.kdeconnect_tp) and should fix the missing functionality.

Give it a try and let me know if it's still a problem.

**Comment by akshatmahla** [comment]
Updating Android version and restarting PC fixed the issue.Thanks.
