### ISSUE TITLE
Clipboard is set to "null" when I screenshot to clipboard

### ISSUE THREAD

**Issue by Kjwon15** [andyholmes/gnome-shell-extension-gsconnect#500]
**Describe the bug**

When screen capture to clipboard, Phone's clipboard set to "null" (as string)
Additionally, If use another program to sync clipboard, PC's clipboard also set to "null"

**To Reproduce**

1. Set clipboard sharing option as "To device"
2. Capture screen to clipboard (<kbd>Ctrl+PrtScr</kbd>)
3. See Phone's clipboard is "null" by pasting it somewhere
4. (Additional) With another clipboard sync app (I use join by joaoapps), PC's clipboard also set to "null"

**Expected behavior**

Don't set clipboard as "null" when clipboard content is not text.

**System Details (please complete the following information):**
 - GSConnect version: 21
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30.2
 - Distro/Release: Ubuntu 18.10

**GSConnect environment (if applicable):**
 - Paired Device(s): Pixel 2 XL, Pixel 2, Nexus 6P
 - KDE Connect app version: 1.12

**Comment by andyholmes** [comment]
Thanks for reporting. This should be fixed now. Since there's no way to really clear the remote clipboard, if `null` or non-text content is in the local clipboard nothing will be sent instead. I think this is the best solution.

Here's an up to date Zip you can install with the [instructions in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip), or you can build from git:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2999049/gsconnect%40andyholmes.github.io.zip)
