### ISSUE TITLE
GSConnect stop working after update

### ISSUE THREAD

**Issue by PrzemekSkw** [andyholmes/gnome-shell-extension-gsconnect#501]
**Describe the bug**
Last week I've updated some gnome extensions and I think there was also gsconnect. Today when I want to upload photos from android smartphone I have error. When I open gsconnect settings I see that my phone is connected and when I choose pictures on phone gallery I also see my laptop. When I chose pictures and click share I see only notification that upload failed.

**System Details (please complete the following information):**
 - GSConnect version: 21
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30.2
 - Distro/Release: Ubuntu 18.10; Kernel 4.19.10-041910-generic

**GSConnect environment (if applicable):**
 - Paired Device(s): LG G4
 - KDE Connect app version: 1.12.6
 - Plugin(s): ---

**Additional context**
Chrome browser extension don't see paired phone.

Regards,
Przemek

**Comment by ferdnyc** [comment]
@PrzemekSkw 
I just tested with v21 and KDE Connect 1.12.6, and sending photos from the Google Photos app to my Linux desktop still works fine.

Is the "Share" plugin enabled for your phone in the GSConnect settings, as well as the "Share and receive" plugin for your computer in the KDE Connect settings? (I _believe_ those are the ones involved in file exchange, as well as link-sharing from the Chrome extension...)

**Comment by PrzemekSkw** [comment]
@ferdnyc strange, now it works and I don't know what I've done. I only open settings uncheck and check sftp plugin.

**Comment by ferdnyc** [comment]
Weird, well sometimes these things happen. Glad it's working for you again!

**Comment by nplezka** [comment]
Hi @ferdnyc @andyholmes , I want to re-open this issue because I have the same exact problem since I updated GSConnect but unchecking and checking again SFTP plugin does nothing for me.
In my case the only difference is that the Google Chrome extension works without problems.
Anyway, If I browse phone files mounting file system from PC, I can copy, cut and paste whatever I want.
Only sending from phone (from KDE Connect or via the share menu) doesn't work.

**My system details:**
- GSConnect version: 21
     updated from github, from v19 to v21. 
     Then totally removed (~/.local/share/gnome-shell/extensions & ~/.config/gsconnect. and re-installed 
     from: extensions.gnome.org
- GNOME/Shell version: 3.28.2
- Distro/Release: Ubuntu 18.04; Kernel 4.15.0-46-generic

**GSConnect environment (if applicable):**
- Paired Device: OnePlus 5T
- KDE Connect app version: 1.12.6
- Plugin(s): ---

I tried reinstalling KDE Connect for Android and GSConnect, checking and unchecking settings and plugins.
I don't know what to do 🤔

**Comment by andyholmes** [comment]
> Only sending from phone (from KDE Connect or via the share menu) doesn't work.

You should try to gather and error log using the [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) feature.

1. Select *Generate Support Log*
2. Once the dialog opens, send a file from your phone
3. Once it completes/fails, close the dialog
4. Review the log that's shown and upload/paste it here

**Comment by nplezka** [comment]
@andyholmes Sorry for the delay, here I am with support logs:
[sendfilefromkdeconnect.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3026961/sendfilefromkdeconnect.txt)
[sendfromsharemenu.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3026962/sendfromsharemenu.txt) 😊

**Comment by andyholmes** [comment]
Hi, it doesn't seem like any sharing or actions were performed during the time the support log dialog was open. You must

1. Open the dialog by selecting *Generate Support Log*
2. Leave the dialog open while performing actions
3. Close the dialog only after the action has completed/failed

**Comment by nplezka** [comment]
That's really strange because I did exactly what you told me and I want to specify that the phone was connected. Anyway I tried another time and now I see an error in log like "unable to open the file x because it doesn't exist", while it exists.:
[sendfromkdeconnect2.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3029223/sendfromkdeconnect2.txt)
[sendfromsharemenu2.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3029224/sendfromsharemenu2.txt)

**Comment by nplezka** [comment]
Wait, I have a flash: it's possible that in the last versions GSConnect can't understand where is my download folder?
I'll explain: When I installed Ubuntu I moved my personal folders to the hard disk, while I only have the Home partition in my primary drive, an SSD.
I saw that the Downloads path in the log is the default one that creates Ubuntu, not the real one in my HDD, that is in "/mnt/*harddiskcode*/Scaricati". I don't understand, the download folder is just the same as always and it worked like a charm before, in GSConnect v19.
