### ISSUE TITLE
Disable Firefox context menu entry

### ISSUE THREAD

**Issue by fbruetting** [andyholmes/gnome-shell-extension-gsconnect#502]
**Describe the bug**
Can you please delete GSC from my Firefox context menu? I don’t want every one of my extensions to spam my menus and I don’t know how I can deactivate that. Please provide a setting for this instead, so everyone can use this if it would be useful, but the default should be to be lean and not obtrusive.

**Comment by ferdnyc** [comment]
@fbruetting 

I'll mark this as an enhancement for the moment, since I suppose it's _possible_ to make the context-menu insertions optional — we'll have to see how @andyholmes feels about that, since currently the extension has no configurables, keeping it "lean" from a different perspective.

I do have to ask, though: If you don't want the extension to provide context-menu options to send URLs to your paired device (which also works for links on the page, so you can send a link to the target page _without_ having to load it first)... what **do** you use it for?

(As I said, I'm marking this as an enhancement anyway — that's not contingent on your answer. I'm just trying to understand the desired operating mode of the extension. How would you prefer to be able to use it, if it could be configured the way you want?)

**Comment by fbruetting** [comment]
The option already exists where it belongs – in the ton menu of the address bar, next to “copy address”, “send via email”, “send to pocket”, et cetera. I don’t understand why one needs a second option and it’s not that I send tabs to devices all day long. So why dosn’t the address bar icon suffice?
