### ISSUE TITLE
Unable to purge key after removing.

### ISSUE THREAD

**Issue by alexfornuto** [andyholmes/gnome-shell-extension-gsconnect#505]
**Describe the bug**
Even after completely removing the plugin as described [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings) I still have a privkey listed when I run `ssh-add -L`:

```
$ ssh-add -L
ssh-rsa AAAA... /home/USER/.config/gsconnect/private.pem
$ rm ~/.config/gsconnect/private.pem
rm: cannot remove '/home/USER/.config/gsconnect/private.pem': No such file or directory

```

**To Reproduce**
1. Install and connect a device.
2. Remove the plugin
3. Note the reference to the now-removed private key.

**Expected behavior**
References to this key purged.

```

```

**System Details (please complete the following information):**
 - GSConnect version: Latest provided by [extensions.gnome.org](https://extensions.gnome.org/extension/1319/gsconnect/)
 - GNOME/Shell version: 3.30.2
 - Distro/Release: Fedora 29

**Comment by ferdnyc** [comment]
I mean... the thing is, without an "uninstall" process there's no way for GSConnect to _know_ that it's being removed, in order to purge the key. As you observed the corresponding key file has been deleted, so that identity is relatively harmless and will only last until the next restart of the SSH agent (most likely next logout/login cycle). But if it's going to be "purged" that would need to be done by the user.

So, I suppose there are two changes I could think of to address this:

1. `ssh-add` could be passed `-t` <var>`lifetime`</var> arguments when adding the key, to give it an expiration time instead of making it immortal for the lifetime of the agent process. Even this wouldn't _really_ address your concern since immediately after removal the identity would still be there, but it's something we're currently not doing.
2. I suppose we could add `ssh-add -d ~/.config/gsconnect/private.pem` to the removal steps in the Wiki, before the deletion of `~/.config/gsconnect`. I don't love the idea of making that process even longer, but it would eliminate the lingering identity.

**Comment by andyholmes** [comment]
I'm not this is fixable for us, but I'm also not sure where the problem lies exactly. I suspect the reason `ssh-add -d` won't work is because `gnome-keyring` has taken over as the SSH agent.

I believe the removal of a key using the private key fails, even if the key exists, because it expects a public key. This is my guess because this was an *old* bug in openssh that was fixed ages ago, by having openssh extract the public key if necessary.

But as @ferdnyc says, this shouldn't cause any problems or security concerns. I would tend to mark this an upstream issue in gnome-keyring...

**Comment by alexfornuto** [comment]
I'm actually not using the gnome-keyring, I'm using a custom gpg agent to authenticate SSH sessions with a smart key... I see know that that would have been useful information.

**Comment by alexfornuto** [comment]
So I removed the key as described [here](https://lists.gnupg.org/pipermail/gnupg-users/2016-August/056499.html) - sound very much like this issue doesn't merit any further thought, and I apologize for the thought you already put into it.

**Comment by andyholmes** [comment]
Thanks for the link. Maybe it's worth shipping a shell script to wipe all this stuff at some point.
