### ISSUE TITLE
Provide method to change display order of paired devices

### ISSUE THREAD

**Issue by pwd-github** [andyholmes/gnome-shell-extension-gsconnect#511]
**Is your feature request related to a problem? Please describe.**
Sometimes users have multiple devices connected and may want the primary device to be displayed first, however currently such an option doesn't exist, meaning that users are stuck with whatever order devices are added in.

**Describe the solution you'd like**
Provide a simple up and down button in the pairing screen.

**Describe alternatives you've considered**
Providing a drag and drop ability to change device order

**System Details (please complete the following information):**
 - GSConnect version: 21
   - Installed from: extensions.gnome.org

**Additional context**

**Comment by andyholmes** [comment]
This is probably possible, but requires a lot of work in a lot of different places.

It's really coincidence that devices are listed in the shell in the order they're paired, since they're added in the order that DBusObjectManager lists them, which is probably non-deterministic.

Implementing drag-and-drop in a listbox is not terribly complicated, however the sorting in every place devices appear (Preferences, Shell, Nautilus, Web Browser) are all pretty arbitrary.

**Comment by andyholmes** [comment]
Going to close this for now as it's not really doable given the current architecture.
