### ISSUE TITLE
Selecting Message notification doesn't switch to message in notification

### ISSUE THREAD

**Issue by rexbron** [andyholmes/gnome-shell-extension-gsconnect#512]
Using F30 Beta and GSConnect V21 

Clicking on text notificiation pop up opens the message window but doesn't change the thread displayed.

**Comment by andyholmes** [comment]
As explained on #gsconnect, this is not possible to do reliably because notifications come with an icon, a title and a body. The title would be what we used to find the conversation, however that could be:

* contact name
* 2fa name
* e-mail address
* phone number

Without a reliable way to tell which it is, we can't find which conversation to select. Finding the conversation by `body` could be mean iterating every message of every conversation, and that assumes we've received the `kdeconnect.sms.messages` packet before the `kdeconnect.notification` packet.

I'm going close this as `can't fix` since I don't believe this is possible to solve reliably without extra information in the `kdeconnect.notification` packet.
