### ISSUE TITLE
Possible to trigger refresh from script?

### ISSUE THREAD

**Issue by bryango** [andyholmes/gnome-shell-extension-gsconnect#514]
Sometimes GSConnect won't automatically detect my phone, but it usually works when I manually click the top left refresh button ↻ in the settings view. 

I wonder if this refresh action can be achieved from a script (`gjs` or DBus command) so I won't have to navigate to the GUI button (it gets frustrating after a couple of times); I can simply run this refresh command from script when the network changes...

&emsp;![image](https://user-images.githubusercontent.com/26322692/55707587-85ad0580-5a16-11e9-91fa-1c9899cc13ff.png)

Thank you all!

**Comment by andyholmes** [comment]
GSConnect sends a directed broadcast asking for a connection every 5s to the last known IP of each disconnected device, so as long as your device doesn't change IPs this should happen automatically.

You can call the *Refresh* action (a network wide broadcast) from the command-line using:

    gapplication action org.gnome.Shell.Extensions.GSConnect broadcast

Although these actions should generally be considered a "private" API as they may change without warning in future.

**Comment by bryango** [comment]
Ah! That's very nice! Thank you so much! My device's IP does change frequently as I constantly switch between home network & mobile hotspot. I think that's why it is not automatically detected. 

BTW,  I've been studying the code, 

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/6c8ab5d8f5611b4959e705a73914225c2d1dbc26/src/service/daemon.js#L175-L185

I believe this is the source of the DBus refresh action, therefore this `daemon.js` can be of future reference in case of API change, is that right? :stuck_out_tongue_winking_eye: Thanks!

**Comment by andyholmes** [comment]
Probably they won't change, but I make no guarantees since they're not generally intended to be called externally. That's the function definition, but the action names are here:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/6c8ab5d8f5611b4959e705a73914225c2d1dbc26/src/service/daemon.js#L300-L311

A general broadcast every 5s instead of a direct-to-IP broadcast might be a better solution for everyone. The only reason it's not that way already is that when a device receives a broadcast, it responds by opening a connection to the device that sent it.

If it's already connected, it opens the new connection anyways and try to "hotswap" the socket in without registering a disconnection. Sometimes that doesn't work and even when it does I'm not sure what would happen to ongoing file transfers, etc.

Going to close this for now since I think I solved your immediate problem ;)

**Comment by bryango** [comment]
Yeah, that's very helpful! Thank you very much!

**Comment by mint1goose** [comment]
Right now, I am not able to call the function to refresh externally (was mentioned previously that function is meant to be private)
```
user@box:~$ gapplication action org.gnome.Shell.Extensions.GSConnect broadcast
error sending ActivateAction message to application: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Unknown action ‘broadcast’
user@box:~$ sudo gapplication action org.gnome.Shell.Extensions.GSConnect broadcast
unable to connect to D-Bus: Failed to execute child process “dbus-launch” (No such file or directory)
```
Is it possible to reopen the issue or link to similar issue? I change IPs daily and having a general broadcast or external command would help a lot instead of having to access the GUI.

**Comment by ferdnyc** [comment]
@mint1goose It looks like the action is called "refresh" rather than "broadcast" now, so this should work:

```bash
gapplication action org.gnome.Shell.Extensions.GSConnect refresh
```

(Untested, but based on...)

<img width="802" height="820" alt="Image" src="https://github.com/user-attachments/assets/9aacf809-fb18-4567-a127-776a63253779" />

(**Edit:** Also, you should definitely not use `sudo`, since every part of GSConnect is running under your userID. If you can't do it as you, you can't do it period.)
