### ISSUE TITLE
GLib.FileError at installation/setup

### ISSUE THREAD

**Issue by b4adam** [andyholmes/gnome-shell-extension-gsconnect#527]
Hi!
I am using Ubuntu 19.04 with Gnome Classic. I could successfully install the Gnome Shell Extension. At installation of GSconnect I am receiving the following error:
The settings of extension gsconnect@andyholmes.github.io had an error:

```
GLib.FileError: Nem sikerült létrehozni a(z) „/home/adam/.config/chromium/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json.I5650Z” fájlt: Engedély megtagadva
```

Stack trace:
```
gsconnect.installService@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:220:13
init@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:20:5
_getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:60:9
_selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:74:31
_onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
@<main>:1:43
```
Thanks, Adam

**Comment by ferdnyc** [comment]
@b4adam 

Assuming Google Translate didn't steer me wrong, that error message comes out as...
```
GLib.FileError: Could not create file
"/home/adam/.config/chromium/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json.I5650Z":
Permission denied
```

Can you check whether your user account has write permission on this directory?
`/home/adam/.config/chromium/NativeMessagingHosts/`

And if there's an existing file
`/home/adam/.config/chromium/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
are the permissions set so that your account would be able to modify it?

```bash
# to see the directory permissions
ls -ld /home/adam/.config/chromium/NativeMessagingHosts 

# to see the permissions of any files it contains
ls -l /home/adam/.config/chromium/NativeMessagingHosts/
```

The temporary filename (`....gsconnect.json.I5650Z`) makes me think GSConnect is attempting to move or replace an existing file, and is being prevented from doing that by the permissions on either the file or the directory it's in.

If you've ever run `chromium` as the root user, but under your account (using `sudo`, for example), then it's possible that directory is owned by `root`, in which case GSConnect running under your user account wouldn't be able to write there. (That's just one example of how these permissions errors can happen, the actual cause could be something else entirely.)

Find whatever permissions issue is blocking GSConnect from writing, and that should solve this.

**Comment by b4adam** [comment]
Dear Frank,

Yes, I have checked, the permissions for the directory 
||"/home/adam/.mozilla/" ||are rwx for the user account adam.||
||

||As You wright, I had to change the owner "root" for the subdirectory 
"/home/adam/.mozilla/native-messaging-hosts" to "adam".
||

||For Firefox it seems to work now, for chromium there is a further 
error report:

||

|Translated to English this means: "An error occured. Tha package is 
invalid. Details: " Message file is missing for 
locale.|||/tmp/scoped_dirlStKvv/CRX_INSTALL/_locales/ja/messages.json".

Thanks anyway for your help.

Regards, ??d??m
||||

||||

||

03.05.19 14:46 keltez??ssel, Frank Dana ??rta:

**Comment by ferdnyc** [comment]
@b4adam Looks like that's #528 which was a packaging error on our end. @andyholmes has released an update to correct the problem, which should be available shortly.

Closing in favor of #528, the Chrome extension locale issue can be tracked there.
