### ISSUE TITLE
Transferred files location

### ISSUE THREAD

**Issue by jrens** [andyholmes/gnome-shell-extension-gsconnect#536]
At the moment the transferred files location is set to the users Downloads directory.
```
    // Downloads link; Account for some corner cases with a fallback
    let download_dir = GLib.get_user_special_dir(
            GLib.UserDirectory.DIRECTORY_DOWNLOAD
            );

    if (!download_dir || download_dir === GLib.get_home_dir()) {
        download_dir = GLib.build_filenamev([GLib.get_home_dir(), 'Downloads']);
    }
```

It would be useful to be able to specify another directory, either on a per device basis (files from different devices go to different folders) or generally so that files from devices can be isolated from other generic downloads.

**Comment by naymat** [comment]
I agree, it would be a nice addition

**Comment by HerrBulles** [comment]
I also  agree, that it would be a nice addition. I am looking to find a way for automated folder sync between Android and Linux PC , without the need to select manually the files for sending to PC

**Comment by billtown** [comment]
I could really use this also.  I apparently just tip toed through Glib User Directory Constants and don't want to  change this global setting, just want it changed for gsconnect only.  I don't get how this is supposed to be implemented, because I don't ultimately understand how GLib.UserDirectory.DIRECTORY_DOWNLOAD ultimately maps to XDG_DOWNLOAD_DIR in .config/user-dirs.dirs (which I think is where this is ultimately looked up?).  It's obfuscated enough that it sure would be helpful to be able to either have a settings file (I first looked in .config/gsconnect/ for one), or configure the downloads directory in a sane way for gsconnect, if all the underlying defaults want to be kept.  No clue, just know it's a pita (for ignorant me) and I just gave up.  Downloads is a mess for me personally, and I want to send files off my phone to a clean specific place to ingest/sync them.

I don't know the "correct" way to override GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_DOWNLOAD)
or I'd offer a pr :/

**Comment by ferdnyc** [comment]
> I also agree, that it would be a nice addition. I am looking to find a way for automated folder sync between Android and Linux PC , without the need to select manually the files for sending to PC

I still maintain that the cloud is the best solution to that problem. 

I run the Dropbox sync client on my Linux box, and the third-party [Dropsync app](https://play.google.com/store/apps/details?id=com.ttxapps.dropsync) on my phone, which keeps a selected folder from my Dropbox account automatically synced to my phone — and at _all_ times, not only when I'm connected to my home network.
