### ISSUE TITLE
Getting a notification for a download that ended a week ago

### ISSUE THREAD

**Issue by JMS55** [andyholmes/gnome-shell-extension-gsconnect#554]
**Describe the bug**

A notification randomly pops up for a download I did a week ago

**Steps To Reproduce:**
No idea

**Support Log**
warning: big https://pastebin.com/raw/bGHxuTht

**System Details (please complete the following information):**

 - **GSConnect version:* 21
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.32.2
 - **Distro/Release:** Fedora 30

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Moto X4
 - **KDE Connect app version:** 1.12

**Comment by andyholmes** [comment]
Thanks for reporting. So there does seem to be something fishy happening in Android. Below is a good example:

```js
[/service/protocol/core.js:receive/<:177]: JPhone: {
  "id": 1559958349847,
  "type": "kdeconnect.notification",
  "body": {
    "id": "0|com.android.providers.downloads|0|3:329|10046",
    "isCancel": true
  }
}
[/service/protocol/core.js:receive/<:177]: JPhone: {
  "id": 1559958349835,
  "type": "kdeconnect.notification",
  "body": {
    "payloadHash": "6ee56e9b15b96635aa71ac44eca54e58",
    "id": "0|com.android.providers.downloads|0|3:329|10046",
    "isClearable": true,
    "appName": "Download Manager",
    "time": "1559958349605",
    "ticker": "New Doc 2019-05-29 18.41.35.pdf: Download complete.",
    "title": "New Doc 2019-05-29 18.41.35.pdf",
    "text": "Download complete."
  },
  "payloadSize": 359,
  "payloadTransferInfo": {
    "port": 1761
  }
}
[/service/protocol/core.js:receive/<:177]: JPhone: {
  "id": 1559958360487,
  "type": "kdeconnect.notification",
  "body": {
    "id": "0|com.android.providers.downloads|0|3:330|10046",
    "isCancel": true
  }
}
[/service/protocol/core.js:receive/<:177]: JPhone: {
  "id": 1559958360466,
  "type": "kdeconnect.notification",
  "body": {
    "payloadHash": "6ee56e9b15b96635aa71ac44eca54e58",
    "id": "0|com.android.providers.downloads|0|3:330|10046",
    "isClearable": true,
    "appName": "Download Manager",
    "time": "1559958360345",
    "ticker": "New Doc 2019-05-29 18.41.35.pdf: Download complete.",
    "title": "New Doc 2019-05-29 18.41.35.pdf",
    "text": "Download complete."
  },
  "payloadSize": 359,
  "payloadTransferInfo": {
    "port": 1762
  }
}
```
First we're receiving notice that a notification (id: `0|com.android.providers.downloads|0|3:329|10046`) is being cancelled (at timestamp `1559958349847`), then receiving notice that notification is being shown (at timestamp `1559958349835`). We should obviously be getting those in the reverse order.

Regardless, this second exchange (with the same reversed order behaviour) shows that the same download notification was posted again although the notification id has changed from `0|com.android.providers.downloads|0|3:329|10046` to `0|com.android.providers.downloads|0|3:330|10046`.

The first problem just shouldn't be possible, since KDE Connect packets are pushed into a socket and read on the other side in the same order. The second problem makes it seem like there's something funky going on with the Android Download manager. Possibly this is causing the posted/cancelled events being out of order.

Could you try clearing the cache/data in the Android Downloads manager and see if that helps?

**Comment by JMS55** [comment]
Updated kde connect to 1.12.7, and cleared android download cache. I'll update if it happens again

**Comment by JMS55** [comment]
I didn't have the log running, but it occurred again.

**Comment by andyholmes** [comment]
Seems like based on the above logs, something is going wrong in the downloads manager and kdeconnect-android. The downloads manager shouldn't be posting old notifications, but what makes it harder to deal with is kdeconnect sending the packets out of order.

The latter I'll try and bring up with nico upstream. The misordered timestamps on those packets indicate that kdeconnect is preparing them in the proper order, but somehow they're being sent out of order. This has also been known to happen with keyboard echo packets (#333), but there isn't much we can do in GSConnect since we never know if such a packet is coming or not.

**Comment by andyholmes** [comment]
Closing now since I think this is upstream Android issue, I'm not sure can be fixed in GSConnect or KDE Connect. If it keeps happening, I'd recommend just opening a bug in kdeconnect-android so at least it can be tracked there.
