### ISSUE TITLE
CPU 100% with error - too many files open

### ISSUE THREAD

**Issue by alexgarel** [andyholmes/gnome-shell-extension-gsconnect#558]
**Describe the bug**

Once, twice or three times a day times, gcj begin to take 100% of CPU.
It may happen while I'm away from the computer.

#330 already talk about this but I prefer to open a new ticket as the old one was marked resolved and is already very long, with different use case.

**Support Log**

Some excerpts from the syslog

Sorry there is some french in it:

*  "Trop de fichiers ouverts" means "Too many open files"
* " Erreur d’acceptation de la connexion" means "Error while accepting connection"

```
Jun 14 10:29:34 tignasse gjs[8742]: unable to create file '/run/user/1001/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.
Jun 14 10:29:34 tignasse gjs[8742]: message repeated 7 times: [ unable to create file '/run/user/1001/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.]
Jun 14 10:29:34 tignasse gjs[8742]: g_file_enumerator_iterate: assertion 'direnum != NULL' failed
Jun 14 10:29:34 tignasse gjs[8742]: unable to create file '/run/user/1001/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.
Jun 14 10:29:34 tignasse gjs[8742]: message repeated 3 times: [ unable to create file '/run/user/1001/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.]
01/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.]
Jun 14 10:29:34 tignasse gjs[8742]: JS ERROR: Gio.IOErrorEnum: Impossible de créer le connecteur : Trop de fichiers ouverts#012_onIdentity/connection</<@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:279:33#012@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
Jun 14 10:29:34 tignasse gjs[8742]: unable to create file '/run/user/1001/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.
Jun 14 10:29:34 tignasse gjs[8742]: message repeated 7 times: [ unable to create file '/run/user/1001/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.]
....
Jun 14 21:54:18 tignasse gjs[8742]: fail: Erreur d’acceptation de la connexion : Trop de fichiers ouverts
Jun 14 21:54:18 tignasse gjs[8742]: unable to create file '/run/user/1001/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.
Jun 14 21:54:18 tignasse gjs[8742]: message repeated 7 times: [ unable to create file '/run/user/1001/dconf/user': Trop de fichiers ouverts.  dconf will not work properly.]
Jun 14 21:54:18 tignasse gjs[8742]: fail: Erreur d’acceptation de la connexion : Trop de fichiers ouverts
Jun 14 21:54:18 tignasse gjs[8742]: JS ERROR: Gio.IOErrorEnum: Impossible de créer le connecteur : Trop de fichiers ouverts#012_onIdentity/connection</<@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:279:33#012@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
Jun 14 21:54:18 tignasse gjs[8742]: fail: Erreur d’acceptation de la connexion : Trop de fichiers ouverts
Jun 14 21:54:29 tignasse gjs[8742]: message repeated 350164 times: [ fail: Erreur d’acceptation de la connexion : Trop de fichiers ouverts]

```

As you see from the last line the amount of repetitions of the message in ten seconds is tremendous !
And it goes one whole night like this :-(

**System Details (please complete the following information):**

 - **GSConnect version:** 24
   - **Installed from:**  GNOME Extensions Website
 - **GNOME/Shell version:** 3.32.0-1
 - **Distro/Release:** Ubuntu 19.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Samsung Galaxy Core (SM-G350)
- **KDE Connect app version:** 1.3.4-0ubuntu1

**Comment by andyholmes** [comment]
> KDE Connect app version: 1.3.4-0ubuntu1

Are you running KDE Connect on your desktop? This seems like a desktop version number.

**Comment by alexgarel** [comment]
>> KDE Connect app version: 1.3.4-0ubuntu1

>Are you running KDE Connect on your desktop? This seems like a desktop version number.

Sorry, I did an `apt show`  without verifying if it was installed (the template asked for it) ! It's not installed…

**Comment by andyholmes** [comment]
Is there anything special you can think of that you're doing? Running lots of remote commands that don't exit cleanly maybe?

It's pretty hard to hit the file descriptor limit on Linux, so something weird must be happening here. Unfortunately there's not much in the log indicating why this is happening.

**Comment by alexgarel** [comment]
My phone is old enough, and I always pass from wifi to wifi (3 hotspot in my home), also my router is not very healthy so most of the times it does not relay from wifi (where my phone is) to wire (where my computer is).

Apart from than I can't tell.
Is there any log I can activate ? (I'm ok to modify source code directly if you point me to some line I should modify).

**Comment by alexgarel** [comment]
@andyholmes ?

**Comment by andyholmes** [comment]
Generating logs is described in the Wiki under ["Generate Support Log"](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log).

**Comment by ferdnyc** [comment]
This... is a truly astonishing log message: 

> message repeated 350164 times

Even more so when you consider the fact that, based on the context, this occurred in the space of no more than 11 seconds! 😮

I don't even know whether to be impressed or frightened.

Anyway... it's been a bit more than a month since the last activity here, any updates on this issue @alexgarel? Is it still occurring? Were you ever able to capture any logs from GSConnect using the wiki information provided above?

**Comment by alexgarel** [comment]
Hi @ferdnyc, sorry because I didn't update on it.

Capturing the log was not evident, because you first have to set it up before the problèms happens, and the only time it happens, I got the same log as in syslog (nothing more). But maybe I did something wrong ?

The problem is that lastly, it stops happening but my phone is also not reachable ! (I am about to change my phone, because it's old and has become very slow, with no space left in memory).

**Comment by ferdnyc** [comment]
> Capturing the log was not evident, because you first have to set it up before the problèms happens, 

Yeah, that is one challenge; the logging-capture features are much more helpful for documenting errors that can be reproduced on demand, less so for systemic or unpredictable issues like the one you're seeing.

> and the only time it happens, I got the same log as in syslog (nothing more). But maybe I did something wrong ?

Possibly, but I don't think so. I suspect that it just means there's nothing more to capture (nothing out of the ordinary going on with GSConnect). The hope would be that, when this happens, some message logged by GSConnect would point us towards the code that was causing the problem, but that assumes there _is_ something in the code that's causing the problem.

If your phone becomes unreachable, then it's definitely a network connectivity problem of _some_ sort. If you're going to be replacing the phone, the best course of action might really be to just wait and see if the new phone has the same issues. (And hope that it doesn't!)

That _feels_ like avoiding the problem rather than solving it. But since it's not clear where "the problem" is even coming from, it may not even be possible to _solve_ it, and we may have to be content with just making it go away. Please do keep us posted, though!

**Comment by alexgarel** [comment]
I'll close the issue however, as I can't reproduce it for now.
