### ISSUE TITLE
gjs - Playback position not available

### ISSUE THREAD

**Issue by tapsiturtle** [andyholmes/gnome-shell-extension-gsconnect#559]
I get constantly this message in my log:
```
Jun 15 10:15:53 turtlebook gjs[1099]: JS ERROR: GLib.Error rb_shell_player_error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._rb_5fshell_5fplayer_5ferror.Code4: Playback position not available
_proxyGetter@/home/tapsiturtle/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:391:23
_handleCommand@/home/tapsiturtle/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:141:21
async*handlePacket@/home/tapsiturtle/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:73:13
receivePacket@/home/tapsiturtle/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:392:21
receive/<@/home/tapsiturtle/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:178:25
@/home/tapsiturtle/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2

```

**System Details (please complete the following information):**

 - **GSConnect version:** 24
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.32
 - **Distro/Release:** Arch

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Fairphone 2

**Comment by andyholmes** [comment]
This seems to be expected behaviour for Rhythmbox:

https://github.com/GNOME/rhythmbox/blob/cbb3ae8bd635af1f2354aee8028107631b32bf46/shell/rb-shell-player.c#L2214-L2246

There are many media players with broken MPRIS implementations, but not much I can do about that. You can try [opening an issue upstream in Rhythmbox](https://gitlab.gnome.org/GNOME/rhythmbox/issues), but I expect they do this on purpose.

**Comment by ferdnyc** [comment]
> but I expect they do this on purpose.

And since Rhythmbox supports internet radio playback, having no `org.mpris.MediaPlayer2.Player.Position` may even be a _valid_ state, really. It's just not one supported by MPRIS2. Most players just display the elapsed time since playback of the station was started, as their "Position", don't know why Rhythmbox can't do the same.

But I have often thought that MPRIS2 should really have a fourth `Playback_Status` value, something that isn't `Stopped`, `Paused`, or `Playing` — maybe `Streaming`, or `Live`. Which would imply both `org.mpris.MediaPlayer2.Player.CanSeek = 0`, and the lack of reportable values for `org.mpris.MediaPlayer2.Player.Position`, `org.mpris.MediaPlayer2.Player.Rate`, and `org.mpris.MediaPlayer2.Player.[Minimum|Maximum]Rate`.

Maybe for MPRIS 2.3.
