### ISSUE TITLE
Notification on device charge completion

### ISSUE THREAD

**Issue by BobyMCbobs** [andyholmes/gnome-shell-extension-gsconnect#565]
**Is your feature request related to a problem? Please describe.**
Some people may have their devices charging in a different room, without a notification of knowing when the device has finished charging, they would have the check the device periodically (either physically or by GSConnect). A notification to say 'Device ____ has finished charging would be useful, as this would mean no periodic checking would be needed.

**Describe the solution you'd like**
The ability to receive notifications when a given device has finished charging.
This would possibly include a toggle in the settings per-device enabling this option.

**Describe alternatives you've considered**
Not applicable.

**Comment by ferdnyc** [comment]
I can see how the option to have GSConnect show a non-persistent<sup><b>1</b></sup> notification when the device reaches 100% charged would be useful.

Especially as there's already a notification on the _opposite_ end of the process: When the device's battery level drops below a certain percentage and it's _**not**_ charging, both desktop KDE Connect and GSConnect will show a device-power-low notification.

#### Notes
1. Why non-persistent? Because in my entire 8-year relationship with Android's UX in all its varied and endlessly shifting forms from version 2.1 through 7.0, **BY FAR** the single most rage-inducing aspect of any release, on any device — like, it's not even a close call, anything else would be a _distant_ second or lower — was the pop-up message dialog my Android 4.0.4 LG phone used to show whenever the battery finished charging.
   It _woke up the device_ just to tell me that the battery was full, which is stupid enough. But even worse, the next time I wanted to do anything with the phone, **I would first have to press "OK" on that popup to dismiss it!** How anyone could have ever thought that was a message that not only warranted interrupting the user, but required their **acknowledgement** of it, absolutely defies comprehension. If that phone had ever been rooted, I would've done it _just_ to get rid of that stupid message. (Sadly, the phone was too obscure, and had an encrypted bootloader that AFAIK nobody ever bothered breaking.)

**Comment by andyholmes** [comment]
> I can see how the option to have GSConnect show a non-persistent1 notification when the device reaches 100% charged would be useful.

Unfortunately, persistent notifications are the only option for us :stuck_out_tongue_closed_eyes:. but that's okay because we can withdraw them when we need to.

I think there are a lot of triggers like this users will want to act on, I'm just hesitant to go down the "build-in-everything" rabbit-hole. On the other hand, I've though about implementing either definable triggers (like tasker) or out-of-tree plugins. The reasons I haven't already are:

* By intentional design, almost every feature users could ever want (including this one) can already be implemented using the DBus interface, but I'm not aware of anyone ever using it.
* Definable triggers would have to be written anyways and the UI/UX of that doesn't seem like it will be straightforward.
* Out-of-tree plugins are an invitation to break the protocol and monkey-patch other code in GSConnect (aka egregious privacy & security risk).
* I spend too much time writing about writing code instead of just writing it :stuck_out_tongue_closed_eyes:

**Comment by andyholmes** [comment]
This should be mostly implemented now. There is no "fully charged" indication in the protocol for the battery plugin though, so user whose phone's never reach 100% will never get this notification. I might fix that down the road if it's an issue.

**Comment by BobyMCbobs** [comment]
Sorry for the delayed response, thank you for implementing this!

It's truely an amazing extension :smile:
