### ISSUE TITLE
Can't able to connect between Oneplus 5 and Inspiron 5548 for past couple of month.

### ISSUE THREAD

**Issue by PranavBhattarai** [andyholmes/gnome-shell-extension-gsconnect#568]
OnePlus 5 = Rooted, Magisk
Inspiron  5548 = Ubuntu 19.04 dual booted with Windows 10 Pro

No matters what I do, I can't seem to connect with between these two devices. 
In a limbo. 
Question/Doubts:
1. I hope enabling selinux is on not a problem. _Just in case, if it matters all of sudden._

**Comment by ferdnyc** [comment]
@PranavBhattarai Hmm, that's frustrating, and not a _whole_ lot to go on I'm afraid. But, maybe we can explore some possibilities.

1. You've made sure that the two devices are on the _same_ local network subnet and are reachable to each other, yes? The laptop is able to at least ping the IP address assigned to the phone, and gets a response?
2. Out of curiosity, since you mentioned Windows 10 dual-booting, have you tried installing [KDE Connect for Windows](https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Nightly_win64/) to see if _that_ can connect to your phone? If that doesn't work either, then it's not GSConnect's fault and we don't have to help you! 😉

   (Kidding, of course we'll still try to help. But it would be somewhat more accurate to say that if the problem also exists with the KDE Connect desktop app, then we _can't_ really help you, since the KDE developers wrote all of that code. But we can definitely point you in the right direction so that they _can_ hopefully help you.)

3. When you say you "can't connect" between the two devices — do they fail pairing attempts? Do they never even _detect_ each other on the network? From either side?

I know there's at least one GSConnect user whose device runs Magisk (#545), though that's the full extent of what I know about their configuration. They had some issues with mirrored notifications being delayed at times, which appeared to be overzealous power-management on the device's part... but discovering and pairing their devices, at least, was apparently not a problem.

**Comment by andyholmes** [comment]
@PranavBhattarai the log that you e-mailed me says you'll have to add yourself to the `systemd-journal` group in order to get log messages. Like @ferdnyc says, without those log messages there's not much to work with.

**Comment by PranavBhattarai** [comment]
@andyholmes can u mention the steps to create "systemd-journal" in order to make GSConnect working.

@ferdnyc Here are my answers according to ur question order:
1. Of course, both my laptop and mobile are always under the same wifi network. 
Both laptop or the mobile don't show any device available to pair up, so there is no point talking about ping.

2. I barely use Windows, so haven't tried it on windows yet. I might give it a try.

3. When I say I can't connect, it means no option either side of the device shows up. So, it's like both KDE connect and GS connect are engaged to not work/ respond at all.

It used to work so nicely...

**Comment by andyholmes** [comment]
> can u mention the steps to create "systemd-journal" in order to make GSConnect working.

You want to do something like:

    $ sudo usermod -a -G systemd-journal <username>

After this, you will probably have to log out and log in. Then you should be able to view journalctl logs and generate a support log.

> Both laptop or the mobile don't show any device available to pair up, so there is no point talking about ping.

If you can't ping your phone from your laptop, GSConnect definitely won't work:

    $ ping 192.168.X.X
    PING 192.168.0.68 (192.168.X.X) 56(84) bytes of data.
    64 bytes from 192.168.X.X: icmp_seq=1 ttl=64 time=25.7 ms
    64 bytes from 192.168.X.X: icmp_seq=2 ttl=64 time=66.10 ms

Where `192.168.X.X` is your phone's IP address.

**Comment by ferdnyc** [comment]
@PranavBhattarai @andyholmes Yeah, sorry, I should've made it more clear that I was referring to a standard network ICMP ping, not the KDE Connect / GSConnect "Ping" feature.

**Comment by PranavBhattarai** [comment]
@andyholmes 
I did this: $ sudo usermod -a -G systemd-journal pranav
I log out and log in.
I don't know what this means (newbie) and who to process this (sorry): _

> Then you should be able to view journalctl logs and generate a support log.

_

@ferdnyc Well, I went to my wifi setting. I can see that I have 192.168.10.2 is my IP address to my connected network. So I did this on terminal:
```
pranav@inspiron-5548:~$ ping 192.168.10.2
PING 192.168.10.2 (192.168.10.2) 56(84) bytes of data.
From 192.168.10.8 icmp_seq=1 Destination Host Unreachable
From 192.168.10.8 icmp_seq=2 Destination Host Unreachable
From 192.168.10.8 icmp_seq=3 Destination Host Unreachable

```

**Comment by andyholmes** [comment]
> Well, I went to my wifi setting. I can see that I have 192.168.10.2 is my IP address to my connected network.

This means there is a problem with your network preventing the two devices from communicating. Possibly a problem with a firewall or router.

If you're in the `systemd-journal` group now, [generating a support log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) will probably show `Host unreachable` errors as well.

**Comment by PranavBhattarai** [comment]
@andyholmes Can u tell me something that I can do in order to make this work?

> Well, I went to my wifi setting. I can see that I have 192.168.10.2 is my IP address to my connected network.
![Screenshot_20190703-104330](https://user-images.githubusercontent.com/32763112/60564526-bc798a00-9d7f-11e9-8b68-bb754e37e457.jpg)

I wonder why u pointed out this. I don't see any work in this. Let me clear it out more clearly:
> Well, I went to my mobile wifi setting. I can see that I have 192.168.10.2 is my IP address to my connected network.

And I don't know how to finish this:
> If you're in the systemd-journal group now, generating a support log will probably show Host unreachable errors as well.

But if this you are asking:

GSConnect Version: 24
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Wed 2019-07-03 10:09:02 +0545, end at Wed 2019-07-03 10:49:08 +0545. --
Jul 03 10:49:08 org.gnome.Shell.Extensions.GSConnect[5654]: [/service/protocol/lan.js:broadcast:315]: "Broadcasting to LAN"
Jul 03 10:49:08 systemd[1]: fprintd.service: Succeeded.

**Comment by andyholmes** [comment]
The log you posted shows that GSConnect is running and broadcasting correctly.

If the IP of your phone is `192.168.10.2` and you can not `ping` that IP from your laptop, then there is a problem in your network preventing the two devices from communicating with each other. Most likely this is a firewall or router.

**Comment by ferdnyc** [comment]
@PranavBhattarai 

The first question is, what IP address does your _computer_ have? It's unusual that the phone would be `192.168.10.2` if the computer is on the same network, since `192.168.10.1` is your router, and typically the computer would have picked up the earlier address (though not always).

You can check your computer's IP information in the Settings / Control Panel interface provided by whatever Linux distribution you run, or if push comes to shove you can just open a terminal window and run this command:
```
nmcli d show
```
That will have NetworkManager dump out the running configuration for your computer's network connection(s). It'll look something like this, from my desktop Fedora box currently:
```
nmcli d show  
GENERAL.DEVICE:                         eno1
GENERAL.TYPE:                           ethernet
GENERAL.HWADDR:                         xxREDACTEDxx
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     Profile 1
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/1
WIRED-PROPERTIES.CARRIER:               on
IP4.ADDRESS[1]:                         192.168.12.103/24
IP4.GATEWAY:                            192.168.12.1
IP4.ROUTE[1]:                           dst = 0.0.0.0/0, nh = 192.168.12.1, mt = 100
IP4.ROUTE[2]:                           dst = 192.168.12.0/24, nh = 0.0.0.0, mt = 100
IP4.DNS[1]:                             192.168.12.1
IP4.DOMAIN[1]:                          local
IP6.ADDRESS[1]:                         xxREDACTEDxx
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = fe80::/64, nh = ::, mt = 100
IP6.ROUTE[2]:                           dst = ff00::/8, nh = ::, mt = 256, table=255

GENERAL.DEVICE:                         xxREDACTEDxx
GENERAL.TYPE:                           bt
GENERAL.HWADDR:                         xxREDACTEDxx
GENERAL.MTU:                            0
GENERAL.STATE:                          30 (disconnected)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --

GENERAL.DEVICE:                         lo
GENERAL.TYPE:                           loopback
GENERAL.HWADDR:                         00:00:00:00:00:00
GENERAL.MTU:                            65536
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
IP4.ADDRESS[1]:                         127.0.0.1/8
IP4.GATEWAY:                            --
IP6.ADDRESS[1]:                         ::1/128
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = ::1/128, nh = ::, mt = 256
```

The important information there is that my computer is on my `192.168.12/24` local network, with an IP address of `192.168.12.103`. I know that my phone is connected to the same network with an IP address of `192.168.12.106`, which is why the two can communicate.

If your computer is on a different network from your phone, or the network isn't permitting them to reach each other. then GSConnect / KDE Connect will be unable to function over that network, and there's nothing that can be done except changing the network configuration. (Even if they are on the same network, it's possible it doesn't permit communication between clients. That's common of public open-access networks, even if you have two devices connected to the same wireless access point they'll be prevented from accessing each other for the users' protection.)

**Comment by PranavBhattarai** [comment]
@ferdnyc My Laptop ip address is **192.168.10.8** as you can see:

`pranav@inspiron-5548:~$ nmcli d show
GENERAL.DEVICE:                         wlxd46e0e0f6870
GENERAL.TYPE:                           wifi
GENERAL.HWADDR:                         D4:6E:0E:0F:68:70
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     SAVAGES
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/1
IP4.ADDRESS[1]:                         192.168.10.8/24
IP4.GATEWAY:                            192.168.10.1
IP4.ROUTE[1]:                           dst = 0.0.0.0/0, nh = 192.168.10.1, mt = 600
IP4.ROUTE[2]:                           dst = 192.168.10.0/24, nh = 0.0.0.0, mt = 600
IP4.ROUTE[3]:                           dst = 169.254.0.0/16, nh = 0.0.0.0, mt = 1000
IP4.DNS[1]:                             192.168.10.1
IP4.DOMAIN[1]:                          domain.name
IP6.ADDRESS[1]:                         fe80::9b88:ccf2:db37:fbc/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = fe80::/64, nh = ::, mt = 600
IP6.ROUTE[2]:                           dst = ff00::/8, nh = ::, mt = 256, table=255

GENERAL.DEVICE:                         enp2s0
GENERAL.TYPE:                           ethernet
GENERAL.HWADDR:                         34:17:EB:93:48:7C
GENERAL.MTU:                            1500
GENERAL.STATE:                          20 (unavailable)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
WIRED-PROPERTIES.CARRIER:               off

GENERAL.DEVICE:                         lo
GENERAL.TYPE:                           loopback
GENERAL.HWADDR:                         00:00:00:00:00:00
GENERAL.MTU:                            65536
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
IP4.ADDRESS[1]:                         127.0.0.1/8
IP4.GATEWAY:                            --
IP6.ADDRESS[1]:                         ::1/128
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = ::1/128, nh = ::, mt = 256

[4]+  Stopped                 nmcli d show
pranav@inspiron-5548:~$ nmcli d show
GENERAL.DEVICE:                         wlxd46e0e0f6870
GENERAL.TYPE:                           wifi
GENERAL.HWADDR:                         D4:6E:0E:0F:68:70
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     SAVAGES
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/6
IP4.ADDRESS[1]:                         192.168.10.8/24
IP4.GATEWAY:                            192.168.10.1
IP4.ROUTE[1]:                           dst = 0.0.0.0/0, nh = 192.168.10.1, mt = 600
IP4.ROUTE[2]:                           dst = 192.168.10.0/24, nh = 0.0.0.0, mt = 600
IP4.ROUTE[3]:                           dst = 169.254.0.0/16, nh = 0.0.0.0, mt = 1000
IP4.DNS[1]:                             192.168.10.1
IP4.DOMAIN[1]:                          domain.name
IP6.ADDRESS[1]:                         fe80::9b88:ccf2:db37:fbc/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = fe80::/64, nh = ::, mt = 600
IP6.ROUTE[2]:                           dst = ff00::/8, nh = ::, mt = 256, table=255

GENERAL.DEVICE:                         enp2s0
GENERAL.TYPE:                           ethernet
GENERAL.HWADDR:                         34:17:EB:93:48:7C
GENERAL.MTU:                            1500
GENERAL.STATE:                          20 (unavailable)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
WIRED-PROPERTIES.CARRIER:               off

GENERAL.DEVICE:                         lo
GENERAL.TYPE:                           loopback
GENERAL.HWADDR:                         00:00:00:00:00:00
GENERAL.MTU:                            65536
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
IP4.ADDRESS[1]:                         127.0.0.1/8
IP4.GATEWAY:                            --
IP6.ADDRESS[1]:                         ::1/128
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = ::1/128, nh = ::, mt = 256
`
And mobile ip is: **192.168.10.3** right now.
In router settings. **Wireless Isolation** is turned off which prevent the interaction between two devices.
As always, I know the devices need to connect in the same network.
Ubuntu firewall is disabled.
Android 9 Selinux is in the permissive mode so that it "may" interfere.

Anything else I am missing!? Especially in the router setting, which I don't know of, which can trigger this! But I doubt to see what happens in other wifi networks too. 

I have an idea, create a mobile hotspot from my brother mobile> connect my laptop and mobile in hotspot > check if connect/ping happens? @andyholmes 

By doing this, we will know if it's really the router issue or something else.

**Comment by Abhinav1217** [comment]
HI, I have a oneplus 7 and Running Solus OS. I spent almost entire day on a similar issue going through all the closed and open issues here, your wiki and googling, I was pretty sure it's a network related problem cause last time I used it, it worked out of box. Now after few months I thought I should set it up again, but no devices were found.

Ultimately it was matter of `iptables` firewall issue. I found solution on KDEConnect wiki.
```
sudo iptables -I INPUT -i <yourinterface> -p udp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo iptables -I INPUT -i <yourinterface> -p tcp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT

sudo iptables -A OUTPUT -o <yourinterface> -p udp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -o <yourinterface> -p tcp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
```

Although I did make sure port 1716 was open, on both UDP and TCP, It worked only after running this on terminal.

 I wanted to submit a pull request on wiki page under section `common problems` to include this, but I couldn't figure out submitting pull request on wiki.

**Comment by ferdnyc** [comment]
> Although I did make sure port 1716 was open, on both UDP and TCP, It worked only after running this on terminal.

Hm! Very odd, but if it works... :+1: 

> I wanted to submit a pull request on wiki page under section `common problems` to include this, but I couldn't figure out submitting pull request on wiki.

Like any 'real' Wiki, the wiki is directly editable by anyone, so there's no PR infrastructure. You can either submit edits directly via the web interface, or you can clone https://github.com/andyholmes/gnome-shell-extension-gsconnect.wiki.git if you'd prefer to make edits offline and push the commits back up to the repo.

**Comment by PranavBhattarai** [comment]
> sudo iptables -I INPUT -i <yourinterface> -p udp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
> sudo iptables -I INPUT -i <yourinterface> -p tcp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
> 
> sudo iptables -A OUTPUT -o <yourinterface> -p udp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
> sudo iptables -A OUTPUT -o <yourinterface> -p tcp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT

Just to make sure, <yourinterface> means my wifi-receiver's device name, right?
Which is "wlxd46e0e0f6870", as I mentioned in the above screenshot where I have shown the output of **nmcli d show**, right?

**Comment by ferdnyc** [comment]
@PranavBhattarai 
Interface name is listed in the first column of the `nmcli d` output, "DEVICE". It's usually a short name like `eth0`, `eno1`, `ewl1`, sometimes `eno1p0` or something like that if it has multiple ports (virtual or physical).

**Comment by ferdnyc** [comment]
(Mine is `eno1`, but I can also see my phone's bluetooth and the local loopback interface `lo`):
```
$ nmcli d
DEVICE             TYPE      STATE         CONNECTION 
eno1               ethernet  connected     Profile 1  
aa:bb:cc:dd:ee:ff  bt        disconnected  --         
lo                 loopback  unmanaged     --

**Comment by ferdnyc** [comment]
(Also, there shouldn't be any braces around the name, that was just for illustration purposes in @Abhinav1217 's example. So if yours were also named `eno1` you'd want:
```
sudo iptables -I INPUT -i eno1 -p udp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo iptables -I INPUT -i eno1 -p tcp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT

sudo iptables -A OUTPUT -o eno1 -p udp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -o eno1 -p tcp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
```

**Comment by PranavBhattarai** [comment]
@ferdnyc I ran all the commands, as @Abhinav1217 said as u can see below:
![Screenshot from 2019-08-18 13-33-04](https://user-images.githubusercontent.com/32763112/63221750-44471680-c1bd-11e9-83d2-9a214bfb6ef8.png)
Turn on/off the wifi. Log out and log in. 
But both my mobile (KDE connect) and PC's (GS connect) don't show each other like it used to do a long time ago.

**Comment by ferdnyc** [comment]
@PranavBhattarai 

Is `wlxd46e0e0f6870` _really_ the device name of your network interface!? The same one that's shown in `nmcli d` or `ifconfig`? I'm not doubting you, that's just a _crazy_ interface name and I don't think I've ever seen anything remotely that unwieldy — except maybe on big Cisco switches or thousand-port 3Com modem servers or something.

...Anyway, no, the port numbers should work because `1714:1764` is a range. It'll apply to all ports between the start and end values, inclusive.

As far as that quote, I believe @Abhinav1217 was referring to the system firewall — which I guess on both Solus and Ubuntu is `ufw`? Since you said you'd done much the same, made sure it was disabled / wasn't blocking those ports.

Hey, just out of curiosity (well, really, to inform the discussion in #593), could you report the output of this command on your machine?
```sh
cat /proc/sys/net/ipv6/bindv6only
```
It'll be a single digit, just a 0 or 1.

**Comment by ferdnyc** [comment]
> Is `wlxd46e0e0f6870` _really_ the device name of your network interface!?

(Actually, never mind, I can see from the `nmcli d show` output you posted a while back that, yes, it really is.) **#craaazy**

**Comment by ferdnyc** [comment]
Actually, while we're at it, another command that might be informative (with sample output from my own system):
```console
$ netstat -tunelp|grep gjs
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::1716                 :::*                    LISTEN      1000       79991      10708/gjs           
udp        0      0 0.0.0.0:1716            0.0.0.0:*                           1000       79990      10708/gjs           
```
Because `/proc/sys/net/ipv6/bindv6only` is `0` on my system, the `tcp6 :::1716 LISTEN` implies IPv4 as well, so I can make a test connection to GSConnect with `telnet 127.0.0.1 1716`. But I suppose it's possible that's not true on all distros.

**Comment by Abhinav1217** [comment]
@ferdnyc I added a section on wiki help under the `uncommon problems` part. I added link to KDE community site for further reading as it has nice solutions regarding firewall and iptables.

@PranavBhattarai That is weird device name, What is your network card. Just curious. 

> Should I also have to use same 4 commands with by changing the port number to "1716"?
These are different commands for INPUT and OUTPUT on UDP and TCP connections. By default KDE/GS Connect uses 1716 port, But GSConnect wiki says it uses anything between 1716-1764 for connection. While KDEConnect wiki states range from 1714-1764, I just used the wider range because nothing was helping me at that time, and I wanted to be sure. 

I have installed ufw in solus and use gufw to manage ports. I made sure entire port range was available on ipv4/ipv6 on firewall. But it still wasn't connecting to my mobile. I decided to look on KDEConnect wiki and it has some more solutions for firewall related issues, That's when I found out about iptables and it worked.

**Comment by andyholmes** [comment]
Thanks for adding to the wiki :)

Strictly speaking, the KDE Connect protocol uses these ports:

* 1716 TCP & UDP
  * TCP for device connections and UDP for network discovery
* 1739-1764 TCP-only
  * These ports are used for anything other that packet exchange; file sharing, sftp/ssh, notification icons, etc.

The primary port was previously 1714, but that hasn't been used in a very long time (protocol version <= 6, I believe).

**Comment by PranavBhattarai** [comment]
A recheck on **ufw**, since i reinstall Ubuntu 19.04 due to dpkg errors like a week ago, does this somes bad? Is it not healthy for GSconnect?
![Screenshot from 2019-08-18 14-41-28](https://user-images.githubusercontent.com/32763112/63222342-5e392700-c1c6-11e9-9b3c-0726e511be02.png)

**Comment by PranavBhattarai** [comment]
@ferdnyc 
```
pranav@Inspi5548:~$ netstat -tunelp|grep gjs
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::1716                 :::*                    LISTEN      1000       34693      2014/gjs            
udp        0      0 0.0.0.0:1716            0.0.0.0:*                           1000       34692      2014/gjs            
pranav@Inspi5548:~$ 

```

**Comment by ferdnyc** [comment]
@Abhinav1217 
> That is weird device name

It's actually the MAC address of the interface (WiFi adapter), appended to `wlx`. Which is... fine, whatever, I guess. My only real objection is that it's annoyingly long and seems practically _designed_ to sabotage any attempts to type it in by hand, more than anything else.

**Comment by PranavBhattarai** [comment]
@ferdnyc @Abhinav1217 @andyholmes 
Come to the main topic? Why I can't seem to connect these two devices?
My phone (1+5) is rooted and selinux is enabled. 
Its their other things to check on my mobile side? 
Pinging my Laptop IP address from Termux in mobile don't make any difference.

I again ran **sudo ufw disable** command and reboot and check GS connect. It didn't make any difference.

**Comment by ferdnyc** [comment]
@PranavBhattarai Hm. OK, well, no surprises there on the `netstat` and `proc` values, everything looks in order. I know exactly nothing about `ufw`, but just from a general firewall standpoint that configuration sounds fine, the default policies sound fine, opened ports would override those defaults anyway, and as you say even having it installed or not doesn't make a difference so it doesn't _seem_ like that's the issue.

> Pinging my Laptop IP address from Termux in mobile don't make any difference.
But it does _succeed_, right?

Hmm. Since your phone is rooted, does it have a `telnet` command on it? (My unrooted Galaxy S6 does not, unshockingly, but I can use the ConnectBot app to make telnet connections.) I'm just curious what happens if you try to `telnet 192.168.10.8 1716` (or equivalent) from the phone. If you're successful it'll just connect silently (no output, just a blinking cursor waiting for input), if there's any problem then presumably it'll come back with a connection error/timeout of some sort.

**Comment by PranavBhattarai** [comment]
@ferdnyc 
![Screenshot_20190818-152730](https://user-images.githubusercontent.com/32763112/63223039-8da06180-c1cf-11e9-92aa-e9dc1daf0dc7.jpg)

I don't know what telnet is, but when I type **telnet --help** it works i.e it shows a lot of options to try.

**Comment by ferdnyc** [comment]
> I don't know what telnet is, but when I type **telnet --help** it works i.e it shows a lot of options to try.

Ah, cool, that's handy. Telnet just makes unencrypted network connections to TCP ports, `telnet $DESKTOP_IP 1716` would simulate the process of KDE Connect trying to contact GSConnect.

...But before we can try that: So, even _pings_ from your phone to your desktop are failing? (The phone is `192.168.10.10`, the desktop is `192.168.10.4`, yes?)  That's not a great sign for any other sort of network connection working.

**Comment by PranavBhattarai** [comment]
@ferdnyc This is the output of telenet from mobile:
$ telnet 192.168.10.4 1716
Trying 192.168.10.4...
telnet: Unable to connect to remote host: No route to host
$

192.168.10.4 is my laptop's current IP address. And 1716 is my laptop TCP stuff (idk).

**Comment by ferdnyc** [comment]
Yeah, which I kind of expected from the failed pings. So, it _looks_ like something is preventing devices on your wifi network from communicating with each other, most likely the wifi router in use. I know you said Wireless Isolation is turned off, but it seems like **something** is interfering with connections between the local devices.

**Comment by PranavBhattarai** [comment]
@ferdnyc I think it's normal. 
I have noticed that router assign IP based on who comes first. 10.1, 10.2 etc.
If there is no manual IP assained in the receiver (mobile, laptop) or sender device (router) settings.
I think its common thing to expect.

**Comment by PranavBhattarai** [comment]
Let's assume its router fault. 
Now, what if, I use another mobile to create a wifi hotspot (without enabling the data).
And connect laptop and mobile on the same wifi hotspot, practically it should work right?
@ferdnyc

**Comment by ferdnyc** [comment]
@PranavBhattarai Probably not that specific approach, actually, as phone hotspots almost _always_ prevent interclient communication. But trying another wifi router / access point, in general, would be a good option for determining whether it's the router. (It just has to be a _real_ network router, the simpler / more-"dumb" it is the better really. Advanced routers often have more layers of security, wanted and unwanted.)

**Comment by PranavBhattarai** [comment]
@ferdnyc @Abhinav1217 @andyholmes 
Problem solved. 
After lots of attempts, probably breaking some fundamental rules & regulation, this 2 month old problem is resolved. 
My conclusion might seems out of frustation but **KDE & Gsconnect is not perfect yet.**
_Hope it will be better in future._
**Thanks everyone for sticking up.** 
There are multiple issues. The last issue, was wifi isolation which i saw was enabled. I disable it. Rebooted my wifi. Boom. Problem solved. Ofcoure firewall was also one big issue. 

Firewall is good thing. I want to use it. I think firewall should work now without disturbing GSconnect.  Ciao. Take care. Rest in peace.
