### ISSUE TITLE
Panel or User Menu, both don't show.

### ISSUE THREAD

**Issue by mercertom** [andyholmes/gnome-shell-extension-gsconnect#569]
**Describe the bug**

Can't see the indicator, despite activating the extension, and having it paired to the phone.

**Steps To Reproduce:**

Ubuntu 19.04, Gnome 3.32.1, all up to date.
Install GSConnect on extensions.gnome.org.
Pair a phone

**Expected behavior**

There's an indicator in the upper right, a drop-down menu you can use to access your phone by GSConnect.

**Screenshots**
![Screenshot from 2019-06-30 19-31-34](https://user-images.githubusercontent.com/10352876/60403646-efe4ca80-9b6d-11e9-8248-5bef5e2d7232.png)

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
GSConnect Version: 24
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Tue 2018-09-11 15:06:45 EDT, end at Sun 2019-06-30 19:35:53 EDT. --
-- No entries --
```

**System Details (please complete the following information):**

 - **GSConnect version:24
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.32.1
 - **Distro/Release:** Ubuntu 19.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Irrelevant. This used to work, now it doesn't. It's still paired, just GSConnect doesn't display on the computer.

**Comment by andyholmes** [comment]
Is the device connected? Are there any errors in GNOME Logs or `journalctl` that might related to this?

**Comment by mercertom** [comment]
The device is connected. I don't know how to find my gnome log.

**Comment by andyholmes** [comment]
You should be able to find them in the *GNOME Logs* application:

![Screenshot from 2019-06-30 19-31-38](https://user-images.githubusercontent.com/1265208/60407023-c1ff8600-9b6d-11e9-9cf0-64c250193ef6.png)

You can search for `gsconnect` or maybe even `gnome-shell` to see if there are any errors.

**Comment by mercertom** [comment]
Installed it, nothing by searching those terms.

**Comment by ferdnyc** [comment]
> Installed it, nothing by searching those terms.

How about "`gjs`", the JavaScript runtime that GSConnect runs inside?

**Comment by mercertom** [comment]
no results

**Comment by andyholmes** [comment]
Unfortunately if there are no errors in any of your logs, it's difficult to determine what's going wrong. If there's an error in the shell extension, there should be messages printed to `journalctl` by GNOME Shell and since I can't reproduce this, I'm not sure how to help.

**Comment by mercertom** [comment]
Dang, so when you go to https://extensions.gnome.org/local/, and turn on
your extension, in 19.04, it just works? And pops up in the menu like in
old times?

**Comment by andyholmes** [comment]
Nothing major has changed in the way the shell extension works for a long time. I'd guess if this was a common problem there would be a lot more reports about it :/

**Comment by ferdnyc** [comment]
\*nod* I'm running Fedora 30, not Ubuntu 19.04, but... yeah, everything still Just Works®. There are countless users on 19.04, so as @andyholmes says we'd have heard if there was a general problem. Something in your setup must be to blame.

Only exception to that in recent _memory_, for me, was when my phone installed the first beta of KDE Connect 1.12.7, and my devices lost the ability to connect until I reset the pairing from both ends. But that was clearly an app issue, because that update was followed by <i>three</i> more in just 4 or 5 days, as they scrambled to fix whatever was going on with that.

It does point to an approach, though: Have you tried _completely_ resetting your GSConnect install, using [the full-reset procedure](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings) from the Wiki's Help page?

If not, do. Clearly, there's something not-right with GSConnect on your system, and just starting over from the beginning has a better chance than anything else of fixing whatever it is.

**Comment by mercertom** [comment]
Please update the full-reset procedure! It doesn't include turning
everything back on!

Frank, thank you. Something among all the things I tried after following
the full-reset procedure, and reinstalling the firefox gnome extensions
add-on, things appear to be working again. I'm pretty sure this was a
problem with gnome extensions as a whole, perhaps the firefox extension,
perhaps the system gnome extension settings.

**Comment by andyholmes** [comment]
@mercertom It's a wiki, so you can add that if you like :)

Glad you got things working :+1:
