### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by vberthet** [andyholmes/gnome-shell-extension-gsconnect#571]
**Describe the bug**

GsConnect process consume tons of RAM (17GB): 
![Capture du 2019-07-04 15-10-01](https://user-images.githubusercontent.com/1115715/60669672-2a50af00-9e6f-11e9-8540-f0639382f111.png)
On this capture process is paused (to prevent OOM), but CPU usage is 100% when not paused.

Notification seems to be duplicated, I also have a strange notification where content is ":undefined" : 
![Infobulle_236](https://user-images.githubusercontent.com/1115715/60670828-e317ed80-9e71-11e9-9e32-0aa7715aeb64.png)

**Steps To Reproduce:**

It's append randomly, or at least i haven't found a way to reproduce.

**Expected behavior**

Use a reasonable amount af RAM 

**Support Log**

> JS WARNING: [/home/vincent/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/notification.js 474]: reference to undefined property "title"

> JS WARNING: [/home/vincent/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/notification.js 474]: reference to undefined property "title"

![Capture du 2019-07-04 15-41-20](https://user-images.githubusercontent.com/1115715/60670987-51f54680-9e72-11e9-82c1-23f07cbd0260.png)

Strace output : [gsconnect_strace.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3359574/gsconnect_strace.txt)

Using sysprof : [sysprof.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3359611/sysprof.zip)

Sadly i can't use the "Generate Support Log", the ui doesn't respond.

> GSConnect Version: 24
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 20, 24, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version: GNOME Shell 3.28.3
 - **Distro/Release:** Ubuntu 18.04

**GSConnect environment (if applicable):**

 - **Paired Device(s): Redmi Note 7
 - **KDE Connect app version: 1.12.6
**Additional Notes:**

**Comment by andyholmes** [comment]
Is this only happening when notifications are duplicated, or is that an unrelated problem?

**Comment by vberthet** [comment]
Notification are'nt duplicated, I've been misled by an another application (mails notification were duplicated). 
I've this problem exclusively with my desktop computer. I also use GsConnect with my laptop without this issue.

**Comment by ferdnyc** [comment]
> Notification are'nt duplicated, I've been misled by an another application (mails notification were duplicated).

:rofl: I had that _exact_ thing happen to me once, too. Not duplicate notifications, but I couldn't figure out why GSConnect was showing certain notifications differently than the rest... and it was because they were web notifications coming from Chrome, GSConnect had nothing to do with it!

In a few years we'll probably have no idea **_how_** most information actually reaches us, as connected as life is becoming. (Nor will most people care, or think to wonder.) Scary thought.

I notice you're still running KDE Connect `1.12.6`. The latest version is... hrm, I'm in the beta program so it says `1.12.93` on my phone... but I think `1.12.9` is out, _definitely_ `1.12.7` — that's been out for months.

Admittedly, I don't _really_ think the older version has anything to do with this issue. (Although if you have remote mountable shared folders configured in the app... it might!)

**Comment by ferdnyc** [comment]
@vberthet Are you still having issues with GSConnect consuming excessive RAM/CPU? (And if so, did you see the note in my previous comment about your KDE Connect app version being out-of-date? Just in case that _is_ somehow causing this...)

**Comment by vberthet** [comment]
I still have the same problem with latest KDE Connect version (1.12.93)
it's appends randomly (didn't append since one month)
PS : i also use GSConnect on my laptop without any issue.

**Comment by meddario** [comment]
Hi,

i think that i am experiencing the same thing.

KDE Connect `1.12.93`
GSConnect (latest at the time of writing)
Ubuntu 18.04 + latest updates (Gnome shell 3.28.2)

The `service/daemon.js` process takes 100% of one CPU core and 15GB of ram + 11GB of swap. The system is obviously unusable when running this extension.

I noticed a strange behaviour before the problem: on the desktop a network folder named "192.168.x.x" (I don't remember exactly, it was the phone's ip in the local network) appeared and disappeared every 2-3 seconds. Opening the folder showed the phone's internal memory.
Maybe the leak is related to this network share appearing and disappearing continously?

Another thing: this memory leak does not happen every time. The 100% CPU core problem is more frequent.

In the attached screenshot you can see the problem, let me know if i can provide more information.

![gsconnect_leak](https://user-images.githubusercontent.com/16596646/64132268-da3e8c00-cdce-11e9-8a38-0892ea43186e.png)

**Comment by andyholmes** [comment]
Hmm, thanks that's some useful information. I noticed a little while ago (a week, two?) there was a particular situation where a failed unmount operation could result in an unresolved Promise. This can be really bad because those float around in the main loop holding a reference on all sorts of things until the program exits.

I believe I fixed that particular problem in 570ff0b when I refactored the whole SFTP plugin. Possibly this was just not a noticeable issue until something changed in kdeconnect-android's SFTP plugin, which has been happening.

I've been doing a lot of refactoring in the lead up to v25 so master isn't *super* stable right now, but you can give this Zip a shot if you're up to it. If you do, you can expect a few minor quirks, but I'd be happy to hear if this helps with the problem.

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3567063/gsconnect%40andyholmes.github.io.zip)

**Fair warning**: this works for me and I haven't had anything worse than a few warnings in the log, but you might have some problems and need to unpair and repair if you go back to an older Zip. For reference:

* [Installing from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)
* [Clearing all settings](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings)

**Comment by meddario** [comment]
Thank you, I'll try this in the next days and let you know!

**Comment by meddario** [comment]
Hi Andy, i tried the extension from the zip file, but it gives me a "network error" https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#LanError and I can't pair the device.

**Comment by andyholmes** [comment]
@meddario Sorry, this one slipped my mind :S 

The error you got was very much my fault. I believe this is now fixed in `master`, but there are a few quirks not worked through yet. If you're still having this bad memory leak, it might be worth [installing from git](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-git), but I'm hesitant to upload a Zip until those quirks are fixed.

If you do give it a shot, please do let me know how it works out for you.

**Comment by vberthet** [comment]
I've reinstall gsconnect and clear gsconnect config on 7 Aug, the problem didn't append since.
Maybe you could try that ? 

Ii'm not sure we've got the same bug, in your case you have multiple gjs process.
