### ISSUE TITLE
Call number: Dont ask for device when only one device available

### ISSUE THREAD

**Issue by tvld** [andyholmes/gnome-shell-extension-gsconnect#574]
When I call a number, e.g. open a  ``tel:+123234565`` link in the browser, GS Connect asks me each time to choose a device and then "Select" it. Two clicks extra which does not make sense with only one device configured. 

![Screenshot from 2019-07-18 11-05-20](https://user-images.githubusercontent.com/986182/61444601-fa63da00-a94b-11e9-8e98-05e269fa097f.png)
Can't we skip that step and select the one device automatically ? Maybe even with a "Automatically select this device from now on" - setting ;-)

Or at least pre-select it... :
![Screenshot from 2019-07-18 11-06-59](https://user-images.githubusercontent.com/986182/61444715-3b5bee80-a94c-11e9-972f-3f5cfa09dd01.png)

**Comment by andyholmes** [comment]
I'm kind of favoring the second option. We used open automatically when there was only one device, but decided to always show the popup.

If I recall from talking to KDE Connect developers, they do this because it might be that only one device is online and it gives some notice to the user. There's not much risk in this case, since we don't *actually* dial the number, but this is automatic link handling so it could happen without user interaction.

I think auto-selecting the first item is a good idea though, that way it's only one click or enter. Selecting a default device is possible, but requires more work because it has to be stored, an option to de-select has to be somewhere, etc. That might be useful elsewhere though, so I'll keep it in mind :)

**Comment by tvld** [comment]
Great :-) ... Looking forward to test it out )
