### ISSUE TITLE
No remote keyboard connection- window

### ISSUE THREAD

**Issue by network4u** [andyholmes/gnome-shell-extension-gsconnect#583]
I've installed kdeconnect on Nexus5X and Ubuntu 18 (I use it with kconnect indicator and mate). When I try to set up a remote keyboard connection (using my computers keyboard for typing to my phone) no typing window pops up on my computer. clicking on the establish-keyboard-connection button on my phone, it says the connection is alive

**Comment by ferdnyc** [comment]
@network4u 

I believe the GSConnect keyboard is only accessible if you bind it to a keyboard shortcut and open it manually — I don't _think_ it's automatic. I'm not sure, since I don't use it, but regardless going into Mobile Settings > Device > Keyboard Shortcuts, clicking Keyboard, and setting a shortcut to bring up the keyboard allowed me to then manually pop it up.

**Comment by network4u** [comment]
I'm sorry, I think i confused GSConnect with KDEConnect
