### ISSUE TITLE
Update meson build system

### ISSUE THREAD

**Issue by andyholmes** [andyholmes/gnome-shell-extension-gsconnect#596]
As a target for v25, we should revisit the whole meson build system and while we're at it look at bumping the minimum requirements of `gnome-shell` and `gjs`. This is a brief list of what this will look like:

- [x] Decide on version of meson
- [x] Correlate with Ubuntu, Fedora versions in circulation (Arch, etc, should be okay)
- [x] Bump `gnome-shell` and `gjs` requirements to match
- [x] Remove defunct backwards-compatible workarounds
- [x] Re-organize build system

**Comment by ferdnyc** [comment]
For meson:

* Fedora's at 0.51.1 (latest) all the way back to Fedora 29 (oldest supported release), so that's no biggie. 

    What [will be an issue](https://apps.fedoraproject.org/packages/meson) is RHEL / CentOS. EPEL7 is still on 0.47.2 (and only updated to that version because they were upgrading Python from 3.4 to 3.6 and had to rebuild everything anyway). EPEL for RHEL6 is way back at 0.44, so they can't even use the _current_ `meson.build`.

* Ubuntu Eoan (19.10) and Debian Sid are [also both at](https://launchpad.net/meson/+packages) 0.51.1, but things fall off quickly after that.
  - Disco (19.04) : 0.49.0
  - Cosmic (18.10) : 0.47.2
  - Bionic (18.04) : 0.45.1
  - And then Artful, Xenial, Trusty are again below our existing 0.45, even.

So, raising the version requirement above even the current 0.45 is going to cut off **some** users who are still running older releases. But, Meson's not _that_ hard to upgrade locally, really.

In terms of "want to have"s, reading through the release notes the newest features that seem like we might potentially care about them are all in [meson 0.49](https://mesonbuild.com/Release-notes-for-0-49-0.html) or earlier:

#### 0.49
* [Joining paths with /](https://mesonbuild.com/Release-notes-for-0-49-0.html#joining-paths-with-)
    Replaces `path = join_paths('path', 'to', 'something')` with `path = 'path' / 'to' / 'something'`
* [Foreach `break` and `continue`](https://mesonbuild.com/Release-notes-for-0-49-0.html#foreach-break-and-continue)
#### 0.48
* [Dictionary addition](https://mesonbuild.com/Release-notes-for-0-48-0.html#dictionary-addition)
* [Dist scripts](https://mesonbuild.com/Release-notes-for-0-48-0.html#dist-scripts)
#### 0.47
* [Feature detection based on meson_version: in project()](https://mesonbuild.com/Release-notes-for-0-47-0.html#feature-detection-based-on-meson_version-in-project) will warn _us_ if we use a feature that's newer than the configured minimum `meson_version`
* [New built-in object type: dictionary](https://mesonbuild.com/Release-notes-for-0-47-0.html#new-builtin-object-type-dictionary)
#### 0.46
* The all-important [`install_data()` supports `rename:`](https://mesonbuild.com/Release-notes-for-0-46-0.html#install_data-supports-rename)
* [test() now supports the depends: keyword argument](https://mesonbuild.com/Release-notes-for-0-46-0.html#test-now-supports-the-depends-keyword-argument) to autobuild dependencies before running a test (something I only recently learned is basically _impossible_ in CMake/CTest, amazingly enough)

0.50 / 0.51, though... meh. [Nothing](https://mesonbuild.com/Release-notes-for-0-50-0.html) really [jumps](https://mesonbuild.com/Release-notes-for-0-51-0.html) out.

**Comment by andyholmes** [comment]
Wow, that's annoying legwork I didn't want to do myself, thanks :smile: 

Yeah, the `rename` is definitely the big one. I think a jump to `0.49` is probably where I'd prefer go. Like you said it's pretty simple to update manually if necessary, most distros actually packaging GSConnect are either way behind (*cough* Ubuntu *cough*) or rolling like Arch/NixOS and most testers are just using the RC's.

I have an inclination to bump our minimum `gnome-shell` to 3.32 for v25. It had a reasonable amount of breaks we had to adjust for, and frankly the 18.04 LTS is a willful choice to be out of date at this point. Moreover, the GJS GC-fix is probably going to be in 3.36 rather than 3.34, there's the new `ClutterDeviceManager` we could probably use for input, the new clipboard API is in there somewhere, mutter w/ pipewire support; there are just a lot imminent changes/improvements coming. Try to hang on to 3.28 is going to block us on most of those big problems until at least Ubuntu 20.04 LTS.

I think that might ruffle some feathers, but lately I've had a lot less time available so easing the maintenance burden is probably for the best. Thoughts?

**Comment by ferdnyc** [comment]
> I have an inclination to bump our minimum `gnome-shell` to 3.32 for v25. It had a reasonable amount of breaks we had to adjust for, and frankly the 18.04 LTS is a willful choice to be out of date at this point. Moreover, the GJS GC-fix is probably going to be in 3.36 rather than 3.34, there's the new `ClutterDeviceManager` we could probably use for input, the new clipboard API is in there somewhere, mutter w/ pipewire support; there are just a lot imminent changes/improvements coming. Try to hang on to 3.28 is going to block us on most of those big problems until at least Ubuntu 20.04 LTS.
> 
> I think that might ruffle some feathers, but lately I've had a lot less time available so easing the maintenance burden is probably for the best. Thoughts?

Hmm. I think letting go of the older releases is understandable, given the breadth of the changes needed for or dependent on newer releases. But, I'm a Fedora user; I know from experience there are a _lot_ of Ubuntu and CentOS users running distros that still ship 3- or 5-year-old releases of things.

The code as it currently stands still works with 3.28, though, right? If it does, and since v25 is relatively close to "there", if you wanted to ruffle the fewest feathers you could release a v25 compatible with 3.28 and 3.30, but announce that it's the final version to support those releases. 

Then, immediately **after** the release, go through and gut the legacy code. Maybe even branch the repo at a v25 release, just in case some critical bugfix needs to be backported. (The branching could also be done later off the v25 tag, if there's a need, of course.)

That way, the users on < 3.32, some of whom may have already gotten a taste of the v25 features via the `-rc` builds, aren't frozen out of the final release.

**Comment by ferdnyc** [comment]
> Maybe even branch the repo at a v25 release, just in case some critical bugfix needs to be backported. (The branching could also be done later off the v25 tag, if there's a need, of course.)

(This is just me thinking out loud, now...)

I wonder how that would work with e.g.o? Its versioning tends to create an impression that each extension update is expected to be compatible with the same or _newer_ Shell releases, but I _think_ it should do the right thing as long as the metadata is correct. (Or if not, I think we'd be justified in reporting it as a bug.)

Like, say you did basically what I described above:
* release v25 for `"shell-version": [ "3.28", "3.30", "3.32" ]`
* The codebase then moved up to `"shell-version": [ "3.32", "3.34" ]`
* A bugfix had to be backported into the v25 branch, resulting in...
  - v26 for `"shell-version": [ "3.28", "3.30" ]`
  - v27 for `"shell-version": [ "3.32", "3.34" ]`

...Would everyone get updated correctly, even with shell version enforcement currently switched off? (Swapping v26/v27 might result in users on 3.32+ ending up with the backported legacy fix simply because it's the latest release, which would break things for 3.34 users. The question is, in _this_ order, will e.g.o properly **not** offer the v27 update to the legacy users?)

**Comment by andyholmes** [comment]
>  ...if you wanted to ruffle the fewest feathers you could release a v25 compatible with 3.28 and 3.30, but announce that it's the final version to support those releases.

Yeah, actually that's a good idea. I don't know when the next Android release is, but we'll need to have the new SMS/MMS stuff in place or users will have to use older versions of the app. After that though, I think it'll just have to be the way it is when you choose to run older versions of software.

I think the easiest way (to make it easy for others) is to leave a branch off that tag and if someone wants to maintain it they can cherry-pick fixes and submit them as PRs or just outright fork. I guess that's what Zorin OS might do.

> I wonder how that would work with e.g.o?

I honestly don't know. Even when enabled the [version check code is pretty confusing](https://gitlab.gnome.org/Infrastructure/extensions-web/blob/master/sweettooth/extensions/views.py#L48), so without running a local test server it's hard to be confident.

I know of at least three extensions that do exactly what you describe, notably Ubuntu's AppIndicator extension, but I have no idea how that plays out because I'm almost always running the latest GNOME Shell.

**Comment by ferdnyc** [comment]
> I know of at least three extensions that do exactly what you describe, notably Ubuntu's AppIndicator extension, but I have no idea how that plays out because I'm almost always running the latest GNOME Shell.

Same here, but I do use that extension, and haven't _seen_ any problems with updating... and we can probably assume they wouldn't keep doing it that way if it didn't work. After downloading a few versions, it looks like they do exactly as I described:

* `v22`: `"shell-version": [ "3.16", "3.18", "3.17.91", "3.20", "3.22", "3.24", "3.26" ]`
* `v23`: `"shell-version": [ "3.32" ]`
* `v24`: `"shell-version": [ "3.16", "3.18", "3.17.91", "3.20", "3.22", "3.24", "3.26", "3.28", "3.30" ]`
* `v25`: Never released, AFAICT
* `v26`: `"shell-version": [ "3.16", "3.18", "3.17.91", "3.20", "3.22", "3.24", "3.26", "3.28", "3.30" ]`
* `v27`: `"shell-version": [ "3.32" ]`

It's also interesting that even though `v25` (presumably a `3.32` update) wasn't released, timing doesn't seem to have been an issue.
* `v23` was released Feb 24
* `v24` was released Mar 27
* `v26`/`v27` were released together on Apr 9. 

So, there was a week-plus time period where `v24` was the newest release, and apparently it didn't cause any problems for those of us running `3.32`. Maybe the ordering's not even as critical as I feared.

**Comment by andyholmes** [comment]
Hmm, interesting. Well, it did occur to me that since ZorinOS forked, their version should keep supporting older shell versions, once it's reviewed on ego.
