### ISSUE TITLE
Add battery percentage to GSConnect icon

### ISSUE THREAD

**Issue by tukusejssirs** [andyholmes/gnome-shell-extension-gsconnect#606]
It would be nice to see the battery percentage in the icon (both in the indicator and in the Mobile devices menu).

**Comment by andyholmes** [comment]
I'm not sure what you mean? Both the device indicator and menu show the battery percent:

![Screenshot from 2019-09-02 13-17-20](https://user-images.githubusercontent.com/1265208/64132422-a5a5e280-cd84-11e9-9618-251448640708.png)

**Comment by tukusejssirs** [comment]
Okay, on second thoughts: the battery indicator in the menu is perfect.

However, I think the battery indicator should be _on_ panel instead of the icon (there’s probably a need to differentiate the battery indicator from the laptop battery indicator, but I don’t care that much about it). See this picture (sorry, I did it in hurry :smile:).
![gsconnect_bat_indicator](https://user-images.githubusercontent.com/5111894/64148927-db020d00-ce24-11e9-9f2a-a581acb73625.png)

**Comment by ferdnyc** [comment]
@tukusejssirs As you say, because of the (very real) potential for confusion with the _local_ device's battery level, I don't think it's that much of an inconvenience to have the battery level of the paired device be **one** click away.

**Comment by tukusejssirs** [comment]
Well, yeah, one click away, however, I think most of us are accustomed just to _look_ at the panel to see the current battery level. Even on Android, I use [BatON](https://play.google.com/store/apps/details?id=com.limi.baton) app to see the connection Bluetooth headphones battery level in the status bar.

Still I think that the icon can be change to include anything to reflect that it is indicating the battery level of the connected device, like :iphone: :battery: or anything really.

**Comment by andyholmes** [comment]
We probably won't be adding extra widgets like that into the shell UI. In the past, we've actually removed UI elements (including a battery widget) due to complaints that they're confusing and not consistent with GNOME Shell's design patterns.

The truth is I have less and less time to maintain GSConnect, and adding UI features that might need to include configuration options will only make that situation worse. So unless someone contributes and makes some commitment to maintain them, I can't really justify adding them.

Compare this with #506, which is not a feature I will ever use myself, but is written and used by the author who will notice and fix any problems that arise.
