### ISSUE TITLE
Control video players in Firefox

### ISSUE THREAD

**Issue by gnouts** [andyholmes/gnome-shell-extension-gsconnect#628]
Under Gnome Manjaro, I'm able to pause/play players in chrome based browsers (like chromium or brave). Even without installing GSconnect addon.
It works with Netflix, Twitch, Youtube, Spotify and Funkwhale (so I guess it works for every players). 

I would like the same under Firefox :smiley: 

I really don't know how it works. I guess it's tied to same chrome api or os level ?
I hope Firefox has this too or maybe the addon can workaround this to provide the same kind of service.

**System Details (please complete the following information):**
 - GSConnect version: 24
   - Installed from: manjaro community repo
 - KDE Connect version : 1.13
   - Installed from: Fdroid
  - Firefox version: 69.0
  - Chromium version: 76.0.3809.132

**Comment by ferdnyc** [comment]
@gnouts Chrome have added an MPRIS extension directly into the browser, for controlling web media. You can also see it show up as a Play icon (▶️) in the toolbar, when you're on e.g. a YouTube video page, which when clicked brings up a transport controller similar to the one in Gnome Shell / Android's notification shade.

For Firefox, and for Chrome before that existed, many of us have been using KDE's [plasma-browser-integration](https://community.kde.org/Plasma/Browser_Integration), which consists of a browser plugin and a native backend (much like GSConnect's own browser extension, or the one that enables installing via extensions.gnome.org). Typically there are distro packages for the native end, and the browser plugins are available from the browsers' add-on sites (links at that page).

I'm going to close this, since the solutions are entirely external to GSConnect. (Though they work great with it!) Feel free to reopen if there's some GSConnect piece that isn't working right, though.

**Comment by gnouts** [comment]
OK I guess thats what I was looking for :)
Thanks for the clarification !
