### ISSUE TITLE
Respect gnome notification settings

### ISSUE THREAD

**Issue by FlorianLudwig** [andyholmes/gnome-shell-extension-gsconnect#65]
When disabling notifications for an app in the gnome control center those notifications are still send to the mobile via gsconnect.

**Comment by andyholmes** [comment]
Just to clarify, in the image below do you mean **1** or **2**?

![not-settings](https://user-images.githubusercontent.com/1265208/37568680-f1876338-2a95-11e8-9f3b-188d60ba9bca.png)

Nowadays there are two notification buses to watch, `/org/freedesktop/Notifications` and `/org/gtk/Notifications`. GSConnect should definitely respect these settings, but if it's **1** that it's not respecting, I'll have to dig a little to find how to Gnome desktop negotiates these two since it's possible to send to either.

On the other hand, if it's **2** then that's expected behaviour.

**Comment by FlorianLudwig** [comment]
It is one, so everything is disabled
![screenshot from 2018-03-18 19-16-28](https://user-images.githubusercontent.com/432263/37569325-f03ca754-2ae0-11e8-99ed-8a6ecd0bcefa.png)

**Comment by andyholmes** [comment]
Okay, thanks for confirming, I'm looking into this now. I suspect the GNotification backend is forwarding notifications to the `org.freedesktop.Notifications` interface (even if they're disabled) for backwards compatibility, and that's the interface GSConnect current watches so it can catch eg. `notify-send` notifications.

**Comment by andyholmes** [comment]
Okay, so it seems like Rhythmbox, which I assume is the specific app in question, still uses libnotify. This makes things a little more tricky since the app-id is not sent over DBus, only the app name which may or may not be translated.

Apparently these settings are respected at the level of Gnome Shell, which makes this a possibly memory heavy thing to deal with, but I think I can fix it for now anyways and try to optimize later. Could you please tell me if this build fixes the issue:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1823283/gsconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
Here is an updated Zip for testing, built from master + notifications fix:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1858504/gsconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
I'm just going to push this since it's been almost two weeks since reported, but the fix is untested so YMMV.
