### ISSUE TITLE
Issue on gnome.org for a "share with" in Nautilus

### ISSUE THREAD

**Issue by Mannshoch** [andyholmes/gnome-shell-extension-gsconnect#651]
For your information:
https://gitlab.gnome.org/GNOME/nautilus-sendto/issues/3

I used gsconnect as an inspiration.

**Comment by ferdnyc** [comment]
@Mannshoch 

Mmmm... I'm not trying to discourage you at all, and maybe this'll go differently than I predict, but I suspect you're barking up the wrong tree by making that a request against nautilus-sendto. If the initial response you got didn't dissuade you, then I admire your... determination, but most likely the tone's been set for how that request will evolve. Mostly because there's... history, there. A _lot_ of history.

#### A (hopefully brief) history of nautilus-sendto

nautilus-sendto is one of many things that grew out of the long-defunct MeeGo project, and a long, long, LONG time ago — so long ago that my hair could've still been charitably described as "brown"<sup>1</sup> — it actually _did_ offer a lot more functionality. It used a library called libsocialweb to interface with then-nascent social network services, and attempted to provide a social sharing interface much like the one you envision. Really, it was ahead of its time.

So _far_ ahead of its time that none of it really worked like it should, libsocialweb eventually died out, and the last commit of any significance to the nautilus-sendto codebase was the one that _removed_ all of the social functionality and stripped it down to just an email-sending tool... and that was back in early 2013. It's been on translations-and-housekeeping life support ever since.<sup>2</sup>

#### Nautilus sharing functionality

All of which is to say, there's so little of anything _there_ in nautilus-sendto today, that there's no advantage to the requested functionality even being part of nautilus-sendto. It would make as much sense (probably more sense) for it to be implemented elsewhere. Either as a new, separate tool (one that could _replace_ nautilus-sendto, or possibly use it as the provider of its "Share to email" functionality), or directly in Nautilus itself.

If you're looking to lobby for such functionality (which I think would be great, but then I think puppies are great too), I think you've got an uphill battle regardless, but I'd suggest focusing on Nautilus itself, rather than nautilus-sendto. Check the issue tracker for Nautilus, see if there are existing requests for similar sharing features. I would lay money that there _are_, and if so then you can get an idea of how those have been received and what the progress is. **Only** if, somehow, there _aren't_ any existing requests for the same thing, then I'd file a new request with the Nautilus developers themselves, rather than focusing on a legacy project like nautilus-sendto.

But I can't imagine the idea hasn't been proposed, and then pushed off, multiple times in the past by now.

#### Notes
1. (I'm only 45, but apparently I signed up for the Steve Martin plan at birth. **#WhoKnew?**)

2. In fact, nautilus-sendto came close to being [sucked into nautilus itself completely](https://bugzilla.gnome.org/show_bug.cgi?id=680983), and the only reason that _didn't_ happen was because other applications (Evolution, primarily) also used it for their own "Send to..." functionality — it wasn't _actually_ nautilus-specific at all, and the nautilus developers didn't want those other applications to have Nautilus as a dependency just to provide an out-of-scope functionality like sending email.

**Comment by Mannshoch** [comment]
😲
Thanks a lot for your feedback. Fascinating what happened there, but also kind of unbelievable. I'm not able to understand this roll back to a simple "send to mail".

**Comment by andyholmes** [comment]
Seems like what you're looking for is something like the yet unimplemented "[Sharing](https://wiki.gnome.org/Design/OS/Sharing)" proposal.

The design page there spells out pretty well what would be [required to make that happen](https://wiki.gnome.org/Design/OS/Sharing#Technical_Details) which would also probably require a [sandboxed portal](https://github.com/flatpak/xdg-desktop-portal/issues/12), but things like this generally require someone to step up and really just do it.

As far as Nautilus extensions themselves, I've heard Carlos say somewhere that they're not very awesome at all (which I agree with) and will probably be replaced in the future with something else as the removal of legacy junk progresses in Nautilus.

**Comment by Mannshoch** [comment]
At moment ther is no other sharing issue (except [P2P](https://gitlab.gnome.org/GNOME/nautilus/issues/889) )

Would you propose that I create a new Issue on https://gitlab.gnome.org/GNOME/nautilus
and Link to 
https://wiki.gnome.org/Design/OS/Sharing
https://github.com/flatpak/xdg-desktop-portal/issues/12
and upload again my Mockup 

or is there another way I  could promote this?

**Comment by andyholmes** [comment]
Opening an issue in Nautilus is not a bad idea. But until someone implements the portal, GNOME Settings panel, support in the XDG Application/Desktop Entry specification, there's not much that can be done in Nautilus.

Unfortunately most GNOME projects are already starving for contributors. For reference, Evolution Mail and Evolution Data Server (which are *huge*) have basically been maintained by one person for at least the last 4 years.

You might have better luck starting a thread on https://discourse.gnome.org and trying to find people interested in joining in.

**Comment by ferdnyc** [comment]
> Thanks a lot for your feedback. Fascinating what happened there, but also kind of unbelievable. I'm not able to understand this roll back to a simple "send to mail".

I mean, really it came down to "this is the _only_ part of this thing that actually works, and people are still using that one tiny part." It was very much a pragmatic alternative to just mothballing the entire thing completely, or copying the email-sending source into the Nautilus tree (as was discussed).

**Comment by ferdnyc** [comment]
> Seems like what you're looking for is something like the yet unimplemented "[Sharing](https://wiki.gnome.org/Design/OS/Sharing)" proposal.

One fascinating 'easter egg' there is the random-seeming "See Also" link to https://wiki.apertis.org/Sharing. Apertis is apparently envisioned (realized? not sure) as a FLOSS system for _automotive_ use, which seems like an unusual focus for general GNOME sharing functionality.

Then again, that page on _its_ wiki hasn't been updated since December 2015, and the entire Apertis wiki seems to have been long since overrun by spam accounts.

The GNOME 'Sharing' designs are a year older than that, even — the last edits (other than the one in 2016 to add the Apertis link) were in August 2014. The envisioned functionality would definitely be a very good fit for GSConnect, though, if anything were actually implemented.

...Actually, come to think of it, one part "sorta" is: [GOA](https://wiki.gnome.org/Design/SystemSettings/OnlineAccounts/), which didn't yet exist in its current form when the Sharing designs were put together, but has since evolved to be a bit more robust in terms of _incoming_-data functionality.

The Sharing designs would require hooks going in the other direction, which even now is a much more dicey prospect. (Facebook, for example, has cut off access to all external publishing APIs. The Facebook-post mockup in those designs would be impossible today, as there is no longer any way for third-party software to publish to Facebook on behalf of user accounts.)
