### ISSUE TITLE
Don't connect to RemoteDesktop if no devices are connected

### ISSUE THREAD

**Issue by taaem** [andyholmes/gnome-shell-extension-gsconnect#671]
On GSConnect 27 Gnome always shows the "Your desktop is remote..." (I don't know the exact English words) and shows a orange indicator.

**Steps To Reproduce:**

1. Install GSConnect 27
2. See orange indicator

**Expected behavior**
Only activate the RemoteDesktop portal if the device is actually using the Remote Input or if that's not possible only if a device is connected.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/7108647/66939784-055e0180-f044-11e9-9432-1a725cf9a9e4.png)

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 27
  - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Fedora 31

 - **Paired Device(s):** Galaxy S9
 - **KDE Connect app version:** 1.13.2
 - **Plugin(s):** RemoteInput

**Comment by andyholmes** [comment]
So the problem here is latency and polling basically. We just can't detect if a device is "using" remote input, because it really just sends us discrete commands to do things. These are the two most obvious options:

1. We can set a timeout and close the session after a period where there are no input events, but that also means checking if the session is started for each input event, waiting if it isn't and deciding whether events should be queued or ignored until the session (possibly) starts. The latency could become noticeable when moving the mouse for example, because that often entails ~100 discrete events.

2. We can close the RemoteDesktop session when no devices are connected. That means having the service watch each device and when it disconnects polling all other devices to see if there are any other devices still connected. If you're on a network where your device frequently connects/disconnects this could get annoying and possibly lead to some race conditions with different sessions.

As far as warning the user that a RemoteDesktop session is about to start, this is what's often referred to as "security theatre", so we're probably not going to do that. The reality is there's nothing stopping any user application from starting a session or doing any manner of questionable things. For example, GSConnect gives no warning that it's inspecting all the content of desktop notifications, buffering all clipboard content, has full access to PulseAudio or any number of other things. We could give warning, but since there's no system-level or other way to force us to comply it would really just be for show.

I'm open to opinions on how users want this fixed.

**Comment by ferdnyc** [comment]
_Personally_, even though I'm not a particularly frequent user of remote input, I'd be fine with the first option despite the latency on reopen, and wouldn't even object if the first "wakeup" input action was lost entirely, as long as the timeout for dropping the remote-input link is long enough. It'd be analogous to a screensaver-wakeup keypress; those typically aren't delivered to the desktop/application either.

(So, specifically, I'm envisioning something like this:)
1. The user calls up the remote input interface, swipes on the screen, and the sharing icon appears on the Linux desktop. They now have remote control of the desktop's mouse/keyboard input.
1. The user does their thing — some mousing, some scrolling, some typing — then sets their phone down to go grab a refreshing beverage.
1. Some time — let's say 30 seconds, maybe shorter, maybe longer? — later, the sharing icon disappears from the top bar on the desktop.
1. User returns, carefully sets down libation a sufficient distance away from sensitive electronics to be outside of spill/splash zone, and picks up their phone.
1. A first swipe at the mouse input pad or a tap on the keyboard "wakes up" the remote connection, heralded by the shared-desktop icon's reappearance in the top bar. That input disappears into the ether. (Along with any others sent before the sharing is reestablished, if they're too quick and send multiple at once.) 
1. Once the icon's showing, the link is reestablished and it's back to remote-business as usual.

The way I see it, remote input is something akin to a remote-desktop connection, more than it's meant to be an extension of the system's direct input hardware. If someone wants an always-active, instant-response input device, wireless keyboards and mice can be purchased wherever computer peripherals are sold. :wink:

**Comment by taaem** [comment]
I would also prefer 1. in the way that @ferdnyc described.

**Comment by ferdnyc** [comment]
> 1. but that also means checking if the session is started for each input event, waiting if it isn't and deciding whether events should be queued or ignored until the session (possibly) starts. The latency could become noticeable when moving the mouse for example, because that often entails ~100 discrete events.

On this point... well, the way I'd implement something like this in Qt would be, I'd set a local state boolean `inputCxnActive` to `true` when I've opened the link, and also create a new `QTimer()` which I `connect(timer, SIGNAL(timeout()), this, SLOT(closeInputCxn()));`, then `timer->start(30000);` (ms). When the `QTimer` expires, `closeInputCxn()` will disconnect the sharing link, kill the timer, and set `inputCxnActive` back to `false`.

Each input event then only has to check the `inputCxnActive` variable -- if that's `true`, it delivers the event and uses `timer->start(30000);` to reset the `QTimer`, which ideally wouldn't add any noticeable latency even during rapid-fire streams of events.

If the connection has to be opened, that's obviously gonna take more time. But like I said, personally I think it's fine if events are dropped on the floor until the link's up.

I know JavaScript's execution model is a _bit_ different than Qt's event loop, so I'm not certain how well that would all translate to JS, nor how performant it would be. Feasible?

**Comment by andyholmes** [comment]
This should be fixed, although it's possible there are some weird cases where the session doesn't stop properly, so report any problems.

It basically worked out as @ferdnyc described above, but a bit trickier since starting the session (and initting the DBus proxy) are done in threads, so I had to use a kind of a mutex to deal with that.
