### ISSUE TITLE
Acronyms and proper nouns should not be translated.

### ISSUE THREAD

**Issue by JasonLG1979** [andyholmes/gnome-shell-extension-gsconnect#689]
**Describe the bug**

MPRIS is an acronym for "The Media Player Remote Interfacing Specification" a DBus interface spec and should not be translated nor marked as translatable. It should be treated as a proper noun in this sense.

**Comment by ferdnyc** [comment]
A fair point. (Not that it's actually _been_ translated by any of our translators, who tend to be pretty on the ball.) I've opened #690 to remove it from the translation master.

**Comment by JasonLG1979** [comment]
> A fair point. (Not that it's actually _been_ translated by any of our translators, who tend to be pretty on the ball.) I've opened #690 to remove it from the translation master.


SFTP and SMS are also acronyms and GSConnect is a proper noun so they shouldn't be translated either.

**Comment by ferdnyc** [comment]
> SFTP and SMS are also acronyms and GSConnect is a proper noun so they shouldn't be translated either.

See, now, I don't believe that's correct. There are two issues here:

1. A generic acronym like "SMS" _does_ get translated when localizing, especially when the translations target other **scripts** entirely. For example, the message "Share SMS" in our translation file is translated as:
   1. "共享短信" in our `zh_CN` localization
   1. "分享簡訊" in our `zh_TW` localization
   1. "Дели СМС" in our `sr` localization

1. Even where "SMS" _does_ get localized as "SMS", it still needs to be in the translation master because it's often found in longer strings. For example, that message "Share SMS" is translated as:
   1. "SMS megosztása" in our `hu` localization
   1. "SMS freigeben" in our `de` localization

It would actually be **more difficult** to construct those strings, if we excluded "SMS" from them. We'd have no way to know how to assemble that phrase with the correct grammar. So we include the entire string, and trust our translators to handle it correctly.

**Comment by ferdnyc** [comment]
(But as for translating acronyms, a lifetime of safer-sex messaging has drilled it into my head that "AIDS" in Spanish is "SIDA", so non-proper-name acronyms are definitely fair game for translation.)

**Comment by JasonLG1979** [comment]
Fair enough. I guess if the acronym is generic enough like SMS then I see your point.

**Comment by andyholmes** [comment]
I think the general rule is "Don't translate acronyms", but I left it after learning that because there wasn't much to gain and I figured leave it to the translator.

I guess some like SMS have just been around long enough to have entered common speech, but now that we have enough translations to guess which those are I'm in favour of dropping the ones that never get translated. :+1:

**Comment by andyholmes** [comment]
I'm going to close this one, since it seems unclear what languages might have translations for some abbreviateions (eg. SMS apparently). Any ways, translators can always just not translate string if they want. Maybe we'll revisit this next time we do a major cleanup.
