### ISSUE TITLE
Proposed re-ordering of items in the system-menu

### ISSUE THREAD

**Issue by amivaleo** [andyholmes/gnome-shell-extension-gsconnect#697]
Hi!

This is how the gsconnect-items are displayed in the system-menu:

![Schermata da 2019-11-06 10-24-53](https://user-images.githubusercontent.com/24316547/68285516-b3772d00-007f-11ea-92e2-9be11fe26451.png)

I translate them:
- Messages
- Ring
- Photos
- Files >
- Send file

To me, they could ordered in a more convenient way, according to their "meaning".

This is what I suggest:
- Ring
- Messages
- Photos
- Send file
- Files >

I pretend the "Jimmy" label for this "issue", because it is a veeeery pedantic suggestion! ☺

**Comment by ferdnyc** [comment]
Hmm. Prioritizing "Ring" doesn't make a lot of sense to me, it's a function I suspect only a tiny percentage of users _ever_ use even once. Messaging as the first item listed makes a lot of sense to me, as it's one of the extension's more popular features. I'd probably put either Photo or Share next, and stick either Ring or Mount way at the bottom (only because Mount is another small-percentage feature, _and_ it's the one that alters the menu itself).

...The biggest issue, though, is that I suspect most users are used to the menu in the order it's currently in, and arbitrarily shuffling it around on them might cause some annoyance. Nothing worse than when some software just decides to move everything around simply because it can.

**Comment by amivaleo** [comment]
I feel like that "Ring" and "Files/Mount" are somewhat misplaced. "Ring" in particular, also for the reason you said: it's almost never used. And all the others entries belong to the same context, in some sense.

> Nothing worse than when some software just decides to move everything around simply because it can.

Yep, definetely. That's definitely a point, indeed.

🤔

I think this "issue" is maybe way too much pedantic maybe.
Gonna close this. 💪

Thank you, Frank, for being well-disposed at any time. ^_^

**Comment by andyholmes** [comment]
FYI, you can actually re-order these by changing the dconf key for menu items:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/9b54aad174f97a012d8abe8fded8b377bee9aa71/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml#L54-L56

This was eventually intended to be exposed in some menu editor, it's just a bit complicated because some items are dynamic.

**Comment by amivaleo** [comment]
Settings! I love settings.

But... Can't find that key in dconf-editor. 🤔

**Comment by ferdnyc** [comment]
Mmm, I tried creating it...
```console
$ dconf write /org/gnome/shell/extensions/gsconnect/device/$DEVICE_ID/menu-actions \
'["sms", "share", "photo", "ring", "mount"]'
```
...It was not effective. (I previously tried versions containing both `"commands"` and `"runcommand"`, since `"commands"` from the schema file didn't look right to me — and I noticed that item never showed up, though I assume it's not valid for phones... but they were all equally ineffective.)

**Comment by andyholmes** [comment]
Oh, it's not really setup to react to changes, so you'll have to restart gsconnect:

```
touch ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```

**Comment by amivaleo** [comment]
> Mmm, I tried creating it...
> 
> ```
> $ dconf write /org/gnome/shell/extensions/gsconnect/device/$DEVICE_ID/menu-actions \
> '["sms", "share", "photo", "ring", "mount"]'
> ```
> 
> ...It was not effective. (I previously tried versions containing both `"commands"` and `"runcommand"`, since `"commands"` from the schema file didn't look right to me — and I noticed that item never showed up, though I assume it's not valid for phones... but they were all equally ineffective.)

When I give that command, I get

```
error: dconf key must not contain two consecutive slashes

Usage:
  dconf write KEY VALUE 

Write a new value to a key

Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)
```

🤔

**Comment by ferdnyc** [comment]
@amivaleo Did you replace `$DEVICE_ID` with your device ID? :wink:

Sounds like you left it unsubstituted, and since it's not a real variable (just a placeholder I made up) it would expand to the empty string, creating the two consecutive slashes.

**Comment by ferdnyc** [comment]
> Oh, it's not really setup to react to changes, so you'll have to restart gsconnect:

Yeah, nope, I'd tried that. At one point I think I even manually killed the `gjs` process and restarted it. I was going to reevaluate after a system reboot (still trying to wind everything down so I can do that), but I just tried the touch-reset again. And yet, stubbornly...
```sh
$ dconf read /org/gnome/shell/extensions/gsconnect/device/2ef99c50e6e759f8/menu-actions
['sms', 'share', 'photo', 'ring', 'mount']
```
![Screenshot from 2019-11-09 17-27-50](https://user-images.githubusercontent.com/538020/68535815-62349b00-0316-11ea-8f37-a60164fc6aea.png)

**Comment by ferdnyc** [comment]
(Maybe I created the key in the wrong place? It _looked_ like it should be a per-device setting, from the XML, but I may have gotten that wrong.)

**Comment by andyholmes** [comment]
Hmm, worked for me:

```
$ dconf write /org/gnome/shell/extensions/gsconnect/device/6ff41127f43b141f/menu-actions "['sms', 'share', 'photo', 'ring', 'mount', 'keyboard']"
$ touch ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```
![Screenshot from 2019-11-09 15-50-42](https://user-images.githubusercontent.com/1265208/68536501-cea89d80-0308-11ea-91a2-698f4f4607de.png)

**Comment by ferdnyc** [comment]
So `photo` and `mount` automatically re-position themselves to the end of the list, regardless?

(Why is Ring second in both of our screenshots, though, when it's not listed second in our action lists? It seems highly resistant to any attempts at repositioning.)

**Comment by andyholmes** [comment]
Well, as I said it's not really set up or tested to handle this usage, it's just the basic infrastructure exists since the menu is automatically populated.

**Comment by amivaleo** [comment]
> `$DEVICE_ID` [...] just a placeholder I made up [...]

C'mon, dude! :( I'm a self-taught geek who doesn't like to geek but who has to geek for living. If I see a bash command, I simply copy&paste it without thinking. 🙈
I'm like an old man with some geek skill. ☺

By the way, I don't know how to find that ID. 😁

**Comment by andyholmes** [comment]
You should be able to just use tab completion with `dconf`:

```
dconf write /org/gnome/shell/gsconnect/device/<tab><tab>...
```

**Comment by ferdnyc** [comment]
> By the way, I don't know how to find that ID.

And that was exactly why I had to use the placeholder, it's _easily_ obtainable but not very **conveniently** obtainable, to make it part of the sample commands. You're lucky I didn't just post commands with my own device ID and have you creating useless keys! :wink: 

By inspection in `dconf-editor` is one way. When you're at `/org/gnome/shell/extensions/gsconnect/` there's a `devices` key that holds a list. And if you navigate to the `device` (_without_ the 's') subfolder inside `gsconnect`, you'll see a further subfolder for each paired device ID. (Fortunately computer IDs are GUIDs, so they're much longer strings and easily discerned from mobile device IDs.)

Or you could...
```sh
$ dconf read /org/gnome/shell/extensions/gsconnect/devices
['2ef99c50e6e759f8']
```

**Comment by amivaleo** [comment]
> You should be able to just use tab completion with `dconf`:
> 
> ```
> dconf write /org/gnome/shell/gsconnect/device/<tab><tab>...
> ```

Yeah...
![Schermata da 2019-11-10 11-20-47](https://user-images.githubusercontent.com/24316547/68542356-35cb5e00-03ac-11ea-97c0-8f9060345307.png)
😁

> Or you could...
> 
> ```shell
> $ dconf read /org/gnome/shell/extensions/gsconnect/devices
> ['2ef99c50e6e759f8']
> ```

That worked! ^_^
Or... At least I got only one ID. Ty guys!

**Comment by ferdnyc** [comment]
Holy _balls_!

You know, this wouldn't be the worst idea ever conceived...
```sh
$ dconf dump /org/gnome/shell/extensions/gsconnect/device/[YOUR_ONE_ACTUAL_DEVICE_ID]/ \
 > /tmp/device-settings.txt
$ dconf reset -f /org/gnome/shell/extensions/gsconnect/device/
$ dconf load /org/gnome/shell/extensions/gsconnect/device/[YOUR_ONE_ACTUAL_DEVICE_ID]/ \
 < /tmp/device-settings.txt
```

Clear away the _astonishing_ amount of cobwebs there.

(Insert standard disclaimers about how I'm not responsible if the world blows up in your face, etc. It _should_ be pretty safe, and realistically the **worst** case is you lose your device settings and pairing info and have to re-create them. Which would take... what, like 5 minutes tops? :angel: )

**Comment by amivaleo** [comment]
> Holy balls!

?

Am I irritating? I'm a noisy guy! 😁

> `YOUR_ONE_ACTUAL_DEVICE_ID`

Good! Now I do understand it's not a global variable! :D

> Which would take... what, like 5 minutes tops?

No worries. I was used to even reinstall the entire distro because I faced some weird and completely absurd issue some year ago. Then I learned to be a bit smarter and avoid adding any f**king repo I found for ubuntu. 😅 Now I can still break fedora at anytime, but *wisely*!

By the way, why should I make such backup of my settings in gsconnect? I already change the order of the entries in the system-menu:
![Schermata da 2019-11-10 11-50-51](https://user-images.githubusercontent.com/24316547/68542783-5e555700-03b0-11ea-90b7-390b8caeb092.png)

☺

**Comment by ferdnyc** [comment]
(Note: All completely OT...)

> Then I learned to be a bit smarter and avoid adding any f**king repo I found for ubuntu.  Now I can still break fedora at anytime, but _wisely_!

Yeah, I will give Fedora this: their COPR system of community-maintained (read: "amateur-hour") package repos — and the fact that they're managed both (a) more aggressively, and (b) completely _distinct_ from the "system" package repositories, both official and third-party — beats the _hell_ out of the polluted mess that I've come to view the PPA system as.

Adding additional _system_ repos is explicitly held up as a "risk" action, and maintainers of third-party collections mostly understand that, if they wish to enjoy any sort of "semi-official" status, they're expected to play nice with each other's packages and try very very hard not to cause any ugly conflicts or breakages.

The crazy nonsense packages slapped together by Some Random User who has no clue what they're doing, then promptly forgotten about and never maintained so that it eventually falls into complete disrepair... the ones that are almost _guaranteed_ to cause weird conflicts and unpredictable interactions with the system repo sets... those all get relegated to COPR where the fallout can at least be minimized.

**Comment by amivaleo** [comment]
I only had to re-install Fedora once. I installed an unreleased version, I obviously did some bad thing and had some issue with the wifi.

Not a single issue since I re-installed that (and changed the wifi&bt card...).

I like Fedora: pure gnome, without any additional ubuntu-made app that tries to replace other system apps. For example: Ubuntu has a "Update"-something app
![Schermata da 2019-11-10 12-10-12](https://user-images.githubusercontent.com/24316547/68543099-14ba3b80-03b3-11ea-86c3-fae1ecbd0ea8.png)
It replaces gnome-software update feature.

My OCD couldn't accept that. 😁

That's it with this thread. We've gone way too far from the initial topic.

Thank you both, Frank and Andy, for being so patient, well-disposed and funny. :) I even tend to regret being so noisy with you. 😄

Thanks!
