### ISSUE TITLE
Advantage over mconnect

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#70]
Maybe you could also list the advantages [over your old project](https://github.com/andyholmes/gnome-shell-extension-mconnect/)/mconnect in general in the FAQ?

**Comment by andyholmes** [comment]
Well, in general there are no advantages, other than not needing MConnect or KDE Connect server.

GSConnect is a complete implementation of the protocol, so it is a server and a front-end, while gnome-shell-extension-mconnect (not to be confused with MConnect the server) is just front-end.

gnome-shell-extension-mconnect will probably continue to work for some time, but won't receive any more updates, translations or bug fixes.

If you find an advantage, or course, the Wiki is open to edits and your welcome to add to it :)

**Comment by rugk** [comment]
Okay, maybe advantage was the wrong word. "Difference" may be enough.

**Comment by andyholmes** [comment]
Oh, then that's already present in the description "_KDE Connect implementation for Gnome Shell 3.24+_" and the [Dependencies](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#dependencies) section of the installation page, "_This extension does not depend on an external program such as KDE Connect, MConnect or GConnect_".

But you're still welcome to add it to the Wiki/FAQ, as an explict "_How is this different from the MConnect extension?_",  if you like.

**Comment by thedonquixotic** [comment]
I think it would be worth doing as I found this page looking this up on Google and didn't know what mconnect was really. I get the gist of that it's a rewrite after reading it. And I'll gladly add it to the wiki myself once I get to a desktop (on my phone right now), but I also think it should be explicitly said on the Frontpage Readme and perhaps even said in the mconnect Readme etc. As a newbie dev and even newer Linux user, the distinctions you draw ok a technical level aren't immediately obvious without further explanation. I'd love to see this become a more "defacto" extension for gnome people.

And like, I know open source people aren't always open or concerned with this, but I'm a newbie dev coming from a design background so if you'd like some professional branding identity work done I'd be more than happy. I think having good marketing and presentation is important for open source projects because it helps make things more accessible and grow.

**Comment by andyholmes** [comment]
Sorry, I didn't respond to your offer earlier, but I've been quite busy. Yesterday I updated the "front page" readme with a somewhat better explanation of what GSConnect is, but in relation to KDE Connect not the previous extension.

Some branding might not be bad idea (at least after the rewrite is merged), so I'll describe what I think about this situation for when the time comes to decide.

* **MConnect**

  Although there's probably nothing wrong with the older MConnect extension, I have no intention of maintaining it anymore and I doubt the MConnect server is still being developed. I would probably remove it from Github and extensions.gnome.org if I could be certain no one was using it.

  One problem `gnome-shell-extension-mconnect` caused was confusing the difference between MConnect the server, MConnect the extension and KDE Connect in general. This was made worse because that extension supports the KDE Connect server and the MConnect server. This is why I decided on the name "GSConnect".
* **GSConnect**

  Although it's not part of the KDE Connect project, I consider GSConnect to be a part of the extended family and that's something that's important but sometimes hard to get across. It will never break compatibility with KDE Connect and I refuse to discuss protocol changes as a part of GSConnect development.

  Originally the KDE Connect team didn't like someone else re-implementing their server, but taking a very hard stance on that and insisting discussion happens within their project has reassured them somewhat. I also keep in weekly contact with the team and try re-file bug reports with them that affect us both.

  This is why I usually use the terms "KDE Connect team", "KDE Connect project", "KDE Connect protocol" and `kdeconnectd`. Although like you said using terms like "protocol" can be unhelpful for people who don't know or care much about how it works, just what it does and that it does it.
