### ISSUE TITLE
Messaging avatar icons no longer center aligning

### ISSUE THREAD

**Issue by nikolowry** [andyholmes/gnome-shell-extension-gsconnect#701]
**Describe the bug**

Avatar icons have been aligning to the top/left in their round containers since GNOME 3.34

**Expected behavior**

Avatar icons align center/center

**Screenshots**

![Screenshot from 2019-11-08 21-34-37](https://user-images.githubusercontent.com/597310/68521580-876ece00-0270-11ea-904a-8734516c0f07.png)

^ Apologizes for the small messaging window, but I don't have access to photo editing software at the moment and those messages in the screenshot are the only ones that didn't contain contacts' full names.

**System Details (please complete the following information):**

 - **GSConnect version:** 28
 - **Installed from:** GNOME Extensions Website (same behavior with AUR packages)
 - **GNOME/Shell version:** 3.34.1 Wayland
 - **Distro/Release:** Arch Linux

**Comment by andyholmes** [comment]
No problem about the window size, I see what you mean. Could you double-check that this is not an icon theme issue by testing with Adwaita?

As a guess, I'm thinking this might be a problem with the way we fetch icons, since we might target a specific size that is not distributed with Papirus. Some icon themes only ship certain sizes of PNG versions and rely on scalable SVGs, so that might be the issue.

**Comment by ferdnyc** [comment]
There's also the fact that that image is `3840×2160 px` (AKA "4K"), which I believe makes that a HiDPI situation right @nikolowry ? And the icons do seem conspicuously 50% undersized in each dimension.

**Comment by andyholmes** [comment]
Ah good point.

**Comment by amivaleo** [comment]
I can replicate this:

![Schermata da 2019-11-10 11-09-40](https://user-images.githubusercontent.com/24316547/68542226-a07b9a00-03aa-11ea-9d51-16fb74f65641.png)

In my case, it's due to the fonts. I changed the font size  in Tweaks > Fonts, so to make them bigger. I've been spotting tiny UI issues since then, in several apps.

In this specific case of gsconnect, sticking avatars to the top-left corner instead of having them vertical-aligned in the centre might be considered as a thoughtful UI. 🤔
That's why I didn't complain by opening an issue. 😁

**Comment by nikolowry** [comment]
@ferdnyc I do have a 4k monitor. Can confirm https://github.com/andyholmes/gnome-shell-extension-gsconnect/commit/169fbb1f0df93e13974250944028db163311a4dc resolved the sizing and alignment issues with avatar icons.

However, I now just saw a new bug with contacts' whom have a photo -- those avatars are rendering as quarter circles (like a pizza slice):
![Screenshot from 2019-11-10 11-17-35](https://user-images.githubusercontent.com/597310/68547181-9064ba00-03ac-11ea-984e-3ff7eb84052c.jpg)

@andyholmes should I open a separate issue for the bug posted above? Let me know if you need any other system details that might be useful.

**Comment by andyholmes** [comment]
Can you try with 71bafab? I figured Cairo would do those automatically, but I think this should fix it.

**Comment by nikolowry** [comment]
https://github.com/andyholmes/gnome-shell-extension-gsconnect/commit/71bafab91974d916aee308df088e5764a60b8f5e resolves contacts with photo issue.

Thanks for the quick fixes, really appreciated!
