### ISSUE TITLE
Link to keyboard from System Menu when enabled.

### ISSUE THREAD

**Issue by pwd-github** [andyholmes/gnome-shell-extension-gsconnect#707]
**Describe the bug**

**Steps To Reproduce:**

1. Enable remote keyboard on device
2. Try and access keyboard from laptop

**Expected behavior**

A link to open keyboard dialog should appear in System Menu rather than requiring users to add a keyboard shortcut.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34.1
 - **Distro/Release:** Fedora 31

**GSConnect environment (if applicable):**

N/A (Irrelevant)

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by ferdnyc** [comment]
@pwd-github 

That's actually possible today by setting a hidden `dconf` key (we were just discussing this in #697 over the weekend).
```sh
$ dconf read /org/gnome/shell/extensions/gsconnect/devices
['DEVICE_ID_1', 'DEVICE_ID_2', ... ]
$ # In case you're not sure if it's the right one
$ dconf read /org/gnome/shell/extensions/gsconnect/device/DEVICE_ID_n/name
'Hopefully your phone's identifier'
$ # Once you've got the correct device targeted
$ dconf write /org/gnome/shell/extensions/gsconnect/device/DEVICE_ID_n/menu-actions \
'["sms", "ring", "keyboard", "mount", "commands", "share", "photo"]'
$ # To activate the change
$ touch ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```

...That adds `"keyboard"` to the default list of plugins that will appear as actions in the menu.

That being said, assuming there's no issue with it being there, it makes sense to me that `"keyboard"` should just be added to the default list.

I just tested, and while disabling the Mousepad plugin entirely _does_ remove the menu entry, it's otherwise always there — even when the device has the "Receive remote keypresses" plugin completely disabled. That's _kind of_ a bummer, it'd be cool if GSConnect could be as smart about showing that menu entry as it is about the others. But, I don't know if that's possible... that's a question for @andyholmes .

**Comment by pwd-github** [comment]
Awesome, thank you @ferdnyc

**Comment by andyholmes** [comment]
> I just tested, and while disabling the Mousepad plugin entirely does remove the menu entry, it's otherwise always there — even when the device has the "Receive remote keypresses" plugin completely disabled. That's kind of a bummer, it'd be cool if GSConnect could be as smart about showing that menu entry as it is about the others.

Not really possible, no. As mentioned before, the remote device doesn't tell us what plugins are loaded or even available, just a list of packets it can support if they're all loaded.

**Comment by ferdnyc** [comment]
> Not really possible, no. As mentioned before,

You _**did**_ say that, yes. You said it, and I read it, and then it slipped right down between a couple of synapses way at the back, and it was just as if I'd never even seen it in the first place. My apologies.

**Comment by andyholmes** [comment]
No worries, it's near the bottom of my list of things to do. An implementation of this protocol is supported (in spirit) by the KDE Connect team, but our standing rule is that KDE Connect is the reference implementation, so that means implementing it in kdeconnect-kde, kdeconnect-android and gsconnect.
