### ISSUE TITLE
Inhibit Screensaver when Keyboard Dialog is Active

### ISSUE THREAD

**Issue by pwd-github** [andyholmes/gnome-shell-extension-gsconnect#708]
**Is your feature request related to a problem? Please describe.**
If the remote keyboard dialog is active, GSConnect should prevent the screensaver from executing.

**Describe the solution you'd like**
If the remote keyboard dialog is active, GSConnect should prevent the screensaver from executing.

**Describe alternatives you've considered**
Perhaps have it as an option if not on by default.

**System Details (please complete the following information):**
 - GSConnect version: 28
   - Installed from: extensions.gnome.org, GitHub Release download, distro package, ...

**Additional context**
Add any other context for your suggestion here, including screenshots if applicable.

**Comment by ferdnyc** [comment]
By remote keyboard "dialog"... do you mean the remote-input panel on the device end, or the keyboard-input window on the Linux side?

If the latter, why? I mean, if you _type_ into it the idle timeout should be reset (no?), and if you're **not** typing into it, why would its mere presence on the screen need to interfere with the local screensaver?

I'm not saying I disagree, **necessarily**... I'm just trying to figure out the purpose behind it, because it's not immediately clear to me what benefit that would have.

**Comment by andyholmes** [comment]
There's really no way to know if the keyboard function on the remote side is active. It will tell us if an entry in Android is active and waiting for keyboard input, but not if it's preparing to send us input. We'll need more info to tell if that's what you mean though.

**Comment by pwd-github** [comment]
I just meant that if the dialog is the active window on GNOME, then the screensaver should be inhibited.

**Comment by andyholmes** [comment]
Okay, I see what you mean now. I'm still not clear on the use case for this though. As @ferdnyc pointed out typing in the window will reset the screensaver timeout, so I'm not sure why you would want this dialog to inhibit the session if you're not using it? I'm not aware of any other windows doing this in GNOME.

**Comment by andyholmes** [comment]
Closing this one, since I'm not sure there's a real use case to inhibit the screen saver in this case. Feel free to re-open if you can present a real need for this.
