### ISSUE TITLE
Prevent Blank Screen right after video pause

### ISSUE THREAD

**Issue by 0x656b694d** [andyholmes/gnome-shell-extension-gsconnect#709]
**Is your feature request related to a problem? Please describe.**
For a video being played longer than the blank screen timeout, the mpris pause action causes the screen to go blank, and lock.

**Describe the solution you'd like**
I'd expect the screen timer to be reset, but only if that was video playback.

**Describe alternatives you've considered**
Dunno, might be some other harmless event could be triggered.

**System Details (please complete the following information):**
 - GSConnect version: 28
   - Installed from: extensions.gnome.org

**Additional context**
Not sure if it is the Gnome, mpris players problem or what. Reproducible at least with VLC and youtube.

**Comment by ferdnyc** [comment]
Hmm. This is a tricky one. I'm _sympathetic_ to the argument that the behavior you describe can be annoying, but at the same time I get why things are the way they are, and I'm not sure GSConnect _should_ really be doing anything to change it.

The central issue is that GSconnect doesn't get involved in the screensaver-inhibit functionality of the applications at all, currently, they just do what they do. And VLC, like many players, only inhibits the screensaver _during_ playback.

Normally, pausing the video "manually" involves some interaction with the UI, which inherently resets the inactivity timeout for the screensaver. So, this behavior isn't normally seen by most users, who control VLC (and similar apps) exclusively from their desktop session's direct input devices.

But the exact same behavior would occur when controlling vlc using any _other_ method that doesn't involve the desktop input devices — for example, logging in to the machine remotely and issuing `dbus` commands, or (I _believe_) using an IR remote supported by LIRC. Regardless how you interact with it, all VLC does when playback is paused is _release_ the inhibit. And if the timeout has expired since the last interaction, yes, the screensaver and/or suspend will fire immediately.

...Which is often what you _want_, and that's why I say it gets tricky. The same process (of allowing the idle timer to accumulate even during playback) is what allows the system to go to sleep **immediately** after VLC reaches the end of a long playlist with no user interaction, rather than having to wait out the full length of the idle timeout first. Which is a very nice feature that saves users a lot of battery life on their laptops.

I **_suppose_** you could make the argument that GSConnect's MPRIS messages count as "input", and therefore should reset the screensaver idle timeout. And in truth, "poking" the screensaver to reset it is a fairly simple matter; cheating off the `xdg-screensaver` script's paper, it just involves sending this D-Bus message:
```sh
        dbus-send --session \
                  --dest=org.gnome.ScreenSaver \
                  --type=method_call \
                  /org/gnome/ScreenSaver \
                  org.gnome.ScreenSaver.SimulateUserActivity \
                 2> /dev/null
```

Part of me feels like this is a decision that should be made by the player's MPRIS plugin/interface, not by GSConnect. But another part of me can see where they'd be coming from, if they were to argue, "We feel like this is a decision that should be made by the sender of the control message, not by its recipient, since they're in a better position to know whether the message "should be" considered UI interaction..." Hmmmmm. 🤔

**Comment by 0x656b694d** [comment]
I second your hmm, @ferdnyc.
I tried to send the SimulateUserActivity, but in my environment (Gnome on Ubuntu 19.10) there is no such method in this interface. And I haven't found a workaround to propose. Even Mutter.IdleMonitor ResetIdletimeout won't work.
I'd agree the player should manage the screensaver, but I'm afraid I'll have to test all of them and open separate issues. Will start with vlc perhaps.

**Comment by andyholmes** [comment]
Yeah, I'm not sure this is particularly our bug. MPRIS players are notoriously fidgety about their implementations, so that's not really a rabbit-hole I'm keen on venturing down :)

If you're looking to affect the idle timeout, you'll probably want to look at the [`logind`](https://www.freedesktop.org/wiki/Software/systemd/logind/) interface, instead of mutter or GNOME's screensaver though. I think the CLI command `loginctl` will work for that as well.

**Comment by ferdnyc** [comment]
> If you're looking to affect the idle timeout, you'll probably want to look at the [`logind`](https://www.freedesktop.org/wiki/Software/systemd/logind/) interface, instead of mutter or GNOME's screensaver though. I think the CLI command `loginctl` will work for that as well.

I **could** be wrong, but AIUI the _inhibit_ functionality is still owned by `gnome-session`, outside of `logind` control. It controls session activation in the user switching / seat allocation sense, but idling isn't really its purview. (Unless it's creeped to encompass it, as SystemD bits are wont to do.)

But there's even still a `gnome-session-inhibit` tool for creating inhibits, which communicates with that same `org.gnome.ScreenSaver ` DBus interface (which despite the legacy name, isn't so much about screensaving at all anymore).

**Comment by ferdnyc** [comment]
> I tried to send the SimulateUserActivity, but in my environment (Gnome on Ubuntu 19.10) there is no such method in this interface. 

Huh. That's odd. I've still got it, in 3.32 on Fedora 30.

![image](https://user-images.githubusercontent.com/538020/68635747-7ec40500-04c7-11ea-8b3c-17efaa32cc43.png)

**Comment by ferdnyc** [comment]
Hah! Though, actually attempting to _use_ it...
```
('g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: '
 'This method is not implemented (7)')
```

**Comment by ferdnyc** [comment]
VLC logging with verbosity=2 does log this when starting playback, though, on my X11/nvidia desktop using the OpenGL output:
```
main debug: looking for inhibit module matching "any": 2 candidates
dbus_screensaver debug: found service org.freedesktop.ScreenSaver
main debug: using inhibit module "dbus_screensaver"
main debug: Opening vout display wrapper
main debug: looking for vout display module matching "gl": 13 candidates
```

**Comment by ferdnyc** [comment]
Hm. There's also `org.gnome.Mutter.IdleMonitor`, which appears (under its `/org/gnome/Mutter/IdleMonitor/` interface) to be responsible, at a _very_ fine-grained level, for the input idle tracking. It has an interface _per_device_ (16, on my system) which implements `org.gnome.Mutter.IdleMonitor.GetIdleTime` methods that actually _work_ and return believable values.

There's also a `ResetIdleTime` method on each. Predictably...
```
('g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: '
 'This method is for testing purposes only. MUTTER_DEBUG_RESET_IDLETIME must '
 'be set to use it (19)')
```

**Comment by andyholmes** [comment]
It's worth noting that libgnome-desktop is advertised as basically private/unstable between major releases:

> The libgnome-desktop library provides API shared by several applications
on the desktop, but that cannot live in the platform for various
reasons. There is no API or ABI guarantee, although we are doing our
best to provide stability. Documentation for the API is available with
gtk-doc.

Generally, I prefer the freedesktop APIs when possible, which is what we use now in the [`session`](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/src/service/components/session.js) component.

**Comment by andyholmes** [comment]
Possibly related: https://gitlab.freedesktop.org/mpris/mpris-spec/merge_requests/1

**Comment by ferdnyc** [comment]
@andyholmes Looking at [the related bug report](https://gitlab.freedesktop.org/mpris/mpris-spec/issues/9), I don't believe it'll affect this at all. However, it does address a _different_ reported issue, #632.

**Comment by ferdnyc** [comment]
(If I read that correctly, the added timestamp is purely meant to enable the available MPRIS2 hosts to be sorted by recency of interaction, so transport commands can be directed to the correct — read: most-recently used — one.)

**Comment by andyholmes** [comment]
Ah good point, I guess last focus could still be a long time ago.

**Comment by andyholmes** [comment]
I'm still not sure this is an issue we should be dealing with in GSConnect, but I'm going to leave it open because I have some plans to fix up MPRIS stuff in v33. That might be a little while though, since I plan on v32 being the last version before GNOME 3.36 (unless there are some major problems) when we'll drop support for 3.34.

**Comment by andyholmes** [comment]
Going to close this one finally, since I think GSConnect is just not the right place to deal with this. A workaround might just be to twiddle the mouse with the remote input plugin.
