### ISSUE TITLE
Connecting two GSConnect instances

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#71]
Is it possible two connect two devices, where GSConnect is running?

With KDE Connect it is possible, but I thought maybe GSConnect is missing the "receiver" instance, so I installed `kdeconnectd`. This did work (at least the device did appear in the other device GSConnect' selection), but paring failed, maybe because it also installed kdeconnect (the client) and this likely causes problems.

However, with only GSConnect thwe connection does not seem to work. The devices don't detect each other.

**Comment by andyholmes** [comment]
Yes, GSConnect can connect to more than one device at time. Depending on what version of `openssl` you are using, you may be affected by #26 which has been fixed in master. If you build from master, be aware you may have to re-pair your devices.

Also be aware that running `kdeconnectd` and GSConnect at the same is possible, but will make it more difficult to connect and pair devices (cf. [Can I run this and KDE Connect?](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Frequently-Asked-Questions#can-i-run-this-and-kde-connect)).

In the KDE Connect protocol every device must be both a client and server. Which is to say, a KDE Connect implementation is both a client of another server (receives information about the remote device), and a server to another client (sends information about the local device).

**Comment by rugk** [comment]
I think you misunderstood what I want to do. I do not want to connect to a device, where I am already connected with another device. That works, AFAIK.

I want to connect:
* GSConnect on desktop
* GSConnect on laptop

(e.g.)

But, ah, https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/26#issuecomment-373010759 looks like it is the same problem.
