### ISSUE TITLE
Clipboard not working randomly in libreoffice (X11)

### ISSUE THREAD

**Issue by ccat3z** [andyholmes/gnome-shell-extension-gsconnect#716]
**Describe the bug**

When gsconnect is enabled, clipboard not working randomly in libreoffice and some rich text editor like wps.

**Steps To Reproduce:**

1. Turn on gsconnect
2. Copy some text in libreoffice
3. Paste these text into libreoffice or somewhere else, but nothing was pasted

**System Details:**

 - **GSConnect version:** 28 (8f84a2b6)
   - **Installed from:** AUR
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Arch Linux

**Possiable workaround:**

1. Copy twice time or three times.
2. replace `request_targets(this._onTargetsReceived.bind(this))` with `request_text(this._onTextReceived.bind(this))` in `src/service/components/clipboard.js:142` seems work.

**Comment by andyholmes** [comment]
This is effectively by design (`<insert i-told-you-so>`). The short version is we just don't handle rich text (RTF), which happened as a result of #500, #509 and #619. 

Strictly speaking, the KDE Connect protocol only supports plain text, and allowing RTF seems to cause problems because it can sometimes be serialized into its source with rich text annotations (which is not very useful) and sometimes not, which arbitrarily clears the remote clipboard.

**Comment by ccat3z** [comment]
This issue even happended when no device is conntected.

**Comment by andyholmes** [comment]
Hmm, looks like then we're looping around and clearing the local clipboard somehow.

**Comment by andyholmes** [comment]
This might be fixed in the [`clipboard-unsupported-formats`](https://github.com/andyholmes/gnome-shell-extension-gsconnect/tree/clipboard-unsupported-formats) branch I just pushed, but I'm not sure because I couldn't reproduce your problem in LibreOffice when I tried.

**Comment by ccat3z** [comment]
It's my fault. This issue seems not related to gsconnect. I use libreoffice for hours with no gnome extensions, but the bug still happened.
