### ISSUE TITLE
Browser extension buttons open the default browser

### ISSUE THREAD

**Issue by amivaleo** [andyholmes/gnome-shell-extension-gsconnect#721]
Hi!

I have both firefox and chromium installed. If I click on their respective browser extention buttons, I'd expect that the "correct" browser is loaded. Instead, the default browser is loaded.

This, I know, is a really trivial issue. If it requires easy and *very* short fixing, it would be a nice addition.

**Comment by ferdnyc** [comment]
> I have both firefox and chromium installed. If I click on their respective browser extention buttons, I'd expect that the "correct" browser is loaded. Instead, the default browser is loaded.

That's a difficult thing to do, since each browser can take many different forms. There are three different versions of just the _**official**_ Google Chrome for Linux (`google-chrome` aka `google-chrome-stable`, `google-chrome-beta`, and `google-chrome-unstable`), _plus_ `chromium` and all of the other variations. Firefox similarly has multiple builds and alternative releases.

Even if GSConnect tried to be smart and launch Chrome when I clicked the Chrome extension link, how could it know that I prefer to use `google-chrome-unstable` for browsing (but still have `google-chrome-stable` installed as well)? So, whatever link you click is just opened in your default browser.

**Comment by ferdnyc** [comment]
(In the old days, browser extensions used to be incompatible, so for example an `.xpi` was identifiable as a Firefox extension. But now they're all WebExtensions, so in _theory_ the same extension is compatible with any browser.

The big browser projects still don't trust each other enough to share a common "store" as the _source_ for their extensions, of course, and they prohibit installation of extensions from any source other than their official "store". So even though the actual **code** is compatible, extensions still have to be maintained in multiple places to target all of the supported browsers, and compatibility today just comes down to where the extension is hosted.)

**Comment by andyholmes** [comment]
Yeah, I'm not sure there is much we should do about this. The buttons aren't for installing the add-ons really, just pointing out that they exist.

Even if there were a way to decide what browser to open, it means spawning/forking a browser process from within the Preferences applet. Best to just let the desktop to decide what to do I think.

**Comment by amivaleo** [comment]
I see, it is indeed a very pedantic request. :D

Thank you for your nice replies as always!

(I didn't get my label this time 🙁️)
