### ISSUE TITLE
An inactive device icon always shows on panel when GS connect is started

### ISSUE THREAD

**Issue by jasiralavi** [andyholmes/gnome-shell-extension-gsconnect#725]
Hi and thank you for this wonderful extension!

Recently (I think since v28 maybe) whenever GS connect starts an inactive (sometime even unpaired) device icon shows in the panel. This happens even is the setting 'Display mode' is set to 'User Menu'.
If I open the settings and toggle the 'Display mode', the icon disappears. 
This icon appears in addition to the connected device icon, that is if I have a connected device while starting up GS Connect.
I'm using Ubuntu 19.10. 

![GS Connect 2019-12-02_12-40](https://user-images.githubusercontent.com/16372030/69938271-dc65d300-1502-11ea-83ff-d214333dd130.png)

![GS Connect 2019-12-02_12-42](https://user-images.githubusercontent.com/16372030/69938280-e12a8700-1502-11ea-9450-ffa29e8d0bf5.png)

**Comment by andyholmes** [comment]
Can you reproduce this in a standard GNOME Shell session? It looks like you are using some custom panel?

**Comment by ferdnyc** [comment]
I can say that it _doesn't_ happen in the standard GNOME 3.34 panel; as you can see the icon is only present when my phone is connected:

![Screenshot from 2019-12-02 11-19-55](https://user-images.githubusercontent.com/538020/69976243-a884b080-14f6-11ea-839f-6fe6c49d63eb.png)

![Screenshot from 2019-12-02 11-25-34](https://user-images.githubusercontent.com/538020/69976252-aae70a80-14f6-11ea-93a0-bb5f5c1f2c2c.png)

Does the panel you use show the traditional user menu, @jasiralavi ? What do you see for GSConnect _there_ when a device is connected vs. when one isn't? I'm only curious because it looks like your install is using custom icons for certain things, and as you can see GSConnect on my setup _never_ puts the **phone** icon in the panel, when it's set to User Menu display — it uses the same icon that's used in the menu. (But still only shows it when the phone is connected.)

If I set it to Panel display mode, _then_ I get a phone icon... but still it disappears when the phone disconnects.

**Comment by ferdnyc** [comment]
> Does the panel you use show the traditional user menu, @jasiralavi ?

Never mind, your _first_ screenshot makes that a dumb question.

**Comment by ferdnyc** [comment]
Oh, here's a question I _do_ have: When GSConnect is set to "User Menu" display mode, and your device is connected, what icon appears and where? As you can see in my screenshots, in that mode the icon is attached to the rest of the user menu icons (network, volume, power). The device icon in _Panel_ mode, OTOH, is detached from the menu set, sitting just to the left of it in the AppIndicator/system-tray space.

I'm wondering if some other extension or shell modification might be creating an AppIndicator for the GSConnect device, which then isn't properly cleaned up when it disconnects.

**Comment by jasiralavi** [comment]
I'm on Ubuntu 19.10 and use a few extensions including User Themes, Dash to panel, Appindicators and a few others. I use Arc Darker theme and Papyrus icon theme.

After playing around with different combinations of the extensions, I can confirm that the issue is only when the Dash to Panel extension is running.

**Comment by andyholmes** [comment]
Sounds like dash-to-panel is changing the visibility of PanelButtons, so this isn't an issue we can fix in GSConnect unfortunately.
