### ISSUE TITLE
"Keyboard not ready" error message

### ISSUE THREAD

**Issue by TitusLabienus** [andyholmes/gnome-shell-extension-gsconnect#734]
**Describe the bug**

First of all, thank you for the great extension. 

When I open the 'Keyboard' dialog, I get the error message "Keyboard not ready". Not sure if I am missing some setup step, but I have never got it working at all so far.

**Steps To Reproduce:**
1. Go to the main taskbar dialog.
2. Click on \<device name\>.
3. Click on "Keyboard"
4. The "Keyboard" dialog appears showing the message, "Keyboard not ready."

**Expected behavior**
Keyboard is ready

**Screenshots**

![KeyboardIsNotReady](https://user-images.githubusercontent.com/3390179/70708803-afbc7300-1cdb-11ea-9230-b88381f9a20f.jpeg)

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.
-> How can I generate a log? The wiki entry results in 404.

**System Details (please complete the following information):**

 - **GSConnect version: 30-1
   - **Installed from: aur/gnome-shell-extension-gsconnect
 - **GNOME/Shell version:** 1:3.34.1+56+gbb24df2f9-1
 - **Distro/Release: Arch

**GSConnect environment (if applicable):**

 - **Paired Device(s): Galaxy Note 9
 - **KDE Connect app version: 1.13.5
 - **Plugin(s): 

**Additional Notes:**

**Comment by andyholmes** [comment]
This means the phone is reporting that the keyboard is not ready to accept input. You must switch the KDE Connect keyboard in Android and select and editable text area.

**Comment by ferdnyc** [comment]
Perhaps something like one of these?
* Could not connect to 'KDE Connect Remote Keyboard' on '&lt;devicename>'
* No response from device keyboard, check input settings on '&lt;devicename>'

(The former would require our translators to translate the Android input layer labeling, which is a bummer. But, we could maybe "borrow" the strings from KDE Connect's translations file(s). And on the plus side, it might do a better job of directing people to exactly the thing they need to enable.)

**Comment by andyholmes** [comment]
A better string is a good idea, but also we could probably add a link to a Wiki page in the banner. I don't think this is even a full explanation:

> Make sure the Remote Input plugin is enabled and the remote keyboard is ready to receive input. If it is an Android device, make sure the KDE Connect keyboard is set as the active keyboard and either a text field is selected or the option to type at any time is enabled. If the remote device is a Linux desktop running Wayland, it requires GSConnect v## not running Debian/Ubuntu <= 19.10...

 If we do that, maybe a string like ***"The remote keyboard is not available"*** or something. It's tough to do in a sentence, because the keyboard might not be selected, entry not selected, plugin not enabled, device not connected, permissions not granted, we haven't performed the correct ablations to the phone manufacturer, etc

**Comment by ferdnyc** [comment]
@andyholmes 
> If we do that, maybe a string like _**"The remote keyboard is not available"**_ or something. 

...That works, though I think I'd still include the user's device name, only because it serves as a frying-pan-to-the-side-of-the-skull "subtle" pointer as to exactly _where_ they would need to address the problem.

Even "the remote keyboard" _could_ be interpreted (if someone was trying hard enough) to be a reference to the keyboard of the computer they're sitting in front of (with which they wish to _remotely_ type on their phone/tablet...)

**Comment by andyholmes** [comment]
> Even "the remote keyboard" could be interpreted (if someone was trying hard enough) to be a reference to the keyboard of the computer they're sitting in front of (with which they wish to remotely type on their phone/tablet...)

Good point. That's actually why I sort of broke down and just used `git` terminology push/pull.

**Comment by ferdnyc** [comment]
Now I'm having flashbacks to freshman year, a quarter-century ago. "Wait, so I run an X11 _server_ on my client, so that I can display a client application running on the remote server!? 🤯 "
