### ISSUE TITLE
Inconsistent newline and send keybindings between SMS notification reply dialog and messaging window

### ISSUE THREAD

**Issue by Atmelfan** [andyholmes/gnome-shell-extension-gsconnect#736]
**Describe the bug**

- The SMS notification reply dialog allows newline when pressing \<ENTER\> and sends on \<CTRL\>+\<ENTER\>
- The SMS messaging window sends message when pressing \<ENTER\> and inserts newline with  \<SHIFT\>+\<ENTER\>.

**Steps To Reproduce:**

1. Reply to a message, \<ENTER\> enters a newline and \<CTRL\>+\<ENTER\> sends message.
2. Open messages window, \<ENTER\> sends message, \<SHIFT\>+\<ENTER\> inserts newline.

**Expected behavior**

Both reply dialog and messages window to handle newline and sending consistently.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Unnecessary?

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.28
 - **Distro/Release:** Ubuntu 18.04

**Additional Notes:**

None

**Comment by ferdnyc** [comment]
@Atmelfan Unfortunately, GSConnect version 28 is no longer being developed. In later versions that dialog from point 1 is gone. GSConnect uses a newer feature of GNOME Shell notifications to Reply directly in the notification popup.

(Where, it seems that any one of <kbd>Enter</kbd>, <kbd>Ctrl</kbd>+<kbd>Enter</kbd>, _or_ <kbd>Shift</kbd>+<kbd>Enter</kbd> will send the message, as newline insertion isn't supported in the quick reply field. But that's out of our control anyway.)

If you click the notification, you get taken to the full Messaging interface, which operates as you describe in point 2.

So, I'm afraid this is effectively fixed (as much as we're able) everywhere it can be fixed, and since v28 won't be receiving any further updates it can't be fixed there.

**Comment by Atmelfan** [comment]
Thanks, I only checked the extension site so I didn't realize it that it was an old release.

**Comment by ferdnyc** [comment]
Note that `v28` (or maybe `v29`) *is* the last release compatible with GNOME 3.28, and therefore with Ubuntu 18.04. Later GSConnect releases require GNOME 3.32+, due to the use of those newer features I mentioned.
