### ISSUE TITLE
Messaging dialog fails to open

### ISSUE THREAD

**Issue by ofuangka** [andyholmes/gnome-shell-extension-gsconnect#738]
**Describe the bug**
When selecting to open the Messaging dialog, nothing happens.  It seems as though my set of messages contains an entry with no phone number. I can't say why.  FWIW, I have RCS enabled, and had sent 2 messages in very quick succession.  This is the second message, which appears in both the thread and the thread selection list.

```
  {
    "addresses": [
      {}
    ],
    "body": <redacted>,
    "date": 1574981734591,
    "type": 2,
    "read": 1,
    "thread_id": 62,
    "_id": 384,
    "sub_id": 1,
    "event": 1
  }
```

**System Details (please complete the following information):**
master 726c513
Gnome 3.34
ArchLinux
OnePlus 7 Pro
KDE Connect 1.13.5

**Additional Notes:**
I have a branch that resolves the issue, but it's not great because it just uses "Unknown Contact" when the message is in a thread, and other messages in that thread do contain the sender phone number.

https://github.com/ofuangka/gnome-shell-extension-gsconnect/tree/handle-undefined-number

**Comment by andyholmes** [comment]
Thanks for the code demonstrating the problem. I think we should just fix or strip incoming messages that have a broken `addresses` field. That would mean you'd have to clear your cache, but I think it's better to sanitize our input early than account for all the possible problems in the UI code.

**Comment by andyholmes** [comment]
Sorry it's been awhile, but I'm just getting around to having a closer look at this. This is a little more complicated than I first thought, because I forgot about some complications.

[redacted paragraph of immaterial rambling, typical of developers]

I think your approach might actually be better, although I made one modification. Would you like to try from git and confirm this fix still works for you?
