### ISSUE TITLE
Gnome-shell crash

### ISSUE THREAD

**Issue by sojusnik** [andyholmes/gnome-shell-extension-gsconnect#75]
After installing Gsconnect from Gnome's extensions site, my Gnome-shell started to crash at irregular intervals. Ubuntu's log viewer shows the following:

> JS ERROR: TypeError: menu is undefined
> SystemIndicator<._deviceKeybindings@/home/sojusnik/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:610:1
> wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
> SystemIndicator<._deviceAdded/<@/home/sojusnik/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:718:13

I have to re-enable all my extensions after the crash.

Happens on Ubuntu 17.10 with Gnome 3.26.2.

**Comment by andyholmes** [comment]
That's an odd error, probably Gnome Shell crashing isn't caused by this error though. The only cause of the error message I can think of is if the keyboard shortcuts were changed for a device after that device had been removed. See if this Zip will help:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1865841/gsconnect.andyholmes.github.io.zip)

**Comment by sojusnik** [comment]
@andyholmes Yes, you're right. Gnome is also crashing without this error message. Sorry for the false alarm.

**Comment by andyholmes** [comment]
Okay, no problem.
