### ISSUE TITLE
Non-obvious ⊗ button in plugins settings

### ISSUE THREAD

**Issue by mavit** [andyholmes/gnome-shell-extension-gsconnect#757]
In Advanced settings, three of the plugins, Contacts, Run Commands, and SMS, have a a button labelled with a white cross on a black disc.  It's not obvious to me what this button would do if I clicked it. 

**Describe the solution you'd like**
The buttons could have tooltips explaining their function.

**Describe alternatives you've considered**
The buttons could be explained in the wiki at https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Devices#plugins.

**System Details:**
 - GSConnect version: 31
 - Installed from: extensions.gnome.org

**Additional context**
I'm using the default Adwaita icon theme on Fedora 31.

**Comment by andyholmes** [comment]
Thanks for reporting. I believe the icon is `edit-clear-all-symbolic`, which I guess was merged with the other "clear" icons (eg. search fields) at some point.

These buttons are for clearing the cache (eg, SMS messages, contacts, etc), but should be pretty rarely used. This panel is labeled *Advanced* because generally disabling plugins saves single-digit KB of memory (and enabling/disabling plugins isn't well tested), and clearing the cache is only for situations where something breaks.

I think the best fix here is probably just to combine all the buttons into a single <kbd>Clear Cache</kbd> button.

**Comment by ferdnyc** [comment]
Yeah, it's definitely not about the icon _image_ per se (until recently on Fedora it was the little broom icon), it's that there's absolutely no context for it in the interface, so it has no obvious implication. Basically, it's one of those, "it's clear what it does, as long as you already know what it's for" things.

A single, central, explicitly-labeled cache-clearing button sounds like a replacement win, to me.

**Comment by andyholmes** [comment]
I'm working on this now, but it'll take a few minutes since I'm going refactor the cache code in a number of places. I think there's a butt-load of I/O going on that really doesn't need to happen and GSConnect apparently doesn't deal well with certain directories disappearing during runtime.

Not that anyone should be doing that anyways, but experience tells me if you add a new button everyone will to rush in there and press it a bunch of times :wink:

**Comment by andyholmes** [comment]
I kind of forgot how much of a nightmare the cache stuff was, so I've put off refactoring a lot of it until...well I guess I feel like it :man_shrugging: For now at least the UX issue of ambiguous buttons should be fixed.

Later I guess I'll have to rethink the whole caching thing, as "caching" at this point means loading butt-loads of JSON at startup and then keeping it in memory, then arbitrarily writing it to disk.

**Comment by ferdnyc** [comment]
"There are only two hard things in Computer Science: cache invalidation and naming things."
– Phil Karlton, Principal Curmudgeon<sup>1</sup> at Netscape

<sup>1</sup>: (Yes, that was his actual title.)

**Comment by andyholmes** [comment]
I think I'll go with *"Andy, Odd Numbered Star Trek Film"* :wink:
