### ISSUE TITLE
[Feature Request] Remote Desktop Support

### ISSUE THREAD

**Issue by fgheng** [andyholmes/gnome-shell-extension-gsconnect#762]
**Is your feature request related to a problem? Please describe.**
yes

Some apps are only available on the mobile phone. When I use the computer to work, I need to switch between the computer and the mobile phone, which is very time-consuming. This will be a very useful function if gsconnect can display the screen of the mobile phone on the computer.

**Describe the solution you'd like**
I'm sorry, I don't know much about the technical details

**Describe alternatives you've considered**
We can open a software to display the mobile screen on the computer, we can use the mouse to operate the mobile screen on the computer, and even we can drag and drop files between the mobile phone and the computer just like the sharing screen of Huawei mobile phone

**Comment by ferdnyc** [comment]
@fgheng 

This sort of request would be covered under this section of the Feature Request form that you filled out:

> GSConnect works in concert with the [KDE Connect](https://community.kde.org/KDEConnect) app on paired Android devices. Communication between GSConnect and the device is controlled by **KDE Connect**, _not_ GSConnect.
> 
> Any request that would require features not supported in KDE Connect, or would require GSConnect to deviate from the KDE Connect protocols, cannot be implemented. Any such requests should be made to the KDE Connect project. The requested functionality can only be implemented in GSConnect after support is added to KDE Connect.

If you'd like, you can file a feature request in the [KDE Connect Bugzilla](https://bugs.kde.org/enter_bug.cgi?product=kdeconnect) for this feature, as it would have to be implemented there first.

However, I'm afraid it's highly unlikely that KDE Connect would be able to create such a feature, since access to the contents of the device screen is restricted by the Android OS for security/privacy reasons. (If any app installed from Google Play could mirror your phone's screen to another computer, it could also transmit it to an unknown, and potentially malicious, remote system, allowing them to read your emails, view your bank accounts, etc...) Screen-mirroring tools are almost always system apps, granted special permissions by the device manufacturer which would be required for them to function.

**Comment by fgheng** [comment]
ok, thank you very much
