### ISSUE TITLE
Where do remote-controlled photos get stored?

### ISSUE THREAD

**Issue by fbruetting** [andyholmes/gnome-shell-extension-gsconnect#765]
**Describe the bug**

I can make photos from GSconnect and the camera on my phone does indeed make photos – but I cannot find those images, neither on the phone, nor on my computer…?

**Steps To Reproduce:**

1. Go to Panel ⇒ Phone ⇒ Photo
2. Phone opens the camera
3. Go again to Panel ⇒ Phone ⇒ Photo
4. Camera makes a photo
5. That file then cannot be found…?

**System Details (please complete the following information):**

 - **GSConnect version:** 31
   - **Installed from:** Package Manager
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Fedora Silverblue 31

**GSConnect environment (if applicable):**

 - **Paired Device(s):** OnePlus 6T with LineageOS
 - **KDE Connect app version:** 1.13.7
 - **Plugin(s):** Camera (?)

**Comment by andyholmes** [comment]
Received photos are saved in `~/Pictures`, but should also be opened in the default image view when received. I added a [quick note to the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Features#photo) about this.

**Comment by fbruetting** [comment]
I don’t receive it in `~/Pictures`, can I debug this?

**Comment by ferdnyc** [comment]
@fbruetting The path _shouldn't_ matter, I don't think, because KDE Connect should receive the photo taken as the result of the intent it uses to launch the camera in the first place.

If nothing's being sent back to GSConnect, the bug is most likely in KDE Connect, but you can verify that by starting the [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) process, and leaving the log capture window open while you go through the process of taking another photo.

If, after you trigger the phone's camera and it takes the photo, you don't see a message being sent _from_ the phone to GSConnect, then KDE Connect is simply never delivering the requested photo over the network link, and the problem is _definitely_ on their end.

(If you do see a message, and we mishandle it somehow, then definitely please share the logs  here so we can address that!)

**Comment by andyholmes** [comment]
Is this issue still valid?
