### ISSUE TITLE
breaks on fedora gnome 3.36.2

### ISSUE THREAD

**Issue by Qwerty2o** [andyholmes/gnome-shell-extension-gsconnect#840]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

**Steps To Reproduce:**

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.36, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by Orn1** [comment]
Hi @andyholmes I generated the support log, I've been having the same issues as well since yesterday, this is on a fresh fedora 32 install after a system update. I was working with no issue and suddenly poof

`
GSConnect Version: 37
GSConnect Install: user
GJS: 16402
XDG_SESSION_TYPE: x11
GDMSESSION: flat-remix-gnome
--------------------------------------------------------------------------------
-- Logs begin at Sat 2020-05-02 00:36:42 CEST, end at Sun 2020-05-03 22:07:52 CEST. --
May 03 22:07:39 systemd[1480]: Starting Cleanup of User's Temporary Files and Directories...
May 03 22:07:39 systemd[1480]: systemd-tmpfiles-clean.service: Succeeded.
May 03 22:07:39 systemd[1480]: Finished Cleanup of User's Temporary Files and Directories.
May 03 22:07:40 systemd[1480]: Created slice dbus\x2d:1.2\x2dorg.gnome.Shell.Extensions.slice.
May 03 22:07:40 systemd[1480]: Started dbus-:1.2-org.gnome.Shell.Extensions@0.service.
May 03 22:07:40 dbus-broker-launch[1578]: Noticed file-system modification, trigger reload.
May 03 22:07:40 dbus-broker-launch[1578]: Service file '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.Calendar.service' is not named after the D-Bus name 'org.gnome.evolution.dataserver.Calendar8'.
May 03 22:07:40 dbus-broker-launch[1578]: Service file '/usr/share/dbus-1/services/gnome-vfs-daemon.service' is not named after the D-Bus name 'org.gnome.GnomeVFS.Daemon'.
May 03 22:07:40 dbus-broker-launch[1578]: Service file '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.Sources.service' is not named after the D-Bus name 'org.gnome.evolution.dataserver.Sources5'.
May 03 22:07:40 dbus-broker-launch[1578]: Ignoring duplicate name 'org.gnome.Shell.Extensions.GSConnect' in service file '/usr/share/dbus-1/services/org.gnome.Shell.Extensions.GSConnect.service'
May 03 22:07:40 dbus-broker-launch[1578]: Service file '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.AddressBook.service' is not named after the D-Bus name 'org.gnome.evolution.dataserver.AddressBook10'.
May 03 22:07:40 dbus-broker-launch[1578]: Service file '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.UserPrompter.service' is not named after the D-Bus name 'org.gnome.evolution.dataserver.UserPrompter0'.
May 03 22:07:40 dbus-broker-launch[1578]: Service file '/usr/share/dbus-1/services/org.elementary.contractor.service' is not named after the D-Bus name 'org.elementary.Contractor'.
May 03 22:07:40 dbus-broker-launch[1578]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
May 03 22:07:40 dbus-broker-launch[1578]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
May 03 22:07:40 systemd[1480]: Starting Tracker metadata database store and lookup manager...
May 03 22:07:41 systemd[1480]: Started Tracker metadata database store and lookup manager.
May 03 22:07:41 systemd[1480]: Starting Tracker metadata extractor...
May 03 22:07:41 tracker-extract[5070]: Set scheduler policy to SCHED_IDLE
May 03 22:07:41 tracker-extract[5070]: Setting priority nice level to 19
May 03 22:07:41 systemd[1480]: Started Tracker metadata extractor.
May 03 22:07:43 systemd[1480]: dbus-:1.2-org.gnome.Shell.Extensions@0.service: Succeeded.
May 03 22:07:48 systemd[1480]: Created slice dbus\x2d:1.2\x2dorg.gnome.Shell.Extensions.GSConnect.slice.
May 03 22:07:48 systemd[1480]: Started dbus-:1.2-org.gnome.Shell.Extensions.GSConnect@0.service.
May 03 22:07:48 gjs[5148]: g_variant_new_string: assertion 'string != NULL' failed
May 03 22:07:49 audit: BPF prog-id=51 op=LOAD
May 03 22:07:49 audit: BPF prog-id=52 op=LOAD
May 03 22:07:49 systemd[1]: Starting Hostname Service...
May 03 22:07:49 systemd[1]: Started Hostname Service.
May 03 22:07:49 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 03 22:07:51 systemd[1480]: tracker-extract.service: Succeeded.
May 03 22:07:52 PackageKit[1239]: refresh-cache transaction /470_abbbbaac from uid 1000 finished with success after 72031ms`

**Comment by andyholmes** [comment]
Sorry, what is the problem exactly? It seems like the service has started as far as I can tell.

Did you update the extension without restarting gnome-shell?

**Comment by Orn1** [comment]
I genuinely have no idea what just happened, its working normally now I didn't do anything. I was working in blender and suddenly I decided to click the right tray and there it is, its showing and connected to my phone now. I really have no idea what just happened

**Comment by andyholmes** [comment]
I'm going to go ahead and close this one, since I really don't know what the report is about. Feel free to re-open if you still experience this and can describe what is broken.
