### ISSUE TITLE
ssh-copy-id copies my personal id and the gsconnect private.pem.

### ISSUE THREAD

**Issue by arnoudspammer** [andyholmes/gnome-shell-extension-gsconnect#843]
Hi there,

When i did a ssh-copy-id to a remote server with my regular ssh, I saw that one of the authorized keys is gsconnect itself. I find that strange. I can't find to see any reason why a random remote server wants that authorized keys from gsconnect. Is this expected behaviour?

i couldn't find any similar items regarding this subject so excuse me for putting it here.

Thanks in advance!

**Comment by andyholmes** [comment]
GSConnect adds it's private key to the `ssh-agent` so that it can be used to authenticate SFTP sessions with KDE Connect devices.

By my reading of the man page, your use of `ssh-copy-id` is offerring the key, rather than the remote server requesting it. I'm not really familiar with that tool though, so you might want to lookup how it works in these cases or ask some more familiar with it.

**Comment by andyholmes** [comment]
Closing, since I believe this is how the 3rd-party tool is intended to work.

**Comment by ferdnyc** [comment]
> It could be we're doing something improper by adding the private key instead of the public key, but I'm fairly certain it's necessary to authenticate sessions on our end.

It is; you can only add private keys to `ssh-agent`. It will _index_ them by their public fingerprint, and (critically) `ssh-copy-id` will only _export_ the public parts of the registered keys to the remote host — it only uses the private keys to check whether the keys in question are already installed on the remote end.

If I run `ssh-copy-id` to one of my own servers...
```console
$ ssh-copy-id -n ferd@192.168.12.100
# Then after...
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out
 any that are already installed
# It determines...
/usr/bin/ssh-copy-id: INFO: 10 key(s) remain to be installed -- if you are prompted
 now it is to install the new keys
=-=-=-=-=-=-=-=
# And then if I hadn't run it with -n, it...
Would have added the following key(s):
```
Then it displays a list like this:
```
ssh-rsa AAAA[noise] /home/ferd/.config/gsconnect/private.pem
ssh-rsa AAAA[noise] ferd@domain1
ssh-rsa AAAA[noise] ferdnyc@domain2
```
and etc.

The listing for GSConnect is the _public fingerprint_ that corresponds to `private.pem`. Unfortunately it can't have a comment associated with it, because the older key format didn't support comments. So it's listed by the key filename, which more-unfortunately is "`private.pem`". The same thing (literally, an identical listing) is shown if you run `ssh-add -L` to list the public fingerprints for the identities loaded into the agent.

So, the only thing that really _could_ be done to address this would be to rename `private.pem` to something like `gsconnect.pem`, so that the identity doesn't "seem" as much like a private key getting passed around. But it isn't, regardless.

**Comment by ferdnyc** [comment]
> I'm fairly certain it's necessary to authenticate sessions on our end.

The only other way to go on that would be to associate the GSConnect private key with the Gio mount, so that it doesn't need to be added to the agent. But I'm not aware of any way to do that sort of thing.

It'd be neat if Gio offered an API for it, though I can definitely appreciate the hassle that would be involved in managing key registrations securely. Much easier for them to just rely on the existing, robust `ssh-agent` featureset.
