### ISSUE TITLE
Feature Request: Selective/Explicit Clipboard Sharing

### ISSUE THREAD

**Issue by mirko** [andyholmes/gnome-shell-extension-gsconnect#86]
First of all: thank you so much for this project! I primarily was looking for a way to share the clipboard between my gnome running desktop and my Android device.

However I noticed, that I feel uncomfortable sharing *all* my clipboard content, as I trust my computer more than my Android device.

Right now I'm turning the sharing-option on and off but would much more prefer a button, e.g. in the tray menu, to actually share/push the content which is in my clipboard buffer at the very moment.

**Comment by andyholmes** [comment]
I think this is not a bad idea. At this point I'm generally putting all new features into the rewrite and only committing bugfixes and translations to the current release series, but I think this will be an easier to do there anyways.

**Comment by andyholmes** [comment]
I'm going to close this now, since this has been implemented in the rewrite and merged into master. It's now possible to auto-sync selecting to or from a device like before, but also selectively sync.

Selective syncing is a bit trickier, but I think I found a reliable solution that makes sense. Basically the clipboard content is buffered (privately) and can be "pushed" to the device or "pulled" from it using a keyboard shortcut:

![screenshot from 2018-09-22 06-02-06](https://user-images.githubusercontent.com/1265208/45917487-0fa3d100-be2d-11e8-8c70-0e1a7d6aec89.png)

**Comment by mirko** [comment]
Yeah, thanks!
But how do I get those "Clipboard Pull/Push" functionality to work?
Me - being on 945de369e23d5b9be5c2334dda48dace81d81db7 - only sees four possible Action Shortcuts.:

![screenshot from 2018-10-04 14-29-37](https://user-images.githubusercontent.com/106558/46473988-0a0d9a00-c7e2-11e8-9ddc-f6bb485c542f.png)
