### ISSUE TITLE
How do I determine if sudden inability to mount is with GSConnect or with KDE Connect?  

### ISSUE THREAD

**Issue by dln949** [andyholmes/gnome-shell-extension-gsconnect#873]
GSConnect 28, gnome shell 3.28.4, Ubuntu 18.04.4

The mount function suddenly just stopped working for one android device, it still works on another one.  (The file "share" function still works - both directions, starting from either the desktop or the android device.)  

I understand that no help/support will be provided for the version of GSConnect and gnome shell that I have.  

But, here is my question:  How do I at least determine that the problem is with GSConnect, or with KDE Connect - or with both?

**Comment by andyholmes** [comment]
There is an [entry in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#mount-doesnt-work) that briefly describes this. You can also [debug Gvfs](https://wiki.gnome.org/Projects/gvfs/debugging) to see if the problem is there.

Debugging the Android app is more involved and requires building from source code.
