### ISSUE TITLE
shell extension with error status; no icon

### ISSUE THREAD

**Issue by violetmage** [andyholmes/gnome-shell-extension-gsconnect#889]
**System Details**
- **gsconnect version:** 20 (via apt install)
- **GNOME/Shell version:** 3.36 (vanilla-gnome-desktop)
- **Distro/Release:** Ubuntu 20.04

the switch to enable gsconnect is always grey in extensions menu, with informative error icon next to it. however, settings panel is usable, devices can be paired, sms, file copy, etc. work [mostly](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/320) correctly.

changing display mode (user menu/panel) appears to do nothing.

logs have no useful messages; i.e. unrelated dbus/systemd output

no strange happenings are observed, only the complete absence of shell menus/icons for gsconnect.

am suspecting is simply old version of gsconnect, however am now curious where exactly is the problem

**Comment by andyholmes** [comment]
The current release is v39; v20 is unlikely to work well at all, as it's about a year and a half old.

You can go through the [changes since then](https://github.com/andyholmes/gnome-shell-extension-gsconnect/compare/v20...master) if you really want to figure how each bug or incompatibility was fixed, but it's probably easier to just install the latest version.

You should probably wipe all settings an uninstall before upgrading though.

**Comment by violetmage** [comment]
much thanks for fast reply

am have not yet reinstall from [extensions.gnome.org](https://extensions.gnome.org), however have found [matching bug in ubuntu launchpad](https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-gsconnect/+bug/1875184)

am suppose is no much you can do about ubuntu package...

anyway, thank you for reply and usefule software

**Comment by andyholmes** [comment]
Yes, around the time they packaged GSConnect for Ubuntu they wanted to ship it pre-installed like the sidebar extension, Dash-to-Dock. In the end they didn't have the developer time to maintain the package so have stopped updating it.

The only real difference is where the files are installed, so I wouldn't worry about it not being a package.
