### ISSUE TITLE
GSConnect should be part of Shell

### ISSUE THREAD

**Issue by lionirdeadman** [andyholmes/gnome-shell-extension-gsconnect#896]
**Is your feature request related to a problem? Please describe.**
Extensions in shell break with releases more often than not and make this functionality less accessible since they need to look for it.

**Describe the solution you'd like**
GSConnect could be part of gnome-shell.

**Describe alternatives you've considered**
I don't think there are alternative solutions

**System Details (please complete the following information):**
Irrelevant to idea.

**Additional context**
While the quality of code might not be optimal, I think with work, this could be part of gnome-shell. Worth mentioning that the release cycle of gnome-shell might make development a bit harder but I think it's a fair trade-off especially when considering that I believe GSConnect implements most of KDE-Connect so it would simply be a matter of adding things overtime. This would also make greater integration possible (such as settings in g-c-c potentially)

**Comment by ferdnyc** [comment]
This isn't a GSConnect feature request. You're welcome to propose integration over at the GNOME GitLab, but the extensions system was created specifically to give users the option to add functionality that the GNOME Shell team doesn't _want_ to provide as part of the base shell. They've always had a very minimal vision of the core environment.

**Comment by lionirdeadman** [comment]
@ferdnyc Well, would the developers here be open to doing this if it was accepted upstream from a design standpoint?

**Comment by ferdnyc** [comment]
@lionirdeadman Well, that's the thing, the Shell doesn't "come with" extensions. If KDE Connect functionality were part of the core Shell, the server part would most likely be rewritten as a C library, the settings would be integrated into `gnome-control-center`, etc. ­— it'd most likely be a very different codebase from GSConnect's. GSConnect in its current form isn't eligible to be part of the GNOME Shell distribution, specifically _because_ it's an extension, which is pretty much defined as "add-on features that aren't part of GNOME Shell".

(Would @andyholmes be willing to have the GNOME team take it off his hands? I can't imagine not!)

**Comment by ferdnyc** [comment]
I suspect you'd even get resistance simply because of the name "KDE Connect'. There are some very brand-conscious factions within the GNOME project, and I think they'd push back at integrating official GNOME functionality meant to interface with a KDE app. (Which... I can sort of understand how there might be concerns about user confusion, I suppose.)

So, to make the idea palatable there'd also be a need for either a "GNOME Connect" phone app (even if it was just a rebranded build of KDE Connect), or a more generically-named app that speaks the same protocol.

**Comment by andyholmes** [comment]
> Well, would the developers here be open to doing this if it was accepted upstream from a design standpoint? 
> [...]
> (Would @andyholmes be willing to have the GNOME team take it off his hands? I can't imagine not!)

The reality is we just have nothing to gain from this and neither does GNOME Shell. Only 10% of the code (that's an actual LoC comparison, not a guess) has anything to do with GNOME Shell to begin with, and most of that is a glorified DBus menu implementation.

The criticism of extensions breaking between releases is *grossly* overstated in general and wouldn't change whatsoever if the code were in GNOME Shell. The difference would literally what repository we push our commits to. Furthermore, I can tell you for a fact there is no benefit to porting to C (except in one singular, irrelevant case) because I did it well over a year ago.

If the upstream developers want to integrate GSConnect into the Shell they are more than welcome to, but I think it would be a mistake both technically and logistically.
