### ISSUE TITLE
No unmount for "Browse Files" connection?

### ISSUE THREAD

**Issue by ferdnyc** [andyholmes/gnome-shell-extension-gsconnect#9]
Browsing my Android device's filesystem via the sshfs mount to the KDE Connect app's built-in SSH server is pretty snazzy, and performs far better than I'd imagined it would. Very cool.

Am I correct that there's currently no supported way to _unmount_ the remote device's filesystem, after connecting to it through GSConnect? I was able to get the sshfs process stopped and the mount disconnected by switching the plugin off entirely, but that's a bit drastic and hardly convenient for regular use.

**_Ideally,_** from my POV, the phone would be connected up through Gio as a GMount. Then it would appear in the Nautilus sidebar when mounted, with an Eject icon provided allowing the user to disconnect it just like any other removable or remote user filesystem mount. 

But right now that doesn't seem likely to happen in the near term, since AFAICT it couldn't be done in GSConnect without changes also being made to the Android app. (Even the latest beta appears to **still** be using deprecated `ssh-dss` format host keys, and while GSConnect can work around that by enabling support for them on connection, I doubt Gio could easily be talked into doing the same.)

So, until that day when GSConnect is able to just hand the device-filesystem connection off to Gio for management as a standard GMount, and as long as it's forced to manage the remote mounts internally, it does seem like there should be a way to explicitly indicate, "OK, I'm done browsing this device, you can close the connection to its filesystem." Leaving mounts connected indefinitely anytime a device is browsed just feels like a recipe for trouble. The user still has the _option_ to do that, of course, simply by not unmounting their device. But for peace of mind, it's probably best if they also have the option to be a little more cautious.

**Comment by andyholmes** [comment]
> Am I correct that there's currently no supported way to unmount the remote device's filesystem, after connecting to it through GSConnect?

Well, there is an `unmount()` command, but there's no way to call it in the GUI (although you can use D-Feet).

> But right now that doesn't seem likely to happen in the near term, since AFAICT it couldn't be done in GSConnect without changes also being made to the Android app. (Even the latest beta appears to still be using deprecated ssh-dss format host keys, and while GSConnect can work around that by enabling support for them on connection, I doubt Gio could easily be talked into doing the same.)

That's pretty much exactly everything right :( As far as I know the SFTP server is actually a built in Android class that uses some ancient apache code. I've pretty much combed the web, documentation, gio/gvfs source code and have an [open question on stackoverflow](https://stackoverflow.com/questions/47268278/how-can-i-show-a-mounted-and-or-mountable-sshfs-in-nautilus) about this.

> Leaving mounts connected indefinitely anytime a device is browsed just feels like a recipe for trouble. [...] it's probably best if they also have the option to be a little more cautious.

As I understand it, SSHFS is actually just a FUSE wrapper for SFTP (transaction based) so it's not technically doing anything when not used.

I could never think of an elegant way to put it in the Shell UI. I could add an unmount item to the folder list, but there would be no way to tell if you were just mounting it to unmount it, since there's no indication that it's mounted to begin with. It might be possible to add an "emblem" to the browse icon since StIcon can take a GIcon as a parameter, but I'm not sure if it will respect GEmblemedIcon or not.

**Comment by ferdnyc** [comment]
> As I understand it, SSHFS is actually just a FUSE wrapper for SFTP (transaction based) so it's not technically doing anything when not used.

\*nod\* And security does appear to be good, even from a root shell I couldn't see the contents of `/run/user/$UID/gsconnect/$CONNECTION_ID/`. But the mount does show up in the `/bin/mount` listing as 
```
kdeconnect@$PHONE_IP:/storage/emulated/0 on /run/user/$UID/gsconnect/$CONNECTION_ID \
type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=$UID,group_id=$GID)
```
for as long as the sshfs process is alive, which may be of concern to some. But my motivation is definitely more "housekeeping" than anything else, I'm a neurotic and like to "put things away" when I'm finished using them. ;-)

> I could never think of an elegant way to put it in the Shell UI.

In terms of Nautilus, where it really belongs, there probably isn't a great one. Or, there is one, but it's the sidebar GMount Eject-button support that GSConnect can't currently use.

But perhaps in GSConnect itself. What about an Eject button that gets added to the header of the Devices pane entry (next to the Unpair padlock button), but only when the mount's active? That way, there would at least be a _way_ to easily unmount the filesystem, even if it's somewhat hidden.

**Comment by andyholmes** [comment]
> What about an Eject button that gets added to the header of the Devices pane entry (next to the Unpair padlock button), but only when the mount's active?

That's possible. I've been meaning to come back to that device pane since it's almost pointlessly minimalist, but it would probably result in being compelled to rewrite the whole preferences dialog.

It would be nice to also have an indication of whether or not the device is mounted in the shell, too. I added this item for unmounting on my local copy, but you still have to open the menu to use it, which could mean mounting it just to unmount it:

![menu-test](https://user-images.githubusercontent.com/1265208/33446656-9beeb118-d5b5-11e7-9265-f2fd1ffae055.png)

It's difficult making custom changes in the shell while cooperating with the different shell themes, otherwise I could use a dashed border, colored background or something else to indicate it's status. v6 is actually the first release I bothered to expose CSS classes for the UI for that reason. Even using Cairo/Clutter to create custom graphics like I did with the battery arc is difficult without knowing what the theme is going to do ahead of time.

**Comment by ferdnyc** [comment]
> It's difficult making custom changes in the shell while cooperating with the different shell themes, otherwise I could use a dashed border, colored background or something else to indicate it's status. v6 is actually the first release I bothered to expose CSS classes for the UI for that reason. Even using Cairo/Clutter to create custom graphics like I did with the battery arc is difficult without knowing what the theme is going to do ahead of time.

And HiDPI adds a whole 'nother set of wrinkles. I don't know if anyone has tested GSConnect on a HiDPI display yet, but when they do you may get [reports that menu elements aren't scaling how you'd expect](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/413)

**Comment by andyholmes** [comment]
Ha, I hadn't even thought of that. I got a "great deal" on my laptop which turned out to mean it had a 720p screen instead of the usual 1080p, so I don't even know how it looks on a regular screen; probably ascetic since I make everything tiny.

One of my favourite tricks is to inherit Gtk/Gnome Shell elements and manipulate them only when necessary so I can piggy-back on the work of others. I read a post about how they had automagically fixed HiDPI issues in KDE, but I doubt Gnome has. I'll probably just wait until the error reports start coming in.

I have no idea how many people are actually using the extension yet, but I wager not many since it hasn't been reviewed on e.g.o yet. Although there has to be a few thousand lines of amateur javascript to comb through, so I don't blame them.

**Comment by ferdnyc** [comment]
> Ha, I hadn't even thought of that. I got a "great deal" on my laptop which turned out to mean it had a 720p screen instead of the usual 1080p, 

I've long hated that laptop pricing seems like it's exponentially related to the resolution of the screen. (The same way desktop prices, 20 years ago, seemed like they were multiples of the number of Megabytes of RAM in the system. Now, going from 4GB to 8GB might only add $20.) The preponderance of new models still featuring 13", 14", even 15" screens with 1280x720/800 or 1400x900 resolution, the same density we've had for a decade now — and _significantly_ lower res than even a midrange smartphone! — beggars the imagination. But if you even want to go up to 1080p, to say nothing of going wild and springing for 2K or 4K, the prices _start_ from double. (And then if you do opt for the high-res display, you get punished with a choice between either squinting a lot, or suffering through HiDPI interface scaling. Which AIUI still mostly sucks everywhere except macOS.)

> so I don't even know how it looks on a regular screen; probably ascetic since I make everything tiny.

Well, on my 21" 1080p desktop screen, particularly from the User Menu perspective I quite like GSConnect as it's one of the few things that manages to provide a reasonable number of controls without wasting crazy amounts of space. Which, yeah, in the Gnome 3.0 design language probably means everything is way too small. Especially for all of Gnome Shell's touch-input users. Who, as I said in that bug report I linked to, I have been assured are a totally real thing that actually exist. 🙄

**Comment by andyholmes** [comment]
I'm going to mark this closed for now, since there's at least an unmount item in the extesnion, I might revisit it later though.
