### ISSUE TITLE
Add a better error message if `kdeconnectd` is running

### ISSUE THREAD

**Issue by alexanderadam** [andyholmes/gnome-shell-extension-gsconnect#936]
**Is your feature request related to a problem? Please describe.**

Simply to avoid manual commands to solve [this issue](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error).

**Describe the solution you'd like**

An error message that explains better what happened and that it is advised to uninstall / kill kdeconnect.

**Comment by andyholmes** [comment]
I think this would be overreaching for GSConnect to offer this option, to be honest.

Although it would be slightly more convenient, this is an issue that should only ever happen once and terminating processes it doesn't control probably isn't something GSConnect should be doing. Ultimately `kdeconnect-kde` should be uninstalled if the user is running GSConnect and that's definitely not something we can/should be doing.

**Comment by ferdnyc** [comment]
Yeah, it's not one extension's job to interfere with the processes from a completely different service, just because they happen to want access to the same network ports. It's not even remotely _the same_, of course, but there is a **small sense** in which this is like saying, "Firefox should terminate Google Chrome and make itself the default browser when it starts up." On a tightly-locked-down system that fully isolated processes, GSConnect wouldn't even be **able** to do what you're suggesting. It's exactly the sort of cross-domain meddling things like SELinux are designed to prevent. 

It might be possible to enhance the detection of a running `kdeconnectd`, and to present more details to the user directly rather than making them come read a Wiki troubleshooting page. I doubt a PR to add more robust checking would be turned down. But the user is the only one who can make decisions about what should be running on their system.

**Comment by alexanderadam** [comment]
The browser comparison is actually a bad example. GSConnect cannot work at all when the the port is used. Browser can, however, happyily coexist and are working flawlessly even if you have two different browsers installed. The functionality is not broken.
In this example functionality is broken, however.

A user, who decided to give GSConnect a try, might encounter a very unhelpful message and GSConnect is simply not working.

IMHO at least the error message should be made more helpful then.
I'm fine with not adding the option but please change the error message then at least (I will modify the issue to make it representing this).

**Comment by ferdnyc** [comment]
> The browser comparison is actually a bad example. 

Agreed, as I sort of tried to acknowledge even as I was making it. All analogies are bad analogies, but that one's worse than most.

I mean, the thing of it is: there really **is** no apt comparison. I'd have used a better analogy if I could think of even **one**, but I can't. I can't come up with any comparable situation that would provide guidance or set precedent here. 

Something which, all by itself, is pretty significant. (Well, unless anyone else has one I'm just missing.) My impression, though, is that what you're suggesting just _isn't done_ — and I mean that in the moralizing sense. Well-behaved software **does not DO** such things. It is _improper_.

It's a fairly uncommon situation that got us here, admittedly. It's pretty unusual for a userland service to require exclusive use of a specific network port -- that's something more typical of system services, which can claim exclusive rights. User services, even network servers that take incoming connections (bittorrent clients & the like) are typically able to operate on any port, since it's expected there will be conflicts between them.

(That the KDE Connect protocol makes no accomodations for this is also the source of another open bug: Two users on the same computer can't both run GSConnect simultaneously. In every way, the KDE Connect protocol operates exactly like a system service.)

> A user, who decided to give GSConnect a try, might encounter a very unhelpful message and GSConnect is simply not working.

Always a danger, though I agree it's one we should take all reasonable steps to minimize. 

> IMHO at least the error message should be made more helpful then.

Full agreement. TBH I don't really remember how it's presented now, but suggestions for how user feedback can be improved are always welcome. I'm really not sure how much ability GSConnect has to examine the running process list to detect `kdeconnectd` -- @andyholmes surely would have a better handle on that. There's sure to be _some_ way to do it. It wouldn't even be that difficult to just run `ps` and scrape the output, if it should come to that.

**Comment by andyholmes** [comment]
> IMHO at least the error message should be made more helpful then.

Currently known errors get roughly the same notification, since we can offer better help on the Wiki that can be updated for different distributions:
```
Title: Network Error
Body:  Click for help troubleshooting
```

This points [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Error#network-error):
> GSConnect requires ports **1716-1764** for **TCP and UDP**. This error means another program is using those ports, usually KDE Connect (`kdeconnectd`).
> 
> GSConnect does not require the KDE Connect desktop application and will not work with it installed. If KDE Connect is installed, you should stop the process and uninstall it.

What are you suggesting as an improvement for the error message?

**Comment by alexanderadam** [comment]
> since we can offer better help on the Wiki that can be updated for different distributions

But this wiki doesn't seem to be updated very often, it doesn't even handle cases of different distributions right now and `Network Error` is still not very speaking.

> What are you suggesting as an improvement for the error message?

If `kdeconnectd` can be detected (like suggested earlier by @ferdnyc), maybe something based on the two hints in the wiki, like:

> GSConnect is unable to work because KDE Connect is currently running. GSConnect does not require the KDE Connect desktop application and will not work with it installed. Please stop the KDE connect or uninstall it.

I'm not good at English grammar so this should be reviewed by someone who is good at it.
But I guess _everything_ will be more speaking than `Network Error` :wink:

**Comment by andyholmes** [comment]
> But this wiki doesn't seem to be updated very often, it doesn't even handle cases of different distributions right now and Network Error is still not very speaking.

Well, that page itself was updated a little over two weeks ago, although really the solution hasn't changed in ~3 years. We could add information to it for different package managers now I guess.

Usually the actual error is `EADDRINUSE`, but we don't actually check the error code since binding to the port could fail for other reasons. I think `Network Error` is a little more use-friendly, but we could pass through the original error message I guess.

> If kdeconnectd can be detected...

`lsof` is the easiest way to check the problem, but may require privileges to run. We could also probably use `pidof`, but still spawning a subprocess is kind of lot of work to do for a pretty uncommon error. To do either, we'd also probably have to add another `meson` option for NixOS.

I'm all for improving the experience, but I'm not sure what we can really do other than guess-work, knowing we'll still redirect to the Wiki any ways.

If we do change the message from `Network Error` it should be something very short since we'll still need the notification body to indicate it can be clicked for more information. Do you have a suggestion for a short, notification title that doesn't require us to spawn subprocesses trying to guess if kdeconnect is the problem? I kind of think `Network Error` is an okay, user-friendly compromise :thinking:

**Comment by andyholmes** [comment]
Sorry, I should have been clearer. Currently the notification looks like this:

![Screenshot from 2020-09-08 00-18-25](https://user-images.githubusercontent.com/1265208/92445312-079fe180-f169-11ea-923d-383a970cb2f6.png)

All detected errors get the same body that indicates it can be clicked, since we know we will redirect to the Wiki for more detailed information. If we replace the body, there will then be no indication that clicking the notification will have any effect.

Your current proposed notification would look like this, which doesn't give any indication that more help is available by clicking on the notification:

![Screenshot from 2020-09-08 00-25-27](https://user-images.githubusercontent.com/1265208/92445978-01f6cb80-f16a-11ea-927f-a06493580e00.png)

We could pass through the actual error message which would be more accurate, but is not very user-friendly:

![Screenshot from 2020-09-08 00-29-32](https://user-images.githubusercontent.com/1265208/92446411-a1b45980-f16a-11ea-9687-8f8cd00700d9.png)

Would something like this be better?

![Screenshot from 2020-09-08 00-50-51](https://user-images.githubusercontent.com/1265208/92448511-8bf46380-f16d-11ea-91f9-17447bd3f054.png)

**Comment by alexanderadam** [comment]
You could simply add "`Click for more information`" to `The port, that GSConnect needs is blocked. Please close / uninstall the blocking application (probably KDEConnect).`

But I guess I am biased anyway. :wink: 

@ferdnyc what's your opinion on that?

**Comment by ferdnyc** [comment]
@andyholmes : Is the wiki content translated, currently, or is it English-only? I can't remember. 

If the latter, then that's one pretty strong argument for including as much detail as can reasonably be provided in the actual error messages themselves, which can then be localized.

Could the difference be split? For the heading, the last version by @andyholmes with the port-in-use message. For the link text, something like "You may need to uninstall kdeconnect. Click for more info." (Or "Click for details", w/e.)

**Comment by ferdnyc** [comment]
Obviously that requires customizing the link text for that one error, but since it's a hard fatal one _and_ seems more than usually likely to bite unsuspecting first-time  GSConnect users (and almost ALWAYS first-timers), maybe it's worth the special-casing.

**Comment by andyholmes** [comment]
> Is the wiki content translated, currently, or is it English-only? I can't remember.

It's in english, but non-english users are generally accustomed to translating web pages and the shell commands on that page basically explain the problem any ways.

I'm afraid I'm going to put my foot down on the notification body, for the following reasons:

1. I'm not convinced this error is both common and confusing enough to complicate the error handling
2. We state clearly in several places that GSConnect conflicts with KDE Connect
3. In a new session, GSConnect will actually beat out KDE Connect and take the port first
4. KDE Connect itself only silently logs an error message, providing no help or a way to restart the service

I'm willing to amend the notification title, but the explanation and help is better displayed on the wiki than in a notification.
