### ISSUE TITLE
The "Files" menu item is greyed out

### ISSUE THREAD

**Issue by skerit** [andyholmes/gnome-shell-extension-gsconnect#938]
**Describe the bug**

The files option is greyed out and I don't know why.

**Steps To Reproduce:**

1. Go to the settings screen of the phone in Gsconnect on the PC
2. Click on the 3 vertical dots
3. The "Files" (or "Bestanden" in my case) option is disabled and greyed out

**Expected behavior**

I should be able to browse the files of my device. Everything's configured on my phone and it used to work. At least something should tell me why it's disabled.

**Screenshots**

Can't take a screenshot because that crashes wayland

**Support Log**

(Where is the log stored? The "Review log" button attempts to open it in Totem unfortunately)

**System Details (please complete the following information):**

 - **GSConnect version:** 41
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36.5
 - **Distro/Release:** Manjaro

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy S10
 - **KDE Connect app version:** 1.14.2

**Comment by ferdnyc** [comment]
_Totem_?!!? Well, that's a new one!

The GSConnect log isn't stored anywhere on disk, everything goes to the systemd journal -- what happens is, when you start data collection for a report, GSConnect switches into debug mode and greatly increases its log output over normal levels. So, while the dialog is open, every action will produce detailed logs, which are also collected for review. 

When you hit the review button, it's _supposed_ to open your default text editor with the log messages that were collected. They'd be loaded from a temp file, though, if they're saved to disk at all. But since that's not working, you could just run `journalctl -e` from your user account (without `sudo`) to view the user journal starting from the end (the most recent logs). Everything collected would be there as well.

You may still want to double-check your default text editor settings as well, though. 😉

**Comment by ferdnyc** [comment]
(Regarding the central question of why Files would be grayed out... honestly I didn't know that it _could_ be grayed out. @andyholmes  made some changes to how GSConnect interfaces with Gvfs to handle the SSH connections for remote file browsing, this may be new behavior related to that -- either intentional or unintentional.)

**Comment by skerit** [comment]
Oh! Didn't even think about checking the journal. Is there anything I can do to trigger some sshfs check? Because right now it's only showing soundcard info :)

**Comment by ferdnyc** [comment]
@skerit 

And those messages [might not even be ours](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/891#issuecomment-655747415).

Unfortunately, in terms of the SSH setup we're largely at the mercy of Gvfs, which tends not to be particularly forthcoming. So, SSH logging is unfortunately rather poor. (On _both_ ends. The KDE Connect app's ssh logging is just as anemic, and plenty of users have set up `adb` debugging connections to trace the Android side of the process only to come back with similar reports: "OK, well, when this fails it logs the exact same nothing as when it succeeds."

**Comment by ferdnyc** [comment]
The lack of logging is irritating, especially since commandline SSH can produce _extremely_ (even unnecessarily) verbose traces of its negotiations with the other end of the link.

But in thinking about it, what I _can't_ say is whether that output is free of sensitive information regarding things like ciphers, private key details, data about the user identity on either the remote or local host, etc.

i would not be at all surprised if the verbose trace output produced by libssh is **not** sanitized enough to store it in persistent logs (or sanitized at all, really). Which would make it unsuitable for logging, as doing so would create a security vulnerability merely by making those details accessible to anyone who can view the logs. Not an ideal situation either way, of course.

**Comment by andyholmes** [comment]
It's hard to say why this has happening, but a greyed out menu probably means there are no items in the *Files* submenu. It's pretty unlikely that would happen, but you might want to double-check the Android app has a directory configured.

In `master` we no longer rely on the remote device to report these directories and instead enumerate them automatically, but that change hasn't been well tested and isn't in v41. If you want, you can test the current state of master ([Instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)):

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/5180442/gsconnect%40andyholmes.github.io.zip)

Other than that, there weren't any drastic changes between v39 and v41 ([diff](https://github.com/andyholmes/gnome-shell-extension-gsconnect/compare/v39...v41#diff-d8474cfbc67583b31e22d438d6e2a772)) and the only change that seems related is this:

```diff
@@ -359,7 +363,8 @@ var Plugin = GObject.registerClass({
             filesItem.set_label(_('Files'));
             filesItem.set_submenu(filesSubmenu);
 
-            this.device.replaceMenuAction('device.mount', filesItem);
+            let index = this.device.removeMenuAction('device.mount');
+            this.device.addMenuItem(filesItem, index);
         } catch (e) {
             logError(e);
         }
```

This was pretty much what `replaceMenuAction()` did, so I don't see that could've caused the problem.

**Comment by andyholmes** [comment]
Should be fixed in v42, please feel free to re-open if the issue persists.
