### ISSUE TITLE
rename 'private.pem' to 'gsconnect.pem' to avoid confusion when using ssh-copy-id

### ISSUE THREAD

**Issue by iGadget** [andyholmes/gnome-shell-extension-gsconnect#980]
As per @ferdnyc's comment on https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/843:

The listing for GSConnect is the _public fingerprint_ that corresponds to `private.pem`. Unfortunately it can't have a comment associated with it, because the older key format didn't support comments. So it's listed by the key filename, which more-unfortunately is "`private.pem`". The same thing (literally, an identical listing) is shown if you run `ssh-add -L` to list the public fingerprints for the identities loaded into the agent.

So, the only thing that really _could_ be done to address this would be to rename `private.pem` to something like `gsconnect.pem`, so that the identity doesn't "seem" as much like a private key getting passed around.

_Originally posted by @ferdnyc in https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/843#issuecomment-649567657_

**Comment by andyholmes** [comment]
Sorry, I don't really think the potential regressions here are worth the minor benefit of renaming `private.pem`. It would also mean maintaining two code paths for ~2 years or more while we wait for the current cycle of LTS distros to be replaced.

**Comment by iGadget** [comment]
@andyholmes thanks for your reply. Just out of curiosity - What kind of regressions are you worried about? As a non-coder I figured this would be as simple as performing a search-replace command throughout the code and be done with it. For existing installations run a little script which renames existing private.pem codes and (optionally?) provides a symlink with the old name in case some external script/app/setting hard-coded the old private.pem file. But clearly I'm missing something? Please, enlighten me :-) 
As for maintaining two code paths, would such a change be impossible to push to the LTS distros as well?

**Comment by andyholmes** [comment]
> What kind of regressions are you worried about?

Regressions are, almost by definition, unexpected side effects of changes. Additionally, moving a file during startup would be a blocking operation and a blocking a check for the filename would have to be done every startup. At this point, it seems like the deed is done, since the `private` name has been added into the `ssh-agent` and I'd question if there's any changing that after the fact.

Even if there were no risk of regression I don't see that this is really worth doing just so `ssh-copy-id` titles the public key `gsconnect`, sorry.

> As for maintaining two code paths, would such a change be impossible to push to the LTS distros as well?

No, not really possible. We don't have any input into what software or version distributions ship, and LTS distributions avoid these types of changes specifically for the reason that they can in regressions.

**Comment by ferdnyc** [comment]
> Even if there were no risk of regression I don't see that this is really worth doing just so `ssh-copy-id` titles the public key `gsconnect`, sorry.

I have to agree, even though it was my idea. (I said at the time that it's the only thing we **could** do; I never said we _should_ do it.) Especially since the change has zero effect on **actual** security, merely on the user's _perception_ — and only for those very, very few users who are using a relatively obscure tool, and using it in (IMHO) a fairly cavalier way.

Even the `ssh-copy-id(1)` man page, while failing to actually _recommend against_ running `ssh-copy-id` with the entire contents of the `ssh-agent` keyring, comes up with plenty of reasons why it's a good idea to run it using the `-i` flag instead:

>      The reason you might want to specify the -i option in this case is to
>      ensure that the comment on the installed key is the one from the .pub
>      file, rather than just the filename that was loaded into your agent.  It
>      also ensures that only the id you intended is installed, rather than all
>      the keys that you have in your ssh-agent(1).  Of course, you can specify
>      another id, or use the contents of the ssh-agent(1) as you prefer.

And if it's run that way, this issue becomes moot.

> At this point, it seems like the deed is done, since the `private` name has been added into the `ssh-agent` and I'd question if there's any changing that after the fact.

There actually is, fairly easily. A second `ssh-add` command with the same key (from the same or a different filename) will update the stored entry; it overwrites with the newest data each time. But that's the least of the concerns here.

>  Additionally, moving a file during startup would be a blocking operation and a blocking a check for the filename would have to be done every startup. 

Not just that. To be really complete about it, you'd have to:
1. Check for the new filename
2. If not found, check for the _old_ filename
3. To be safe (and allow a downgrade path), probably **copy** the old filename to the new name.
4. Load the new-filename identity into the SSH agent. 

And that logic would have to be left in the code pretty much indefinitely, because there's no way to control what point in the future people running older versions will finally upgrade to a more recent version that includes the migration code.

> > As for maintaining two code paths, would such a change be impossible to push to the LTS distros as well?
> 
> No, not really possible. We don't have any input into what software or version distributions ship, and LTS distributions avoid these types of changes specifically for the reason that they can in regressions.

And the current GSConnect code isn't compatible with the GNOME libraries present on those LTS releases, so they _can't_ run a newer GSConnect. No way we're backporting this change to N outdated versions of GSConnect, even if we _could_ then get all of those users to update.

**Comment by iGadget** [comment]
Thanks @andyholmes and @ferdnyc for your elaborate explanations. Fair enough, I'm going to apply your suggestions and work around the 'problem'. Appreciate the effort, kudos to you both and have a great weekend.
